#!/usr/bin/env python3
"""Run the binding against headless wgrender and assert what it gets back.

    test/check.py [WGRENDER_DIR]

Headless is wgrender's own test target (`make HEADLESS=1`): no window, GPU or audio,
and WGR_HEADLESS_FRAMES runs a fixed number of frames and returns, so the checks can
assert values rather than only compile.

This is the library's own test suite, not an example's. It lived in examples/simple-
hxcpp while the binding and that port grew together, which meant the thing that
decides whether wgrender-hx works was inside one of the things it was testing.

It runs three generators in --check mode first, because each guards a different way
the binding can be wrong without failing to compile:

  gen_raw    the C surface is generated from wgrender's headers; a stale one declares
             an API that no longer exists
  coverage   a stale omissions list hides a decision as a to-do
  setters    wgrender's headers name every value a setter refuses, and this fails if
             one of those sentences is not repeated in the binding's own docs
  sources    project/wgrender.xml lists wgrender's C files for an installed copy to
             compile, and this fails when wgrender gains or loses one

Then it builds the suite twice: native, where it runs, and against the js binding,
where there is no host loop but a wrapper that exists only on hxcpp fails here rather
than in whichever example first happened to call it.
"""
import os
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
WGRENDER = pathlib.Path(
    next((a for a in sys.argv[1:] if not a.startswith('--')), None)
    or os.environ.get('WGRENDER_DIR', ROOT / '../wgrender-c')).resolve()
HAXE = os.environ.get('HAXE', 'haxe')
BUILD = ROOT / 'test/build'
FRAMES = os.environ.get('WGR_HEADLESS_FRAMES', '5')


def run(cmd, **kw):
    print('+', ' '.join(str(c) for c in cmd), flush=True)
    subprocess.run([str(c) for c in cmd], check=True, **kw)


def main():
    for tool in ('gen_raw.py', 'coverage.py', 'setters.py', 'gen_sources.py'):
        run([ROOT / 'tools' / tool, '--check', WGRENDER])

    print('wgrender (headless)')
    run(['make', '--no-print-directory', '-s', '-C', WGRENDER, 'all', 'HEADLESS=1'])

    BUILD.mkdir(parents=True, exist_ok=True)
    (BUILD / 'check.xml').write_text(f"""<xml>
<!-- Generated by test/check.py. Headless links no window, GPU or audio. -->
  <files id="haxe">
    <compilerflag value="-I{WGRENDER}/include" />
  </files>
  <target id="haxe">
    <lib name="{WGRENDER}/build/headless/libwgrender.a" />
    <lib name="-ldl" />
    <lib name="-lm" />
    <lib name="-lpthread" />
  </target>
</xml>
""")
    (BUILD / 'check.hxml').write_text(
        '# Generated by test/check.py — the headless library, for the checks.\n'
        f'-D WGR_BUILD_XML={BUILD / "check.xml"}\n'
        f'-cp {ROOT / "src"}\n'
        f'-cp {ROOT / "test"}\n'
        '--main CheckBindings\n'
        f'--cpp {BUILD / "cpp"}\n'
        '-D HAXE_OUTPUT_FILE=check-bindings\n'
        '-dce full\n')
    run([HAXE, BUILD / 'check.hxml'], cwd=ROOT)

    binary = BUILD / 'cpp/check-bindings'
    # assets beside it, so the checks that load a real file can find one
    link = binary.parent / 'assets'
    if link.is_symlink() or link.exists():
        link.unlink()
    link.symlink_to(WGRENDER / 'examples/assets')
    run([binary], env={**os.environ, 'WGR_HEADLESS_FRAMES': FRAMES})

    print('type-check (js)')
    run([HAXE, '-cp', ROOT / 'src', '-cp', ROOT / 'test', '--main', 'CheckBindings',
         '--js', BUILD / 'check-js.js', '-D', 'js-es=6'])
    return 0


if __name__ == '__main__':
    sys.exit(main())
