#!/usr/bin/env python3
"""Run the binding against headless wgrender and assert what it gets back.

    test/check.py [WGRENDER_DIR]
    test/check.py --lists      only the WebHost list guards: pure Python, for CI

Headless is wgrender's own test build (its `<os>-headless` CMake preset): no window, GPU or audio,
and WGR_HEADLESS_FRAMES runs a fixed number of frames and returns, so the checks can
assert values rather than only compile.

This is the library's own test suite, not an example's. It lived in examples/simple-
hxcpp while the binding and that port grew together, which meant the thing that
decides whether wgrender-hx works was inside one of the things it was testing.

It runs three generators in --check mode first, because each guards a different way
the binding can be wrong without failing to compile:

  gen_raw    the C surface is generated from wgrender's headers; a stale one declares
             an API that no longer exists
  coverage   a stale omissions list hides a decision as a to-do
  refusals   wgrender's headers name every value a call refuses, and this fails if
             one of those sentences is not repeated in the binding's own docs
  keys       src/wgr/Key.hx is generated from wgr_keys.h, and this fails when a key
             moves; its static_asserts then fail the C++ build too
  sources    project/wgrender.xml lists wgrender's C files for an installed copy to
             compile, and this fails when wgrender gains or loses one

Then it builds the suite twice: native, where it runs, and against the js binding,
where there is no host loop but a wrapper that exists only on hxcpp fails here rather
than in whichever example first happened to call it.
"""
import os
import pathlib
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / 'tools'))
from wgrpath import find  # noqa: E402
import wgrbuild  # noqa: E402
ROOT = pathlib.Path(__file__).resolve().parent.parent
WGRENDER = find()
HAXE = os.environ.get('HAXE', 'haxe')
BUILD = ROOT / 'test/build'
FRAMES = os.environ.get('WGR_HEADLESS_FRAMES', '5')


def run(cmd, **kw):
    print('+', ' '.join(str(c) for c in cmd), flush=True)
    subprocess.run([str(c) for c in cmd], check=True, **kw)


def main():
    for tool in ('gen_raw.py', 'gen_keys.py', 'coverage.py', 'refusals.py', 'gen_sources.py'):
        run([sys.executable, ROOT / 'tools' / tool, '--check', WGRENDER])

    print('wgrender (headless)')
    lib, libs = wgrbuild.desktop(WGRENDER, headless=True)

    BUILD.mkdir(parents=True, exist_ok=True)
    (BUILD / 'check.xml').write_text(f"""<xml>
<!-- Generated by test/check.py. Headless links no window, GPU or audio. -->
  <files id="haxe">
    <compilerflag value="-I{WGRENDER}/include" />
    <compilerflag value="-I{ROOT}/host" />
  </files>
  <!-- The guest glue, because wgr.Wgr's lifecycle goes through it on both targets
       now; before that, nothing the checks touched reached wgr_guest.h. -->
  <files id="wgrguest">
    <compilerflag value="-I{WGRENDER}/include" />
    <compilerflag value="-I{ROOT}/host" />
    <file name="{ROOT}/host/wgr_guest.c" />
  </files>
  <files id="__main__">
    <compilerflag value="-I{WGRENDER}/include" />
    <compilerflag value="-I{ROOT}/host" />
  </files>
  <target id="haxe">
    <files id="wgrguest" />
    <lib name="{lib}" />
{chr(10).join(f'    <lib name="{l}" />' for l in libs)}
  </target>
</xml>
""")
    (BUILD / 'check.hxml').write_text(
        '# Generated by test/check.py — the headless library, for the checks.\n'
        f'-D WGR_BUILD_XML={BUILD / "check.xml"}\n'
        f'-cp {ROOT / "src"}\n'
        f'-cp {ROOT / "test"}\n'
        '--main CheckBindings\n'
        f'--cpp {BUILD / "cpp"}\n'
        '-D HAXE_OUTPUT_FILE=check-bindings\n'
        '-dce full\n')
    run([HAXE, BUILD / 'check.hxml'], cwd=ROOT)

    binary = BUILD / 'cpp/check-bindings'
    # assets beside it, so the checks that load a real file can find one
    link = binary.parent / 'assets'
    if link.is_symlink() or link.exists():
        link.unlink()
    link.symlink_to(WGRENDER / 'examples/assets')
    run([binary], env={**os.environ, 'WGR_HEADLESS_FRAMES': FRAMES})

    # Everything above builds with -dce full, which is what hid a real bug: a
    # `static inline` that is only valid *because* it is inlined still gets an ordinary
    # method generated, and full DCE deleted that copy before anything checked it. A
    # debug build keeps it. Codegen only (-D no-compilation), so this costs seconds.
    print('code generation without DCE (what a debug build does)')
    run([HAXE, '-D', 'WGR_BUILD_XML=' + str(BUILD / 'check.xml'),
         '-cp', ROOT / 'src', '-cp', ROOT / 'test', '--main', 'CheckBindings',
         '--cpp', BUILD / 'cpp-nodce', '-D', 'HAXE_OUTPUT_FILE=check-nodce',
         '-dce', 'no', '--debug', '-D', 'no-compilation'], cwd=ROOT)

    # -D wgr-listing makes wgr.macros.WebHost.build() return at once, as it does inside its own
    # listing compile, so this types the macro without making a host or spawning a child.
    print('type-check (js), with the WebHost macro')
    run([HAXE, '-cp', ROOT / 'src', '-cp', ROOT / 'test', '--main', 'CheckBindings',
         '--js', BUILD / 'check-js.js', '-D', 'js-es=6',
         '-D', 'wgr-listing', '--macro', 'wgr.macros.WebHost.build()'])

    print('WebHost lists')
    return check_webhost_lists()


def check_webhost_lists():
    """The two lists src/wgr/macros/WebHost.hx keeps by hand still match what they describe.

    Both are hand-kept on purpose -- the guest ABI is this binding's own contract, and
    what the JS reaches on the Emscripten module only exists inside function bodies --
    so this is what stops them drifting. One already had: the runtime list in the
    prototype carried HEAP8, which nothing uses. That direction is harmless; the other
    one is a runtime method the binding starts using that nobody adds, which fails in
    the browser as an undefined function.
    """
    import re
    web = (ROOT / 'src/wgr/macros/WebHost.hx').read_text()

    def listed(name):
        m = re.search(name + r'\s*=\s*\[(.*?)\];', web, re.S)
        return set(re.findall(r'"(\w+)"', m.group(1))) if m else set()

    failed = False
    abi = set(re.findall(r'\b(wgr_guest_\w+)\s*\(', (ROOT / 'host/wgr_guest.h').read_text()))
    have = listed('GUEST_ABI')
    for n in sorted(abi - have):
        print(f'  GUEST_ABI is missing {n}, which host/wgr_guest.h declares')
        failed = True
    for n in sorted(have - abi):
        print(f'  GUEST_ABI lists {n}, which host/wgr_guest.h does not declare')
        failed = True

    reached = set()
    for f in (ROOT / 'src/wgr').rglob('*.js.hx'):
        reached |= {n for n in re.findall(r'\bhost\.([A-Za-z_]\w*)', f.read_text())
                    if not n.startswith('_wgr_')}
    runtime = listed('RUNTIME_METHODS')
    for n in sorted(reached - runtime):
        print(f'  RUNTIME_METHODS is missing {n}, which src/wgr reaches on the host module')
        failed = True
    for n in sorted(runtime - reached):
        print(f'  RUNTIME_METHODS lists {n}, which nothing in src/wgr reaches')
        failed = True

    if failed:
        return 1
    print(f'  GUEST_ABI matches host/wgr_guest.h ({len(abi)}); '
          f'RUNTIME_METHODS matches src/wgr ({len(runtime)})')
    return 0


if __name__ == '__main__':
    sys.exit(check_webhost_lists() if '--lists' in sys.argv else main())
