package wgr.impl;

// GENERATED by tools/gen_raw.py from wgrender's include/*.h — do not edit.
// Re-run the tool when wgrender's API moves; it writes this file whole.
//
// wgrender 0.0.1 at 051f6e9, 34 headers.
// wgrender-headers: 1cebe412bf09528f

/** What `wgr.Version` compares the running library against. **/
class BuiltVersion {
	public static inline final MAJOR = 0;
	public static inline final MINOR = 0;
	public static inline final PATCH = 1;
	public static inline final STRING = "0.0.1";

	/** The wgrender commit these were generated from, when there was one. **/
	public static inline final COMMIT = "051f6e9";

	/** A digest of the headers; `tools/gen_raw.py --check` compares it. **/
	public static inline final HEADERS = "1cebe412bf09528f";
}
