package wgr.impl;

// GENERATED by tools/gen_raw.py from wgrender's include/*.h — do not edit.
// Re-run the tool when wgrender's API moves; it writes this file whole.
//
// wgrender 0.0.1 at d61ae61, 34 headers.
// wgrender-headers: 165a6e0ccb0c51cc

import wgr.Handle;
import wgr.MouseState;
import wgr.PickResult;
import wgr.Vec2;
import wgr.Vec3;

typedef WgrHandle = Int;
typedef WgrColor = Int;

/**
	The same C surface Raw.cpp.hx declares, reached through the host module's exports.

	Three rules this layer keeps, all of them measured hazards:

	- **Never hold a heap view.** The host links with `ALLOW_MEMORY_GROWTH`, so any
	  allocation detaches every `HEAPF32`/`HEAP32` JS holds. Every read goes through
	  `host.HEAPF32` at the point of use. Pointers survive growth; views do not.
	- **Scratch is an arena per op.** Strings and struct-return slots come from
	  `stackAlloc`, and the guest's op edge restores the stack pointer once when the op
	  ends, fault or not (`wgr.impl.GuestAbi`).
	- **Structs come back through a pointer.** The wasm C ABI returns anything larger
	  than a scalar through a hidden first argument, so these read the fields out of
	  the heap rather than getting a value.
**/
class Raw {
	/** The Emscripten module, handed over at boot. **/
	/**
		The host module's exports. Until `GuestAbi.attach` sets it, this is a stand-in
		that explains itself: a `static final` initialiser runs when the guest module
		loads, which is before any host exists, so `static final BG = Color.rgba(...)`
		fails there. Without this the browser says
		"Cannot read properties of undefined (reading '_wgr_color_rgba')", which names
		the call and not the cause. Build such values in the init op instead.
	**/
	public static var host(default, null):Dynamic = notAttached();

	static function notAttached():Dynamic {
		return new js.lib.Proxy<Dynamic>(cast {}, {
			get: (_, name, _) -> throw 'wgrender: $name was called before GuestAbi.attach(host). '
				+ 'A static initialiser runs when this module loads, before the host exists — '
				+ 'build wgrender values in the init op instead.'
		});
	}

	public static function attach(module:Dynamic):Void {
		host = module;
	}

	/** Where the op arena started; `GuestAbi` restores to here when an op ends. **/
	public static inline function stackMark():Int
		return host.stackSave();

	public static inline function stackRelease(mark:Int):Void
		host.stackRestore(mark);

	/** A NUL-terminated copy of `s` in the op's arena. **/
	/**
		A Haxe string as a C string in the wasm heap, and `null` as a null pointer.

		The distinction matters: wgr_asset_ensure_async treats a null fetch_url as "use
		the host, with redirects and variants" and a non-null one as "the caller chose
		this exact file". An empty string is not the same thing, so null has to survive
		the crossing — as it already does on hxcpp, through Native.cstr.
	**/
	public static inline function cstr(s:String):Int {
		if (s == null)
			return 0;
		final length = host.lengthBytesUTF8(s) + 1;
		final pointer = host.stackAlloc(length);
		host.stringToUTF8(s, pointer, length);
		return pointer;
	}

	static inline function scratch(bytes:Int):Int
		return host.stackAlloc(bytes);

	public static inline function str(pointer:Int):String
		return host.UTF8ToString(pointer);

	/** The guest ABI's asset op, keyed by `id` — the guest never sees a callback. **/
	public static inline function wgr_guest_asset_load(path:String, id:Int):Bool
		return host._wgr_guest_asset_load(cstr(path), id) != 0;

	public static inline function wgr_init_values(window_width:Int, window_height:Int, window_title:String, window_flags:Int):Int
		return Raw.host._wgr_init_values(window_width, window_height, cstr(window_title), window_flags);

	public static inline function wgr_run():Int
		return Raw.host._wgr_run();

	public static inline function wgr_request_quit():Void
		Raw.host._wgr_request_quit();

	public static inline function wgr_is_initialized():Bool
		return Raw.host._wgr_is_initialized() != 0;

	public static inline function wgr_get_platform():String
		return str(Raw.host._wgr_get_platform());

	public static inline function wgr_get_renderer():String
		return str(Raw.host._wgr_get_renderer());

	public static inline function wgr_has_threads():Bool
		return Raw.host._wgr_has_threads() != 0;

	public static inline function wgr_set_target_fps(fps:Int):Void
		Raw.host._wgr_set_target_fps(fps);

	public static inline function wgr_get_time():Float
		return Raw.host._wgr_get_time();

	public static inline function wgr_asset_set_host(host:String):Void
		Raw.host._wgr_asset_set_host(cstr(host));

	public static inline function wgr_asset_get_host():String
		return str(Raw.host._wgr_asset_get_host());

	public static inline function wgr_asset_set_cache_dir(dir:String):Bool
		return Raw.host._wgr_asset_set_cache_dir(cstr(dir)) != 0;

	public static inline function wgr_asset_fetch_done(request:Int, ok:Bool):Bool
		return Raw.host._wgr_asset_fetch_done(request, ok) != 0;

	public static inline function wgr_asset_evict(path:String):Bool
		return Raw.host._wgr_asset_evict(cstr(path)) != 0;

	public static inline function wgr_asset_clear_cache():Void
		Raw.host._wgr_asset_clear_cache();

	public static inline function wgr_asset_ensure_async(path:String, fetch_url:String, flags:Int):Int
		return Raw.host._wgr_asset_ensure_async(cstr(path), cstr(fetch_url), flags);

	public static inline function wgr_asset_group_create():Int
		return Raw.host._wgr_asset_group_create();

	public static inline function wgr_asset_group_add(group:Int, task:Int):Bool
		return Raw.host._wgr_asset_group_add(group, task) != 0;

	public static inline function wgr_asset_get_progress(task:Int):Float
		return Raw.host._wgr_asset_get_progress(task);

	public static inline function wgr_asset_add_redirect(prefix:String, target:String):Bool
		return Raw.host._wgr_asset_add_redirect(cstr(prefix), cstr(target)) != 0;

	public static inline function wgr_asset_clear_redirects():Void
		Raw.host._wgr_asset_clear_redirects();

	public static inline function wgr_asset_set_upload_budget(milliseconds:Float):Void
		Raw.host._wgr_asset_set_upload_budget(milliseconds);

	public static inline function wgr_audio_create(path:String):Int
		return Raw.host._wgr_audio_create(cstr(path));

	public static inline function wgr_audio_release(handle:Int):Void
		Raw.host._wgr_audio_release(handle);

	public static inline function wgr_camera3d_create(projection:Int):Int
		return Raw.host._wgr_camera3d_create(projection);

	public static inline function wgr_camera3d_get_default():Int
		return Raw.host._wgr_camera3d_get_default();

	public static inline function wgr_camera3d_destroy(camera:Int):Void
		Raw.host._wgr_camera3d_destroy(camera);

	public static inline function wgr_camera3d_set_view(camera:Int, position_x:Float, position_y:Float, position_z:Float, target_x:Float, target_y:Float, target_z:Float, up_x:Float, up_y:Float, up_z:Float):Bool
		return Raw.host._wgr_camera3d_set_view(camera, position_x, position_y, position_z, target_x, target_y, target_z, up_x, up_y, up_z) != 0;

	public static inline function wgr_camera3d_set_projection(camera:Int, projection:Int):Bool
		return Raw.host._wgr_camera3d_set_projection(camera, projection) != 0;

	public static inline function wgr_camera3d_get_projection(camera:Int):Int
		return Raw.host._wgr_camera3d_get_projection(camera);

	public static inline function wgr_camera3d_set_fov(camera:Int, fov:Float):Bool
		return Raw.host._wgr_camera3d_set_fov(camera, fov) != 0;

	public static inline function wgr_camera3d_get_fov(camera:Int):Float
		return Raw.host._wgr_camera3d_get_fov(camera);

	public static inline function wgr_camera3d_set_ortho_height(camera:Int, height:Float):Bool
		return Raw.host._wgr_camera3d_set_ortho_height(camera, height) != 0;

	public static inline function wgr_camera3d_get_ortho_height(camera:Int):Float
		return Raw.host._wgr_camera3d_get_ortho_height(camera);

	public static inline function wgr_camera3d_set_active(camera:Int):Bool
		return Raw.host._wgr_camera3d_set_active(camera) != 0;

	public static inline function wgr_camera3d_get_active():Int
		return Raw.host._wgr_camera3d_get_active();

	public static inline function wgr_color_rgba(r:Int, g:Int, b:Int, a:Int):Int
		return Raw.host._wgr_color_rgba(r, g, b, a);

	public static inline function wgr_color_rgbaf(r:Float, g:Float, b:Float, a:Float):Int
		return Raw.host._wgr_color_rgbaf(r, g, b, a);

	public static inline function wgr_color_with_alpha(color:Int, a:Int):Int
		return Raw.host._wgr_color_with_alpha(color, a);

	public static inline function wgr_color_get_red(color:Int):Int
		return Raw.host._wgr_color_get_red(color);

	public static inline function wgr_color_get_green(color:Int):Int
		return Raw.host._wgr_color_get_green(color);

	public static inline function wgr_color_get_blue(color:Int):Int
		return Raw.host._wgr_color_get_blue(color);

	public static inline function wgr_color_get_alpha(color:Int):Int
		return Raw.host._wgr_color_get_alpha(color);

	public static inline function wgr_color_lerp(from:Int, to:Int, t:Float):Int
		return Raw.host._wgr_color_lerp(from, to, t);

	public static inline function wgr_debug_enable_fps(x:Int, y:Int, font_size:Int):Void
		Raw.host._wgr_debug_enable_fps(x, y, font_size);

	public static inline function wgr_debug_disable_fps():Void
		Raw.host._wgr_debug_disable_fps();

	public static inline function wgr_emitter2d_create(texture:Int):Int
		return Raw.host._wgr_emitter2d_create(texture);

	public static inline function wgr_emitter2d_destroy(emitter:Int):Void
		Raw.host._wgr_emitter2d_destroy(emitter);

	public static inline function wgr_emitter2d_set_source(emitter:Int, x:Float, y:Float, width:Float, height:Float):Bool
		return Raw.host._wgr_emitter2d_set_source(emitter, x, y, width, height) != 0;

	public static inline function wgr_emitter2d_set_frames(emitter:Int, columns:Int, rows:Int, count:Int, per_second:Float):Bool
		return Raw.host._wgr_emitter2d_set_frames(emitter, columns, rows, count, per_second) != 0;

	public static inline function wgr_emitter2d_set_position(emitter:Int, x:Float, y:Float):Bool
		return Raw.host._wgr_emitter2d_set_position(emitter, x, y) != 0;

	public static inline function wgr_emitter2d_jump(emitter:Int, x:Float, y:Float):Bool
		return Raw.host._wgr_emitter2d_jump(emitter, x, y) != 0;

	public static function wgr_emitter2d_get_position(emitter:Int):Vec2 {
		final out = scratch(8);
		Raw.host._wgr_emitter2d_get_position(out, emitter);
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new Vec2(f32[base + 0], f32[base + 1]);
	}

	public static inline function wgr_emitter2d_set_rate(emitter:Int, per_second:Float):Bool
		return Raw.host._wgr_emitter2d_set_rate(emitter, per_second) != 0;

	public static inline function wgr_emitter2d_burst(emitter:Int, count:Int):Bool
		return Raw.host._wgr_emitter2d_burst(emitter, count) != 0;

	public static inline function wgr_emitter2d_set_emitting(emitter:Int, emitting:Bool):Bool
		return Raw.host._wgr_emitter2d_set_emitting(emitter, emitting) != 0;

	public static inline function wgr_emitter2d_is_emitting(emitter:Int):Bool
		return Raw.host._wgr_emitter2d_is_emitting(emitter) != 0;

	public static inline function wgr_emitter2d_set_max(emitter:Int, count:Int):Bool
		return Raw.host._wgr_emitter2d_set_max(emitter, count) != 0;

	public static inline function wgr_emitter2d_set_life(emitter:Int, min_seconds:Float, max_seconds:Float):Bool
		return Raw.host._wgr_emitter2d_set_life(emitter, min_seconds, max_seconds) != 0;

	public static inline function wgr_emitter2d_prewarm(emitter:Int, seconds:Float):Bool
		return Raw.host._wgr_emitter2d_prewarm(emitter, seconds) != 0;

	public static inline function wgr_emitter2d_set_spawn_box(emitter:Int, half_width:Float, half_height:Float):Bool
		return Raw.host._wgr_emitter2d_set_spawn_box(emitter, half_width, half_height) != 0;

	public static inline function wgr_emitter2d_set_spawn_circle(emitter:Int, radius:Float):Bool
		return Raw.host._wgr_emitter2d_set_spawn_circle(emitter, radius) != 0;

	public static inline function wgr_emitter2d_set_velocity(emitter:Int, x:Float, y:Float, spread:Float, speed_variance:Float):Bool
		return Raw.host._wgr_emitter2d_set_velocity(emitter, x, y, spread, speed_variance) != 0;

	public static inline function wgr_emitter2d_set_gravity(emitter:Int, x:Float, y:Float):Bool
		return Raw.host._wgr_emitter2d_set_gravity(emitter, x, y) != 0;

	public static inline function wgr_emitter2d_set_drag(emitter:Int, per_second:Float):Bool
		return Raw.host._wgr_emitter2d_set_drag(emitter, per_second) != 0;

	public static inline function wgr_emitter2d_set_inherit_velocity(emitter:Int, fraction:Float):Bool
		return Raw.host._wgr_emitter2d_set_inherit_velocity(emitter, fraction) != 0;

	public static inline function wgr_emitter2d_set_size(emitter:Int, start:Float, end:Float, variance:Float):Bool
		return Raw.host._wgr_emitter2d_set_size(emitter, start, end, variance) != 0;

	public static inline function wgr_emitter2d_set_color(emitter:Int, start:Int, end:Int):Bool
		return Raw.host._wgr_emitter2d_set_color(emitter, start, end) != 0;

	public static inline function wgr_emitter2d_add_size_key(emitter:Int, t:Float, size:Float):Bool
		return Raw.host._wgr_emitter2d_add_size_key(emitter, t, size) != 0;

	public static inline function wgr_emitter2d_clear_size_keys(emitter:Int):Bool
		return Raw.host._wgr_emitter2d_clear_size_keys(emitter) != 0;

	public static inline function wgr_emitter2d_add_color_key(emitter:Int, t:Float, color:Int):Bool
		return Raw.host._wgr_emitter2d_add_color_key(emitter, t, color) != 0;

	public static inline function wgr_emitter2d_clear_color_keys(emitter:Int):Bool
		return Raw.host._wgr_emitter2d_clear_color_keys(emitter) != 0;

	public static inline function wgr_emitter2d_add_palette_color(emitter:Int, color:Int):Bool
		return Raw.host._wgr_emitter2d_add_palette_color(emitter, color) != 0;

	public static inline function wgr_emitter2d_clear_palette(emitter:Int):Bool
		return Raw.host._wgr_emitter2d_clear_palette(emitter) != 0;

	public static inline function wgr_emitter2d_set_spin(emitter:Int, min:Float, max:Float):Bool
		return Raw.host._wgr_emitter2d_set_spin(emitter, min, max) != 0;

	public static inline function wgr_emitter2d_set_stretch(emitter:Int, seconds:Float):Bool
		return Raw.host._wgr_emitter2d_set_stretch(emitter, seconds) != 0;

	public static inline function wgr_emitter2d_set_alpha_mode(emitter:Int, mode:Int, cutoff:Float):Bool
		return Raw.host._wgr_emitter2d_set_alpha_mode(emitter, mode, cutoff) != 0;

	public static inline function wgr_emitter2d_set_seed(emitter:Int, seed:Int):Bool
		return Raw.host._wgr_emitter2d_set_seed(emitter, seed) != 0;

	public static inline function wgr_emitter2d_get_count(emitter:Int):Int
		return Raw.host._wgr_emitter2d_get_count(emitter);

	public static inline function wgr_emitter2d_clear(emitter:Int):Void
		Raw.host._wgr_emitter2d_clear(emitter);

	public static inline function wgr_emitter2d_set_visible(emitter:Int, visible:Bool):Bool
		return Raw.host._wgr_emitter2d_set_visible(emitter, visible) != 0;

	public static inline function wgr_emitter2d_draw(emitter:Int):Void
		Raw.host._wgr_emitter2d_draw(emitter);

	public static inline function wgr_emitter3d_create(texture:Int):Int
		return Raw.host._wgr_emitter3d_create(texture);

	public static inline function wgr_emitter3d_destroy(emitter:Int):Void
		Raw.host._wgr_emitter3d_destroy(emitter);

	public static inline function wgr_emitter3d_set_source(emitter:Int, x:Float, y:Float, width:Float, height:Float):Bool
		return Raw.host._wgr_emitter3d_set_source(emitter, x, y, width, height) != 0;

	public static inline function wgr_emitter3d_set_frames(emitter:Int, columns:Int, rows:Int, count:Int, per_second:Float):Bool
		return Raw.host._wgr_emitter3d_set_frames(emitter, columns, rows, count, per_second) != 0;

	public static inline function wgr_emitter3d_set_position(emitter:Int, x:Float, y:Float, z:Float):Bool
		return Raw.host._wgr_emitter3d_set_position(emitter, x, y, z) != 0;

	public static inline function wgr_emitter3d_jump(emitter:Int, x:Float, y:Float, z:Float):Bool
		return Raw.host._wgr_emitter3d_jump(emitter, x, y, z) != 0;

	public static function wgr_emitter3d_get_position(emitter:Int):Vec3 {
		final out = scratch(12);
		Raw.host._wgr_emitter3d_get_position(out, emitter);
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new Vec3(f32[base + 0], f32[base + 1], f32[base + 2]);
	}

	public static inline function wgr_emitter3d_set_rate(emitter:Int, per_second:Float):Bool
		return Raw.host._wgr_emitter3d_set_rate(emitter, per_second) != 0;

	public static inline function wgr_emitter3d_burst(emitter:Int, count:Int):Bool
		return Raw.host._wgr_emitter3d_burst(emitter, count) != 0;

	public static inline function wgr_emitter3d_set_emitting(emitter:Int, emitting:Bool):Bool
		return Raw.host._wgr_emitter3d_set_emitting(emitter, emitting) != 0;

	public static inline function wgr_emitter3d_is_emitting(emitter:Int):Bool
		return Raw.host._wgr_emitter3d_is_emitting(emitter) != 0;

	public static inline function wgr_emitter3d_set_max(emitter:Int, count:Int):Bool
		return Raw.host._wgr_emitter3d_set_max(emitter, count) != 0;

	public static inline function wgr_emitter3d_set_life(emitter:Int, min_seconds:Float, max_seconds:Float):Bool
		return Raw.host._wgr_emitter3d_set_life(emitter, min_seconds, max_seconds) != 0;

	public static inline function wgr_emitter3d_prewarm(emitter:Int, seconds:Float):Bool
		return Raw.host._wgr_emitter3d_prewarm(emitter, seconds) != 0;

	public static inline function wgr_emitter3d_set_spawn_box(emitter:Int, half_x:Float, half_y:Float, half_z:Float):Bool
		return Raw.host._wgr_emitter3d_set_spawn_box(emitter, half_x, half_y, half_z) != 0;

	public static inline function wgr_emitter3d_set_spawn_sphere(emitter:Int, radius:Float):Bool
		return Raw.host._wgr_emitter3d_set_spawn_sphere(emitter, radius) != 0;

	public static inline function wgr_emitter3d_set_velocity(emitter:Int, x:Float, y:Float, z:Float, spread:Float, speed_variance:Float):Bool
		return Raw.host._wgr_emitter3d_set_velocity(emitter, x, y, z, spread, speed_variance) != 0;

	public static inline function wgr_emitter3d_set_gravity(emitter:Int, x:Float, y:Float, z:Float):Bool
		return Raw.host._wgr_emitter3d_set_gravity(emitter, x, y, z) != 0;

	public static inline function wgr_emitter3d_set_drag(emitter:Int, per_second:Float):Bool
		return Raw.host._wgr_emitter3d_set_drag(emitter, per_second) != 0;

	public static inline function wgr_emitter3d_set_inherit_velocity(emitter:Int, fraction:Float):Bool
		return Raw.host._wgr_emitter3d_set_inherit_velocity(emitter, fraction) != 0;

	public static inline function wgr_emitter3d_set_size(emitter:Int, start:Float, end:Float, variance:Float):Bool
		return Raw.host._wgr_emitter3d_set_size(emitter, start, end, variance) != 0;

	public static inline function wgr_emitter3d_set_color(emitter:Int, start:Int, end:Int):Bool
		return Raw.host._wgr_emitter3d_set_color(emitter, start, end) != 0;

	public static inline function wgr_emitter3d_add_size_key(emitter:Int, t:Float, size:Float):Bool
		return Raw.host._wgr_emitter3d_add_size_key(emitter, t, size) != 0;

	public static inline function wgr_emitter3d_clear_size_keys(emitter:Int):Bool
		return Raw.host._wgr_emitter3d_clear_size_keys(emitter) != 0;

	public static inline function wgr_emitter3d_add_color_key(emitter:Int, t:Float, color:Int):Bool
		return Raw.host._wgr_emitter3d_add_color_key(emitter, t, color) != 0;

	public static inline function wgr_emitter3d_clear_color_keys(emitter:Int):Bool
		return Raw.host._wgr_emitter3d_clear_color_keys(emitter) != 0;

	public static inline function wgr_emitter3d_add_palette_color(emitter:Int, color:Int):Bool
		return Raw.host._wgr_emitter3d_add_palette_color(emitter, color) != 0;

	public static inline function wgr_emitter3d_clear_palette(emitter:Int):Bool
		return Raw.host._wgr_emitter3d_clear_palette(emitter) != 0;

	public static inline function wgr_emitter3d_set_spin(emitter:Int, min:Float, max:Float):Bool
		return Raw.host._wgr_emitter3d_set_spin(emitter, min, max) != 0;

	public static inline function wgr_emitter3d_set_stretch(emitter:Int, seconds:Float):Bool
		return Raw.host._wgr_emitter3d_set_stretch(emitter, seconds) != 0;

	public static inline function wgr_emitter3d_set_alpha_mode(emitter:Int, mode:Int, cutoff:Float):Bool
		return Raw.host._wgr_emitter3d_set_alpha_mode(emitter, mode, cutoff) != 0;

	public static inline function wgr_emitter3d_set_seed(emitter:Int, seed:Int):Bool
		return Raw.host._wgr_emitter3d_set_seed(emitter, seed) != 0;

	public static inline function wgr_emitter3d_get_count(emitter:Int):Int
		return Raw.host._wgr_emitter3d_get_count(emitter);

	public static inline function wgr_emitter3d_clear(emitter:Int):Void
		Raw.host._wgr_emitter3d_clear(emitter);

	public static inline function wgr_emitter3d_set_visible(emitter:Int, visible:Bool):Bool
		return Raw.host._wgr_emitter3d_set_visible(emitter, visible) != 0;

	public static inline function wgr_emitter3d_draw(emitter:Int):Void
		Raw.host._wgr_emitter3d_draw(emitter);

	public static inline function wgr_environment_create(path:String):Int
		return Raw.host._wgr_environment_create(cstr(path));

	public static inline function wgr_environment_release(environment:Int):Void
		Raw.host._wgr_environment_release(environment);

	public static inline function wgr_event_off_all(event_name:String):Int
		return Raw.host._wgr_event_off_all(cstr(event_name));

	public static inline function wgr_event_listener_count(event_name:String):Int
		return Raw.host._wgr_event_listener_count(cstr(event_name));

	public static inline function wgr_font_create(path:String):Int
		return Raw.host._wgr_font_create(cstr(path));

	public static inline function wgr_font_release(handle:Int):Void
		Raw.host._wgr_font_release(handle);

	public static inline function wgr_handle_get_kind(handle:Int):Int
		return Raw.host._wgr_handle_get_kind(handle);

	public static inline function wgr_input_capture_cursor():Void
		Raw.host._wgr_input_capture_cursor();

	public static inline function wgr_input_release_cursor():Void
		Raw.host._wgr_input_release_cursor();

	public static function wgr_input_get_mouse_position():Vec2 {
		final out = scratch(8);
		Raw.host._wgr_input_get_mouse_position(out);
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new Vec2(f32[base + 0], f32[base + 1]);
	}

	public static function wgr_input_get_mouse_delta():Vec2 {
		final out = scratch(8);
		Raw.host._wgr_input_get_mouse_delta(out);
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new Vec2(f32[base + 0], f32[base + 1]);
	}

	public static inline function wgr_input_get_mouse_wheel():Float
		return Raw.host._wgr_input_get_mouse_wheel();

	public static inline function wgr_input_get_mouse_wheel_x():Float
		return Raw.host._wgr_input_get_mouse_wheel_x();

	public static inline function wgr_input_get_mouse_button(button:Int):Int
		return Raw.host._wgr_input_get_mouse_button(button);

	public static function wgr_input_get_mouse_state():MouseState {
		final out = scratch(48);
		Raw.host._wgr_input_get_mouse_state(out);
		final i32 = Raw.host.HEAP32;
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new MouseState(i32[base + 0], i32[base + 1], f32[base + 2], f32[base + 3], i32[base + 4], i32[base + 5], i32[base + 6], [i32[base + 7], i32[base + 8], i32[base + 9]], i32[base + 10], i32[base + 11]);
	}

	public static inline function wgr_input_get_key(key:Int):Int
		return Raw.host._wgr_input_get_key(key);

	/**
		A pointer to a `wgr_keyboard_state_t` in the wasm heap — 2324 bytes is too much to
		copy per frame, so the public layer reads the fields it wants through
		`KeyboardStateLayout`. Valid until the current guest op returns, which is
		when the op edge resets the stack this was taken from.
	**/
	public static function wgr_input_get_keyboard_state():Int {
		final out = scratch(2324);
		Raw.host._wgr_input_get_keyboard_state(out);
		return out;
	}

	public static inline function wgr_input_get_touch_count():Int
		return Raw.host._wgr_input_get_touch_count();

	public static function wgr_input_get_touch(index:Int):Touch {
		final out = scratch(24);
		Raw.host._wgr_input_get_touch(out, index);
		final i32 = Raw.host.HEAP32;
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new Touch(i32[base + 0], f32[base + 1], f32[base + 2], f32[base + 3], f32[base + 4], i32[base + 5]);
	}

	public static function wgr_input_get_touch_gesture():TouchGesture {
		final out = scratch(28);
		Raw.host._wgr_input_get_touch_gesture(out);
		final f32 = Raw.host.HEAPF32;
		final u8 = Raw.host.HEAPU8;
		final base = out >> 2;
		return new TouchGesture(u8[out + 0] != 0, f32[base + 1], f32[base + 2], f32[base + 3], f32[base + 4], f32[base + 5], f32[base + 6]);
	}

	public static inline function wgr_input_is_gamepad_connected(pad:Int):Bool
		return Raw.host._wgr_input_is_gamepad_connected(pad) != 0;

	public static inline function wgr_input_get_gamepad_name(pad:Int):String
		return str(Raw.host._wgr_input_get_gamepad_name(pad));

	public static inline function wgr_input_get_gamepad_button(pad:Int, button:Int):Int
		return Raw.host._wgr_input_get_gamepad_button(pad, button);

	public static inline function wgr_input_get_gamepad_axis(pad:Int, axis:Int):Float
		return Raw.host._wgr_input_get_gamepad_axis(pad, axis);

	public static inline function wgr_input_set_gamepad_deadzone(radius:Float):Bool
		return Raw.host._wgr_input_set_gamepad_deadzone(radius) != 0;

	public static inline function wgr_input_is_pointer_captured():Bool
		return Raw.host._wgr_input_is_pointer_captured() != 0;

	public static inline function wgr_input_set_pointer_captured(captured:Bool):Void
		Raw.host._wgr_input_set_pointer_captured(captured);

	public static inline function wgr_input_is_keyboard_captured():Bool
		return Raw.host._wgr_input_is_keyboard_captured() != 0;

	public static inline function wgr_input_set_keyboard_captured(captured:Bool):Void
		Raw.host._wgr_input_set_keyboard_captured(captured);

	public static inline function wgr_light_create(type:Int):Int
		return Raw.host._wgr_light_create(type);

	public static inline function wgr_light_destroy(light:Int):Void
		Raw.host._wgr_light_destroy(light);

	public static inline function wgr_light_set_color(light:Int, color:Int):Bool
		return Raw.host._wgr_light_set_color(light, color) != 0;

	public static inline function wgr_light_set_intensity(light:Int, intensity:Float):Bool
		return Raw.host._wgr_light_set_intensity(light, intensity) != 0;

	public static inline function wgr_light_set_position(light:Int, x:Float, y:Float, z:Float):Bool
		return Raw.host._wgr_light_set_position(light, x, y, z) != 0;

	public static inline function wgr_light_set_direction(light:Int, x:Float, y:Float, z:Float):Bool
		return Raw.host._wgr_light_set_direction(light, x, y, z) != 0;

	public static inline function wgr_light_set_range(light:Int, range:Float):Bool
		return Raw.host._wgr_light_set_range(light, range) != 0;

	public static inline function wgr_light_set_spot_cone(light:Int, inner_angle:Float, outer_angle:Float):Bool
		return Raw.host._wgr_light_set_spot_cone(light, inner_angle, outer_angle) != 0;

	public static inline function wgr_light_set_enabled(light:Int, enabled:Bool):Bool
		return Raw.host._wgr_light_set_enabled(light, enabled) != 0;

	public static inline function wgr_light_is_enabled(light:Int):Bool
		return Raw.host._wgr_light_is_enabled(light) != 0;

	public static inline function wgr_light_get_type(light:Int):Int
		return Raw.host._wgr_light_get_type(light);

	public static inline function wgr_light_get_color(light:Int):Int
		return Raw.host._wgr_light_get_color(light);

	public static inline function wgr_light_get_intensity(light:Int):Float
		return Raw.host._wgr_light_get_intensity(light);

	public static function wgr_light_get_position(light:Int):Vec3 {
		final out = scratch(12);
		Raw.host._wgr_light_get_position(out, light);
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new Vec3(f32[base + 0], f32[base + 1], f32[base + 2]);
	}

	public static function wgr_light_get_direction(light:Int):Vec3 {
		final out = scratch(12);
		Raw.host._wgr_light_get_direction(out, light);
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new Vec3(f32[base + 0], f32[base + 1], f32[base + 2]);
	}

	public static inline function wgr_light_get_range(light:Int):Float
		return Raw.host._wgr_light_get_range(light);

	public static inline function wgr_light_get_spot_inner_angle(light:Int):Float
		return Raw.host._wgr_light_get_spot_inner_angle(light);

	public static inline function wgr_light_get_spot_outer_angle(light:Int):Float
		return Raw.host._wgr_light_get_spot_outer_angle(light);

	public static inline function wgr_light_set_casts_shadows(light:Int, casts:Bool):Bool
		return Raw.host._wgr_light_set_casts_shadows(light, casts) != 0;

	public static inline function wgr_light_get_casts_shadows(light:Int):Bool
		return Raw.host._wgr_light_get_casts_shadows(light) != 0;

	public static inline function wgr_light_set_shadow_distance(light:Int, distance:Float):Bool
		return Raw.host._wgr_light_set_shadow_distance(light, distance) != 0;

	public static inline function wgr_light_set_shadow_map_size(light:Int, size:Int):Bool
		return Raw.host._wgr_light_set_shadow_map_size(light, size) != 0;

	public static inline function wgr_light_set_shadow_strength(light:Int, strength:Float):Bool
		return Raw.host._wgr_light_set_shadow_strength(light, strength) != 0;

	public static inline function wgr_light_set_shadow_color(light:Int, color:Int):Bool
		return Raw.host._wgr_light_set_shadow_color(light, color) != 0;

	public static inline function wgr_light_set_shadow_bias(light:Int, constant:Float, slope:Float):Bool
		return Raw.host._wgr_light_set_shadow_bias(light, constant, slope) != 0;

	public static inline function wgr_light_get_shadow_distance(light:Int):Float
		return Raw.host._wgr_light_get_shadow_distance(light);

	public static inline function wgr_light_get_shadow_map_size(light:Int):Int
		return Raw.host._wgr_light_get_shadow_map_size(light);

	public static inline function wgr_light_get_shadow_strength(light:Int):Float
		return Raw.host._wgr_light_get_shadow_strength(light);

	public static inline function wgr_light_get_shadow_color(light:Int):Int
		return Raw.host._wgr_light_get_shadow_color(light);

	public static inline function wgr_light_get_shadow_bias_constant(light:Int):Float
		return Raw.host._wgr_light_get_shadow_bias_constant(light);

	public static inline function wgr_light_get_shadow_bias_slope(light:Int):Float
		return Raw.host._wgr_light_get_shadow_bias_slope(light);

	public static inline function wgr_logger_set_level(level:Int):Void
		Raw.host._wgr_logger_set_level(level);

	public static inline function wgr_material_create(shading:Int):Int
		return Raw.host._wgr_material_create(shading);

	public static inline function wgr_material_create_custom(shader:Int):Int
		return Raw.host._wgr_material_create_custom(shader);

	public static inline function wgr_material_get_shader(material:Int):Int
		return Raw.host._wgr_material_get_shader(material);

	public static inline function wgr_material_release(material:Int):Void
		Raw.host._wgr_material_release(material);

	public static inline function wgr_material_set_shading(material:Int, shading:Int):Bool
		return Raw.host._wgr_material_set_shading(material, shading) != 0;

	public static inline function wgr_material_get_shading(material:Int):Int
		return Raw.host._wgr_material_get_shading(material);

	public static inline function wgr_material_set_alpha_mode(material:Int, mode:Int, cutoff:Float):Bool
		return Raw.host._wgr_material_set_alpha_mode(material, mode, cutoff) != 0;

	public static inline function wgr_material_get_alpha_mode(material:Int):Int
		return Raw.host._wgr_material_get_alpha_mode(material);

	public static inline function wgr_material_set_double_sided(material:Int, double_sided:Bool):Bool
		return Raw.host._wgr_material_set_double_sided(material, double_sided) != 0;

	public static inline function wgr_material_is_double_sided(material:Int):Bool
		return Raw.host._wgr_material_is_double_sided(material) != 0;

	public static inline function wgr_material_set_int(material:Int, name:String, value:Int):Bool
		return Raw.host._wgr_material_set_int(material, cstr(name), value) != 0;

	public static inline function wgr_material_set_float(material:Int, name:String, value:Float):Bool
		return Raw.host._wgr_material_set_float(material, cstr(name), value) != 0;

	public static inline function wgr_material_set_vec2(material:Int, name:String, x:Float, y:Float):Bool
		return Raw.host._wgr_material_set_vec2(material, cstr(name), x, y) != 0;

	public static inline function wgr_material_set_vec3(material:Int, name:String, x:Float, y:Float, z:Float):Bool
		return Raw.host._wgr_material_set_vec3(material, cstr(name), x, y, z) != 0;

	public static inline function wgr_material_set_vec4(material:Int, name:String, x:Float, y:Float, z:Float, w:Float):Bool
		return Raw.host._wgr_material_set_vec4(material, cstr(name), x, y, z, w) != 0;

	public static inline function wgr_material_set_color(material:Int, name:String, color:Int):Bool
		return Raw.host._wgr_material_set_color(material, cstr(name), color) != 0;

	public static inline function wgr_material_set_texture(material:Int, name:String, texture:Int):Bool
		return Raw.host._wgr_material_set_texture(material, cstr(name), texture) != 0;

	public static inline function wgr_material_set_texture_sampling(material:Int, name:String, wrap_u:Int, wrap_v:Int, filter:Int):Bool
		return Raw.host._wgr_material_set_texture_sampling(material, cstr(name), wrap_u, wrap_v, filter) != 0;

	public static inline function wgr_mesh_create(path:String):Int
		return Raw.host._wgr_mesh_create(cstr(path));

	public static inline function wgr_mesh_release(mesh:Int):Void
		Raw.host._wgr_mesh_release(mesh);

	public static inline function wgr_mesh_create_plane(width:Float, length:Float, subdivisions:Int):Int
		return Raw.host._wgr_mesh_create_plane(width, length, subdivisions);

	public static inline function wgr_mesh_create_cube(width:Float, height:Float, length:Float):Int
		return Raw.host._wgr_mesh_create_cube(width, height, length);

	public static inline function wgr_mesh_create_sphere(radius:Float, rings:Int, segments:Int):Int
		return Raw.host._wgr_mesh_create_sphere(radius, rings, segments);

	public static inline function wgr_mesh_create_cylinder(radius:Float, height:Float, segments:Int):Int
		return Raw.host._wgr_mesh_create_cylinder(radius, height, segments);

	public static inline function wgr_mesh_create_cone(radius:Float, height:Float, segments:Int):Int
		return Raw.host._wgr_mesh_create_cone(radius, height, segments);

	public static inline function wgr_mesh_create_capsule(radius:Float, height:Float, rings:Int, segments:Int):Int
		return Raw.host._wgr_mesh_create_capsule(radius, height, rings, segments);

	public static inline function wgr_mesh_create_torus(radius:Float, thickness:Float, rings:Int, segments:Int):Int
		return Raw.host._wgr_mesh_create_torus(radius, thickness, rings, segments);

	public static inline function wgr_mesh_get_material_count(mesh:Int):Int
		return Raw.host._wgr_mesh_get_material_count(mesh);

	public static inline function wgr_mesh_get_material(mesh:Int, slot:Int):Int
		return Raw.host._wgr_mesh_get_material(mesh, slot);

	public static inline function wgr_model_create(mesh:Int):Int
		return Raw.host._wgr_model_create(mesh);

	public static inline function wgr_model_set_mesh(handle:Int, mesh:Int):Bool
		return Raw.host._wgr_model_set_mesh(handle, mesh) != 0;

	public static inline function wgr_model_set_transform(handle:Int, position_x:Float, position_y:Float, position_z:Float, rotation_x:Float, rotation_y:Float, rotation_z:Float, scale_x:Float, scale_y:Float, scale_z:Float):Bool
		return Raw.host._wgr_model_set_transform(handle, position_x, position_y, position_z, rotation_x, rotation_y, rotation_z, scale_x, scale_y, scale_z) != 0;

	public static inline function wgr_model_set_tint(handle:Int, color:Int):Bool
		return Raw.host._wgr_model_set_tint(handle, color) != 0;

	public static inline function wgr_model_set_material(handle:Int, slot:Int, material:Int):Bool
		return Raw.host._wgr_model_set_material(handle, slot, material) != 0;

	public static inline function wgr_model_get_material(handle:Int, slot:Int):Int
		return Raw.host._wgr_model_get_material(handle, slot);

	public static inline function wgr_model_set_visible(handle:Int, visible:Bool):Bool
		return Raw.host._wgr_model_set_visible(handle, visible) != 0;

	public static inline function wgr_model_is_visible(handle:Int):Bool
		return Raw.host._wgr_model_is_visible(handle) != 0;

	public static inline function wgr_model_set_pickable(handle:Int, pickable:Bool):Bool
		return Raw.host._wgr_model_set_pickable(handle, pickable) != 0;

	public static inline function wgr_model_is_pickable(handle:Int):Bool
		return Raw.host._wgr_model_is_pickable(handle) != 0;

	public static inline function wgr_model_set_enabled(model:Int, enabled:Bool):Bool
		return Raw.host._wgr_model_set_enabled(model, enabled) != 0;

	public static inline function wgr_model_is_enabled(model:Int):Bool
		return Raw.host._wgr_model_is_enabled(model) != 0;

	public static inline function wgr_model_set_casts_shadow(model:Int, casts:Bool):Bool
		return Raw.host._wgr_model_set_casts_shadow(model, casts) != 0;

	public static inline function wgr_model_casts_shadow(model:Int):Bool
		return Raw.host._wgr_model_casts_shadow(model) != 0;

	public static inline function wgr_model_set_receives_shadow(model:Int, receives:Bool):Bool
		return Raw.host._wgr_model_set_receives_shadow(model, receives) != 0;

	public static inline function wgr_model_receives_shadow(model:Int):Bool
		return Raw.host._wgr_model_receives_shadow(model) != 0;

	public static inline function wgr_model_draw(handle:Int):Void
		Raw.host._wgr_model_draw(handle);

	public static inline function wgr_model_destroy(handle:Int):Void
		Raw.host._wgr_model_destroy(handle);

	public static inline function wgr_model_get_animation_count(handle:Int):Int
		return Raw.host._wgr_model_get_animation_count(handle);

	public static inline function wgr_model_set_animation(handle:Int, animation_index:Int):Bool
		return Raw.host._wgr_model_set_animation(handle, animation_index) != 0;

	public static inline function wgr_model_set_animation_speed(handle:Int, speed:Float):Bool
		return Raw.host._wgr_model_set_animation_speed(handle, speed) != 0;

	public static inline function wgr_model_set_animation_loop(handle:Int, loop:Bool):Bool
		return Raw.host._wgr_model_set_animation_loop(handle, loop) != 0;

	public static inline function wgr_model_animate(handle:Int, delta_seconds:Float):Bool
		return Raw.host._wgr_model_animate(handle, delta_seconds) != 0;

	public static inline function wgr_model_set_animation_time(handle:Int, seconds:Float):Bool
		return Raw.host._wgr_model_set_animation_time(handle, seconds) != 0;

	public static inline function wgr_model_get_animation_time(handle:Int):Float
		return Raw.host._wgr_model_get_animation_time(handle);

	public static inline function wgr_model_get_animation_duration(handle:Int, animation_index:Int):Float
		return Raw.host._wgr_model_get_animation_duration(handle, animation_index);

	public static inline function wgr_model_is_ready(handle:Int):Bool
		return Raw.host._wgr_model_is_ready(handle) != 0;

	public static function wgr_pick_object(object:Int, camera:Int, x:Float, y:Float):PickResult {
		final out = scratch(60);
		Raw.host._wgr_pick_object(out, object, camera, x, y);
		final u32 = Raw.host.HEAPU32;
		final f32 = Raw.host.HEAPF32;
		final u8 = Raw.host.HEAPU8;
		final base = out >> 2;
		return new PickResult(u8[out + 0] != 0, u32[base + 1], f32[base + 2], new Vec3(f32[base + 3], f32[base + 4], f32[base + 5]), new Vec3(f32[base + 6], f32[base + 7], f32[base + 8]), new Vec3(f32[base + 9], f32[base + 10], f32[base + 11]), new Vec3(f32[base + 12], f32[base + 13], f32[base + 14]));
	}

	public static function wgr_pick_get_stats():PickStats {
		final out = scratch(16);
		Raw.host._wgr_pick_get_stats(out);
		final i32 = Raw.host.HEAP32;
		final base = out >> 2;
		return new PickStats(i32[base + 0], i32[base + 1], i32[base + 2], i32[base + 3]);
	}

	public static inline function wgr_pick_reset_stats():Void
		Raw.host._wgr_pick_reset_stats();

	public static inline function wgr_render_begin():Void
		Raw.host._wgr_render_begin();

	public static inline function wgr_render_end():Void
		Raw.host._wgr_render_end();

	public static inline function wgr_render_clear_background(color:Int):Void
		Raw.host._wgr_render_clear_background(color);

	public static inline function wgr_render_begin_mode_2d():Void
		Raw.host._wgr_render_begin_mode_2d();

	public static inline function wgr_render_end_mode_2d():Void
		Raw.host._wgr_render_end_mode_2d();

	public static inline function wgr_render_begin_mode_3d():Void
		Raw.host._wgr_render_begin_mode_3d();

	public static inline function wgr_render_end_mode_3d():Void
		Raw.host._wgr_render_end_mode_3d();

	public static inline function wgr_render_push_clip(x:Float, y:Float, width:Float, height:Float):Void
		Raw.host._wgr_render_push_clip(x, y, width, height);

	public static inline function wgr_render_pop_clip():Void
		Raw.host._wgr_render_pop_clip();

	public static inline function wgr_render_begin_texture(texture:Int):Bool
		return Raw.host._wgr_render_begin_texture(texture) != 0;

	public static inline function wgr_render_end_texture():Void
		Raw.host._wgr_render_end_texture();

	public static inline function wgr_render_add_effect(material:Int):Bool
		return Raw.host._wgr_render_add_effect(material) != 0;

	public static inline function wgr_render_clear_effects():Void
		Raw.host._wgr_render_clear_effects();

	public static inline function wgr_render_effect_count():Int
		return Raw.host._wgr_render_effect_count();

	public static inline function wgr_scene_create():Int
		return Raw.host._wgr_scene_create();

	public static inline function wgr_scene_destroy(scene:Int):Void
		Raw.host._wgr_scene_destroy(scene);

	public static inline function wgr_scene_add(scene:Int, drawable:Int, layer:Int):Bool
		return Raw.host._wgr_scene_add(scene, drawable, layer) != 0;

	public static inline function wgr_scene_set_layer(scene:Int, drawable:Int, layer:Int):Bool
		return Raw.host._wgr_scene_set_layer(scene, drawable, layer) != 0;

	public static inline function wgr_scene_remove(scene:Int, drawable:Int):Bool
		return Raw.host._wgr_scene_remove(scene, drawable) != 0;

	public static inline function wgr_scene_clear(scene:Int):Void
		Raw.host._wgr_scene_clear(scene);

	public static inline function wgr_scene_set_clip(scene:Int, layer:Int, x:Float, y:Float, width:Float, height:Float):Bool
		return Raw.host._wgr_scene_set_clip(scene, layer, x, y, width, height) != 0;

	public static inline function wgr_scene_set_active_camera(scene:Int, camera:Int):Void
		Raw.host._wgr_scene_set_active_camera(scene, camera);

	public static inline function wgr_scene_set_ambient(scene:Int, color:Int, intensity:Float):Bool
		return Raw.host._wgr_scene_set_ambient(scene, color, intensity) != 0;

	public static inline function wgr_scene_set_environment(scene:Int, environment:Int, intensity:Float, rotation:Float):Bool
		return Raw.host._wgr_scene_set_environment(scene, environment, intensity, rotation) != 0;

	public static inline function wgr_scene_set_background(scene:Int, environment:Int, blur:Float):Bool
		return Raw.host._wgr_scene_set_background(scene, environment, blur) != 0;

	public static inline function wgr_scene_set_tonemap(scene:Int, tonemap:Int, exposure:Float):Bool
		return Raw.host._wgr_scene_set_tonemap(scene, tonemap, exposure) != 0;

	public static inline function wgr_scene_draw(scene:Int):Void
		Raw.host._wgr_scene_draw(scene);

	public static inline function wgr_scene_set_interactive(scene:Int, interactive:Bool):Bool
		return Raw.host._wgr_scene_set_interactive(scene, interactive) != 0;

	public static inline function wgr_scene_set_culling(scene:Int, culling:Bool):Bool
		return Raw.host._wgr_scene_set_culling(scene, culling) != 0;

	public static inline function wgr_scene_is_culling(scene:Int):Bool
		return Raw.host._wgr_scene_is_culling(scene) != 0;

	public static inline function wgr_scene_is_interactive(scene:Int):Bool
		return Raw.host._wgr_scene_is_interactive(scene) != 0;

	public static inline function wgr_scene_get_hovered(scene:Int):Int
		return Raw.host._wgr_scene_get_hovered(scene);

	public static inline function wgr_scene_get_hover(scene:Int, object:Int):Int
		return Raw.host._wgr_scene_get_hover(scene, object);

	public static inline function wgr_scene_get_press(scene:Int, object:Int):Int
		return Raw.host._wgr_scene_get_press(scene, object);

	public static inline function wgr_scene_is_clicked(scene:Int, object:Int):Bool
		return Raw.host._wgr_scene_is_clicked(scene, object) != 0;

	public static function wgr_scene_pick(scene:Int, camera:Int, mouse_x:Float, mouse_y:Float):PickResult {
		final out = scratch(60);
		Raw.host._wgr_scene_pick(out, scene, camera, mouse_x, mouse_y);
		final u32 = Raw.host.HEAPU32;
		final f32 = Raw.host.HEAPF32;
		final u8 = Raw.host.HEAPU8;
		final base = out >> 2;
		return new PickResult(u8[out + 0] != 0, u32[base + 1], f32[base + 2], new Vec3(f32[base + 3], f32[base + 4], f32[base + 5]), new Vec3(f32[base + 6], f32[base + 7], f32[base + 8]), new Vec3(f32[base + 9], f32[base + 10], f32[base + 11]), new Vec3(f32[base + 12], f32[base + 13], f32[base + 14]));
	}

	public static inline function wgr_shader_create(path:String):Int
		return Raw.host._wgr_shader_create(cstr(path));

	public static inline function wgr_shader_release(shader:Int):Void
		Raw.host._wgr_shader_release(shader);

	public static inline function wgr_shape2d_draw_rectangle(x:Float, y:Float, width:Float, height:Float, color:Int):Void
		Raw.host._wgr_shape2d_draw_rectangle(x, y, width, height, color);

	public static inline function wgr_shape2d_draw_rectangle_lines(x:Float, y:Float, width:Float, height:Float, color:Int):Void
		Raw.host._wgr_shape2d_draw_rectangle_lines(x, y, width, height, color);

	public static inline function wgr_shape2d_draw_line(start_x:Float, start_y:Float, end_x:Float, end_y:Float, color:Int):Void
		Raw.host._wgr_shape2d_draw_line(start_x, start_y, end_x, end_y, color);

	public static inline function wgr_shape2d_draw_circle(center_x:Float, center_y:Float, radius:Float, color:Int):Void
		Raw.host._wgr_shape2d_draw_circle(center_x, center_y, radius, color);

	public static inline function wgr_shape2d_draw_circle_lines(center_x:Float, center_y:Float, radius:Float, color:Int):Void
		Raw.host._wgr_shape2d_draw_circle_lines(center_x, center_y, radius, color);

	public static inline function wgr_shape2d_draw_triangle(x0:Float, y0:Float, x1:Float, y1:Float, x2:Float, y2:Float, color:Int):Void
		Raw.host._wgr_shape2d_draw_triangle(x0, y0, x1, y1, x2, y2, color);

	public static inline function wgr_shape2d_draw_rounded_rectangle(x:Float, y:Float, width:Float, height:Float, r_top_left:Float, r_top_right:Float, r_bottom_right:Float, r_bottom_left:Float, color:Int):Void
		Raw.host._wgr_shape2d_draw_rounded_rectangle(x, y, width, height, r_top_left, r_top_right, r_bottom_right, r_bottom_left, color);

	public static inline function wgr_shape2d_draw_border(x:Float, y:Float, width:Float, height:Float, left:Float, top:Float, right:Float, bottom:Float, r_top_left:Float, r_top_right:Float, r_bottom_right:Float, r_bottom_left:Float, color:Int):Void
		Raw.host._wgr_shape2d_draw_border(x, y, width, height, left, top, right, bottom, r_top_left, r_top_right, r_bottom_right, r_bottom_left, color);

	public static inline function wgr_shape2d_create():Int
		return Raw.host._wgr_shape2d_create();

	public static inline function wgr_shape2d_destroy(shape:Int):Void
		Raw.host._wgr_shape2d_destroy(shape);

	public static inline function wgr_shape2d_set_rectangle(shape:Int, width:Float, height:Float, corner_radius:Float):Bool
		return Raw.host._wgr_shape2d_set_rectangle(shape, width, height, corner_radius) != 0;

	public static inline function wgr_shape2d_set_circle(shape:Int, radius:Float):Bool
		return Raw.host._wgr_shape2d_set_circle(shape, radius) != 0;

	public static inline function wgr_shape2d_set_line(shape:Int, x0:Float, y0:Float, x1:Float, y1:Float, thickness:Float):Bool
		return Raw.host._wgr_shape2d_set_line(shape, x0, y0, x1, y1, thickness) != 0;

	public static inline function wgr_shape2d_set_transform(shape:Int, x:Float, y:Float, rotation:Float, scale_x:Float, scale_y:Float):Bool
		return Raw.host._wgr_shape2d_set_transform(shape, x, y, rotation, scale_x, scale_y) != 0;

	public static inline function wgr_shape2d_set_pivot(shape:Int, x:Float, y:Float):Bool
		return Raw.host._wgr_shape2d_set_pivot(shape, x, y) != 0;

	public static inline function wgr_shape2d_set_outline(shape:Int, thickness:Float):Bool
		return Raw.host._wgr_shape2d_set_outline(shape, thickness) != 0;

	public static inline function wgr_shape2d_set_color(shape:Int, color:Int):Bool
		return Raw.host._wgr_shape2d_set_color(shape, color) != 0;

	public static inline function wgr_shape2d_set_visible(shape:Int, visible:Bool):Bool
		return Raw.host._wgr_shape2d_set_visible(shape, visible) != 0;

	public static inline function wgr_shape2d_is_visible(shape:Int):Bool
		return Raw.host._wgr_shape2d_is_visible(shape) != 0;

	public static inline function wgr_shape2d_set_pickable(shape:Int, pickable:Bool):Bool
		return Raw.host._wgr_shape2d_set_pickable(shape, pickable) != 0;

	public static inline function wgr_shape2d_is_pickable(shape:Int):Bool
		return Raw.host._wgr_shape2d_is_pickable(shape) != 0;

	public static inline function wgr_shape2d_set_enabled(shape:Int, enabled:Bool):Bool
		return Raw.host._wgr_shape2d_set_enabled(shape, enabled) != 0;

	public static inline function wgr_shape2d_is_enabled(shape:Int):Bool
		return Raw.host._wgr_shape2d_is_enabled(shape) != 0;

	public static inline function wgr_shape2d_draw(shape:Int):Void
		Raw.host._wgr_shape2d_draw(shape);

	public static inline function wgr_shape3d_draw_line(x0:Float, y0:Float, z0:Float, x1:Float, y1:Float, z1:Float, color:Int):Void
		Raw.host._wgr_shape3d_draw_line(x0, y0, z0, x1, y1, z1, color);

	public static inline function wgr_shape3d_draw_cube(cx:Float, cy:Float, cz:Float, width:Float, height:Float, length:Float, color:Int):Void
		Raw.host._wgr_shape3d_draw_cube(cx, cy, cz, width, height, length, color);

	public static inline function wgr_shape3d_draw_cube_wires(cx:Float, cy:Float, cz:Float, width:Float, height:Float, length:Float, color:Int):Void
		Raw.host._wgr_shape3d_draw_cube_wires(cx, cy, cz, width, height, length, color);

	public static inline function wgr_shape3d_draw_sphere(cx:Float, cy:Float, cz:Float, radius:Float, color:Int):Void
		Raw.host._wgr_shape3d_draw_sphere(cx, cy, cz, radius, color);

	public static inline function wgr_shape3d_draw_grid(slices:Int, spacing:Float, color:Int):Void
		Raw.host._wgr_shape3d_draw_grid(slices, spacing, color);

	public static inline function wgr_shape3d_draw_rectangle(cx:Float, cy:Float, cz:Float, width:Float, height:Float, rx:Float, ry:Float, rz:Float, color:Int):Void
		Raw.host._wgr_shape3d_draw_rectangle(cx, cy, cz, width, height, rx, ry, rz, color);

	public static inline function wgr_shape3d_draw_circle(cx:Float, cy:Float, cz:Float, radius:Float, rx:Float, ry:Float, rz:Float, color:Int):Void
		Raw.host._wgr_shape3d_draw_circle(cx, cy, cz, radius, rx, ry, rz, color);

	public static inline function wgr_shape3d_create():Int
		return Raw.host._wgr_shape3d_create();

	public static inline function wgr_shape3d_destroy(shape:Int):Void
		Raw.host._wgr_shape3d_destroy(shape);

	public static inline function wgr_shape3d_set_cube(shape:Int, width:Float, height:Float, length:Float):Bool
		return Raw.host._wgr_shape3d_set_cube(shape, width, height, length) != 0;

	public static inline function wgr_shape3d_set_sphere(shape:Int, radius:Float):Bool
		return Raw.host._wgr_shape3d_set_sphere(shape, radius) != 0;

	public static inline function wgr_shape3d_set_rectangle(shape:Int, width:Float, height:Float):Bool
		return Raw.host._wgr_shape3d_set_rectangle(shape, width, height) != 0;

	public static inline function wgr_shape3d_set_circle(shape:Int, radius:Float):Bool
		return Raw.host._wgr_shape3d_set_circle(shape, radius) != 0;

	public static inline function wgr_shape3d_set_line(shape:Int, x0:Float, y0:Float, z0:Float, x1:Float, y1:Float, z1:Float):Bool
		return Raw.host._wgr_shape3d_set_line(shape, x0, y0, z0, x1, y1, z1) != 0;

	public static inline function wgr_shape3d_set_line_strip(shape:Int):Bool
		return Raw.host._wgr_shape3d_set_line_strip(shape) != 0;

	public static inline function wgr_shape3d_add_point(shape:Int, x:Float, y:Float, z:Float):Bool
		return Raw.host._wgr_shape3d_add_point(shape, x, y, z) != 0;

	public static inline function wgr_shape3d_get_point_count(shape:Int):Int
		return Raw.host._wgr_shape3d_get_point_count(shape);

	public static inline function wgr_shape3d_set_transform(shape:Int, position_x:Float, position_y:Float, position_z:Float, rotation_x:Float, rotation_y:Float, rotation_z:Float, scale_x:Float, scale_y:Float, scale_z:Float):Bool
		return Raw.host._wgr_shape3d_set_transform(shape, position_x, position_y, position_z, rotation_x, rotation_y, rotation_z, scale_x, scale_y, scale_z) != 0;

	public static inline function wgr_shape3d_set_color(shape:Int, color:Int):Bool
		return Raw.host._wgr_shape3d_set_color(shape, color) != 0;

	public static inline function wgr_shape3d_set_visible(shape:Int, visible:Bool):Bool
		return Raw.host._wgr_shape3d_set_visible(shape, visible) != 0;

	public static inline function wgr_shape3d_is_visible(shape:Int):Bool
		return Raw.host._wgr_shape3d_is_visible(shape) != 0;

	public static inline function wgr_shape3d_set_pickable(shape:Int, pickable:Bool):Bool
		return Raw.host._wgr_shape3d_set_pickable(shape, pickable) != 0;

	public static inline function wgr_shape3d_is_pickable(shape:Int):Bool
		return Raw.host._wgr_shape3d_is_pickable(shape) != 0;

	public static inline function wgr_shape3d_set_enabled(shape:Int, enabled:Bool):Bool
		return Raw.host._wgr_shape3d_set_enabled(shape, enabled) != 0;

	public static inline function wgr_shape3d_is_enabled(shape:Int):Bool
		return Raw.host._wgr_shape3d_is_enabled(shape) != 0;

	public static inline function wgr_shape3d_draw(shape:Int):Void
		Raw.host._wgr_shape3d_draw(shape);

	public static inline function wgr_sound_create(audio:Int):Int
		return Raw.host._wgr_sound_create(audio);

	public static inline function wgr_sound_set_audio(handle:Int, audio:Int):Bool
		return Raw.host._wgr_sound_set_audio(handle, audio) != 0;

	public static inline function wgr_sound_destroy(handle:Int):Void
		Raw.host._wgr_sound_destroy(handle);

	public static inline function wgr_sound_play(handle:Int):Bool
		return Raw.host._wgr_sound_play(handle) != 0;

	public static inline function wgr_sound_pause(handle:Int):Bool
		return Raw.host._wgr_sound_pause(handle) != 0;

	public static inline function wgr_sound_resume(handle:Int):Bool
		return Raw.host._wgr_sound_resume(handle) != 0;

	public static inline function wgr_sound_stop(handle:Int):Bool
		return Raw.host._wgr_sound_stop(handle) != 0;

	public static inline function wgr_sound_set_loop(handle:Int, loop:Bool):Bool
		return Raw.host._wgr_sound_set_loop(handle, loop) != 0;

	public static inline function wgr_sound_set_volume(handle:Int, volume:Float):Bool
		return Raw.host._wgr_sound_set_volume(handle, volume) != 0;

	public static inline function wgr_sound_set_pitch(handle:Int, pitch:Float):Bool
		return Raw.host._wgr_sound_set_pitch(handle, pitch) != 0;

	public static inline function wgr_sound_set_pan(handle:Int, pan:Float):Bool
		return Raw.host._wgr_sound_set_pan(handle, pan) != 0;

	public static inline function wgr_sound_is_playing(handle:Int):Bool
		return Raw.host._wgr_sound_is_playing(handle) != 0;

	public static inline function wgr_sprite2d_create(texture:Int):Int
		return Raw.host._wgr_sprite2d_create(texture);

	public static inline function wgr_sprite2d_destroy(sprite:Int):Void
		Raw.host._wgr_sprite2d_destroy(sprite);

	public static inline function wgr_sprite2d_set_texture(sprite:Int, texture:Int):Bool
		return Raw.host._wgr_sprite2d_set_texture(sprite, texture) != 0;

	public static inline function wgr_sprite2d_set_source(sprite:Int, x:Float, y:Float, width:Float, height:Float):Bool
		return Raw.host._wgr_sprite2d_set_source(sprite, x, y, width, height) != 0;

	public static inline function wgr_sprite2d_set_position(sprite:Int, x:Float, y:Float):Bool
		return Raw.host._wgr_sprite2d_set_position(sprite, x, y) != 0;

	public static inline function wgr_sprite2d_set_rotation(sprite:Int, angle:Float):Bool
		return Raw.host._wgr_sprite2d_set_rotation(sprite, angle) != 0;

	public static inline function wgr_sprite2d_set_scale(sprite:Int, x:Float, y:Float):Bool
		return Raw.host._wgr_sprite2d_set_scale(sprite, x, y) != 0;

	public static inline function wgr_sprite2d_set_size(sprite:Int, width:Float, height:Float):Bool
		return Raw.host._wgr_sprite2d_set_size(sprite, width, height) != 0;

	public static inline function wgr_sprite2d_set_pivot(sprite:Int, x:Float, y:Float):Bool
		return Raw.host._wgr_sprite2d_set_pivot(sprite, x, y) != 0;

	public static inline function wgr_sprite2d_set_nine_slice(sprite:Int, left:Float, top:Float, right:Float, bottom:Float):Bool
		return Raw.host._wgr_sprite2d_set_nine_slice(sprite, left, top, right, bottom) != 0;

	public static inline function wgr_sprite2d_set_tint(sprite:Int, color:Int):Bool
		return Raw.host._wgr_sprite2d_set_tint(sprite, color) != 0;

	public static inline function wgr_sprite2d_set_visible(sprite:Int, visible:Bool):Bool
		return Raw.host._wgr_sprite2d_set_visible(sprite, visible) != 0;

	public static inline function wgr_sprite2d_is_visible(sprite:Int):Bool
		return Raw.host._wgr_sprite2d_is_visible(sprite) != 0;

	public static inline function wgr_sprite2d_set_pickable(sprite:Int, pickable:Bool):Bool
		return Raw.host._wgr_sprite2d_set_pickable(sprite, pickable) != 0;

	public static inline function wgr_sprite2d_is_pickable(sprite:Int):Bool
		return Raw.host._wgr_sprite2d_is_pickable(sprite) != 0;

	public static inline function wgr_sprite2d_set_enabled(sprite:Int, enabled:Bool):Bool
		return Raw.host._wgr_sprite2d_set_enabled(sprite, enabled) != 0;

	public static inline function wgr_sprite2d_is_enabled(sprite:Int):Bool
		return Raw.host._wgr_sprite2d_is_enabled(sprite) != 0;

	public static inline function wgr_sprite2d_set_alpha_mode(sprite:Int, mode:Int, cutoff:Float):Bool
		return Raw.host._wgr_sprite2d_set_alpha_mode(sprite, mode, cutoff) != 0;

	public static inline function wgr_sprite2d_get_alpha_mode(sprite:Int):Int
		return Raw.host._wgr_sprite2d_get_alpha_mode(sprite);

	public static inline function wgr_sprite2d_set_material(sprite:Int, material:Int):Bool
		return Raw.host._wgr_sprite2d_set_material(sprite, material) != 0;

	public static inline function wgr_sprite2d_get_material(sprite:Int):Int
		return Raw.host._wgr_sprite2d_get_material(sprite);

	public static inline function wgr_sprite2d_set_pick_alpha_test(sprite:Int, enable:Bool, threshold:Float):Bool
		return Raw.host._wgr_sprite2d_set_pick_alpha_test(sprite, enable, threshold) != 0;

	public static inline function wgr_sprite2d_draw(sprite:Int):Void
		Raw.host._wgr_sprite2d_draw(sprite);

	public static inline function wgr_sprite3d_create(texture:Int):Int
		return Raw.host._wgr_sprite3d_create(texture);

	public static inline function wgr_sprite3d_set_texture(handle:Int, texture:Int):Bool
		return Raw.host._wgr_sprite3d_set_texture(handle, texture) != 0;

	public static inline function wgr_sprite3d_set_transform(handle:Int, position_x:Float, position_y:Float, position_z:Float, rotation_x:Float, rotation_y:Float, rotation_z:Float, scale_x:Float, scale_y:Float, scale_z:Float):Bool
		return Raw.host._wgr_sprite3d_set_transform(handle, position_x, position_y, position_z, rotation_x, rotation_y, rotation_z, scale_x, scale_y, scale_z) != 0;

	public static inline function wgr_sprite3d_set_size(handle:Int, size:Float):Bool
		return Raw.host._wgr_sprite3d_set_size(handle, size) != 0;

	public static inline function wgr_sprite3d_set_extent(handle:Int, width:Float, height:Float):Bool
		return Raw.host._wgr_sprite3d_set_extent(handle, width, height) != 0;

	public static inline function wgr_sprite3d_set_source(handle:Int, x:Float, y:Float, width:Float, height:Float):Bool
		return Raw.host._wgr_sprite3d_set_source(handle, x, y, width, height) != 0;

	public static inline function wgr_sprite3d_set_pivot(handle:Int, x:Float, y:Float):Bool
		return Raw.host._wgr_sprite3d_set_pivot(handle, x, y) != 0;

	public static inline function wgr_sprite3d_set_facing(handle:Int, facing:Int):Bool
		return Raw.host._wgr_sprite3d_set_facing(handle, facing) != 0;

	public static function wgr_sprite3d_get_position(handle:Int):Vec3 {
		final out = scratch(12);
		Raw.host._wgr_sprite3d_get_position(out, handle);
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new Vec3(f32[base + 0], f32[base + 1], f32[base + 2]);
	}

	public static function wgr_sprite3d_get_rotation(handle:Int):Vec3 {
		final out = scratch(12);
		Raw.host._wgr_sprite3d_get_rotation(out, handle);
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new Vec3(f32[base + 0], f32[base + 1], f32[base + 2]);
	}

	public static function wgr_sprite3d_get_scale(handle:Int):Vec3 {
		final out = scratch(12);
		Raw.host._wgr_sprite3d_get_scale(out, handle);
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new Vec3(f32[base + 0], f32[base + 1], f32[base + 2]);
	}

	public static inline function wgr_sprite3d_set_tint(handle:Int, color:Int):Bool
		return Raw.host._wgr_sprite3d_set_tint(handle, color) != 0;

	public static inline function wgr_sprite3d_set_visible(handle:Int, visible:Bool):Bool
		return Raw.host._wgr_sprite3d_set_visible(handle, visible) != 0;

	public static inline function wgr_sprite3d_is_visible(handle:Int):Bool
		return Raw.host._wgr_sprite3d_is_visible(handle) != 0;

	public static inline function wgr_sprite3d_set_pickable(handle:Int, pickable:Bool):Bool
		return Raw.host._wgr_sprite3d_set_pickable(handle, pickable) != 0;

	public static inline function wgr_sprite3d_is_pickable(handle:Int):Bool
		return Raw.host._wgr_sprite3d_is_pickable(handle) != 0;

	public static inline function wgr_sprite3d_set_enabled(sprite:Int, enabled:Bool):Bool
		return Raw.host._wgr_sprite3d_set_enabled(sprite, enabled) != 0;

	public static inline function wgr_sprite3d_is_enabled(sprite:Int):Bool
		return Raw.host._wgr_sprite3d_is_enabled(sprite) != 0;

	public static inline function wgr_sprite3d_set_alpha_mode(handle:Int, mode:Int, cutoff:Float):Bool
		return Raw.host._wgr_sprite3d_set_alpha_mode(handle, mode, cutoff) != 0;

	public static inline function wgr_sprite3d_get_alpha_mode(handle:Int):Int
		return Raw.host._wgr_sprite3d_get_alpha_mode(handle);

	public static inline function wgr_sprite3d_set_material(handle:Int, material:Int):Bool
		return Raw.host._wgr_sprite3d_set_material(handle, material) != 0;

	public static inline function wgr_sprite3d_get_material(handle:Int):Int
		return Raw.host._wgr_sprite3d_get_material(handle);

	public static inline function wgr_sprite3d_set_pick_alpha_test(handle:Int, enable:Bool, threshold:Float):Bool
		return Raw.host._wgr_sprite3d_set_pick_alpha_test(handle, enable, threshold) != 0;

	public static inline function wgr_sprite3d_draw(handle:Int):Void
		Raw.host._wgr_sprite3d_draw(handle);

	public static inline function wgr_sprite3d_destroy(handle:Int):Void
		Raw.host._wgr_sprite3d_destroy(handle);

	public static inline function wgr_text_set_default_font(font:Int):Bool
		return Raw.host._wgr_text_set_default_font(font) != 0;

	public static inline function wgr_text_get_default_font():Int
		return Raw.host._wgr_text_get_default_font();

	public static inline function wgr_text_draw_fps(x:Int, y:Int):Void
		Raw.host._wgr_text_draw_fps(x, y);

	public static inline function wgr_text_draw_fps_ex(font:Int, x:Float, y:Float, size:Float, color:Int):Void
		Raw.host._wgr_text_draw_fps_ex(font, x, y, size, color);

	public static inline function wgr_text_draw(text:String, x:Int, y:Int, font_size:Int, color:Int):Void
		Raw.host._wgr_text_draw(cstr(text), x, y, font_size, color);

	public static inline function wgr_text_measure(text:String, font_size:Int):Int
		return Raw.host._wgr_text_measure(cstr(text), font_size);

	public static inline function wgr_text_draw_ex(font:Int, text:String, x:Float, y:Float, size:Float, color:Int):Void
		Raw.host._wgr_text_draw_ex(font, cstr(text), x, y, size, color);

	public static function wgr_text_measure_ex(font:Int, text:String, size:Float):Vec2 {
		final out = scratch(8);
		Raw.host._wgr_text_measure_ex(out, font, cstr(text), size);
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new Vec2(f32[base + 0], f32[base + 1]);
	}

	public static inline function wgr_text_draw_n(font:Int, text:String, length:Int, x:Float, y:Float, size:Float, color:Int):Void
		Raw.host._wgr_text_draw_n(font, cstr(text), length, x, y, size, color);

	public static function wgr_text_measure_n(font:Int, text:String, length:Int, size:Float):Vec2 {
		final out = scratch(8);
		Raw.host._wgr_text_measure_n(out, font, cstr(text), length, size);
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new Vec2(f32[base + 0], f32[base + 1]);
	}

	public static inline function wgr_text2d_create(font:Int):Int
		return Raw.host._wgr_text2d_create(font);

	public static inline function wgr_text2d_set_font(handle:Int, font:Int):Bool
		return Raw.host._wgr_text2d_set_font(handle, font) != 0;

	public static inline function wgr_text2d_set_text(handle:Int, text:String):Bool
		return Raw.host._wgr_text2d_set_text(handle, cstr(text)) != 0;

	public static inline function wgr_text2d_set_position(handle:Int, x:Float, y:Float):Bool
		return Raw.host._wgr_text2d_set_position(handle, x, y) != 0;

	public static inline function wgr_text2d_set_size(handle:Int, size:Float):Bool
		return Raw.host._wgr_text2d_set_size(handle, size) != 0;

	public static inline function wgr_text2d_set_color(handle:Int, color:Int):Bool
		return Raw.host._wgr_text2d_set_color(handle, color) != 0;

	public static inline function wgr_text2d_set_visible(handle:Int, visible:Bool):Bool
		return Raw.host._wgr_text2d_set_visible(handle, visible) != 0;

	public static inline function wgr_text2d_is_visible(handle:Int):Bool
		return Raw.host._wgr_text2d_is_visible(handle) != 0;

	public static inline function wgr_text2d_set_pickable(handle:Int, pickable:Bool):Bool
		return Raw.host._wgr_text2d_set_pickable(handle, pickable) != 0;

	public static inline function wgr_text2d_is_pickable(handle:Int):Bool
		return Raw.host._wgr_text2d_is_pickable(handle) != 0;

	public static inline function wgr_text2d_set_enabled(text:Int, enabled:Bool):Bool
		return Raw.host._wgr_text2d_set_enabled(text, enabled) != 0;

	public static inline function wgr_text2d_is_enabled(text:Int):Bool
		return Raw.host._wgr_text2d_is_enabled(text) != 0;

	public static inline function wgr_text2d_set_align(handle:Int, horizontal:Int, vertical:Int):Bool
		return Raw.host._wgr_text2d_set_align(handle, horizontal, vertical) != 0;

	public static inline function wgr_text2d_set_max_width(handle:Int, width:Float):Bool
		return Raw.host._wgr_text2d_set_max_width(handle, width) != 0;

	public static inline function wgr_text2d_measure_width(handle:Int):Float
		return Raw.host._wgr_text2d_measure_width(handle);

	public static inline function wgr_text2d_measure_height(handle:Int):Float
		return Raw.host._wgr_text2d_measure_height(handle);

	public static inline function wgr_text2d_draw(handle:Int):Void
		Raw.host._wgr_text2d_draw(handle);

	public static inline function wgr_text2d_destroy(handle:Int):Void
		Raw.host._wgr_text2d_destroy(handle);

	public static inline function wgr_text3d_create(font:Int):Int
		return Raw.host._wgr_text3d_create(font);

	public static inline function wgr_text3d_destroy(text:Int):Void
		Raw.host._wgr_text3d_destroy(text);

	public static inline function wgr_text3d_set_font(text:Int, font:Int):Bool
		return Raw.host._wgr_text3d_set_font(text, font) != 0;

	public static inline function wgr_text3d_set_text(text:Int, string:String):Bool
		return Raw.host._wgr_text3d_set_text(text, cstr(string)) != 0;

	public static inline function wgr_text3d_set_size(text:Int, size:Float):Bool
		return Raw.host._wgr_text3d_set_size(text, size) != 0;

	public static inline function wgr_text3d_set_align(text:Int, horizontal:Int, vertical:Int):Bool
		return Raw.host._wgr_text3d_set_align(text, horizontal, vertical) != 0;

	public static inline function wgr_text3d_set_max_width(text:Int, width:Float):Bool
		return Raw.host._wgr_text3d_set_max_width(text, width) != 0;

	public static inline function wgr_text3d_set_transform(text:Int, x:Float, y:Float, z:Float, rotation_x:Float, rotation_y:Float, rotation_z:Float):Bool
		return Raw.host._wgr_text3d_set_transform(text, x, y, z, rotation_x, rotation_y, rotation_z) != 0;

	public static inline function wgr_text3d_set_facing(text:Int, facing:Int):Bool
		return Raw.host._wgr_text3d_set_facing(text, facing) != 0;

	public static inline function wgr_text3d_set_color(text:Int, color:Int):Bool
		return Raw.host._wgr_text3d_set_color(text, color) != 0;

	public static inline function wgr_text3d_set_visible(text:Int, visible:Bool):Bool
		return Raw.host._wgr_text3d_set_visible(text, visible) != 0;

	public static inline function wgr_text3d_is_visible(text:Int):Bool
		return Raw.host._wgr_text3d_is_visible(text) != 0;

	public static inline function wgr_text3d_set_pickable(text:Int, pickable:Bool):Bool
		return Raw.host._wgr_text3d_set_pickable(text, pickable) != 0;

	public static inline function wgr_text3d_is_pickable(text:Int):Bool
		return Raw.host._wgr_text3d_is_pickable(text) != 0;

	public static inline function wgr_text3d_set_enabled(text:Int, enabled:Bool):Bool
		return Raw.host._wgr_text3d_set_enabled(text, enabled) != 0;

	public static inline function wgr_text3d_is_enabled(text:Int):Bool
		return Raw.host._wgr_text3d_is_enabled(text) != 0;

	public static function wgr_text3d_get_size(text:Int):Vec2 {
		final out = scratch(8);
		Raw.host._wgr_text3d_get_size(out, text);
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new Vec2(f32[base + 0], f32[base + 1]);
	}

	public static inline function wgr_text3d_draw(text:Int):Void
		Raw.host._wgr_text3d_draw(text);

	public static inline function wgr_text_draw_3d(font:Int, text:String, x:Float, y:Float, z:Float, size:Float, color:Int):Void
		Raw.host._wgr_text_draw_3d(font, cstr(text), x, y, z, size, color);

	public static inline function wgr_texture_get_default():Int
		return Raw.host._wgr_texture_get_default();

	public static inline function wgr_texture_get_placeholder():Int
		return Raw.host._wgr_texture_get_placeholder();

	public static inline function wgr_texture_set_placeholder(texture:Int):Bool
		return Raw.host._wgr_texture_set_placeholder(texture) != 0;

	public static inline function wgr_texture_create(path:String):Int
		return Raw.host._wgr_texture_create(cstr(path));

	public static inline function wgr_texture_create_target(width:Int, height:Int):Int
		return Raw.host._wgr_texture_create_target(width, height);

	public static inline function wgr_texture_set_sampling(texture:Int, wrap_u:Int, wrap_v:Int, filter:Int):Bool
		return Raw.host._wgr_texture_set_sampling(texture, wrap_u, wrap_v, filter) != 0;

	public static function wgr_texture_get_size(handle:Int):Vec2 {
		final out = scratch(8);
		Raw.host._wgr_texture_get_size(out, handle);
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new Vec2(f32[base + 0], f32[base + 1]);
	}

	public static inline function wgr_texture_draw(texture:Int, x:Float, y:Float, width:Float, height:Float, tint:Int):Void
		Raw.host._wgr_texture_draw(texture, x, y, width, height, tint);

	public static inline function wgr_texture_draw_ex(texture:Int, source_x:Float, source_y:Float, source_width:Float, source_height:Float, x:Float, y:Float, width:Float, height:Float, tint:Int):Void
		Raw.host._wgr_texture_draw_ex(texture, source_x, source_y, source_width, source_height, x, y, width, height, tint);

	public static inline function wgr_texture_draw_nine_slice(texture:Int, source_x:Float, source_y:Float, source_width:Float, source_height:Float, left:Float, top:Float, right:Float, bottom:Float, x:Float, y:Float, width:Float, height:Float, tint:Int):Void
		Raw.host._wgr_texture_draw_nine_slice(texture, source_x, source_y, source_width, source_height, left, top, right, bottom, x, y, width, height, tint);

	public static inline function wgr_texture_release(handle:Int):Void
		Raw.host._wgr_texture_release(handle);

	public static inline function wgr_version_major():Int
		return Raw.host._wgr_version_major();

	public static inline function wgr_version_minor():Int
		return Raw.host._wgr_version_minor();

	public static inline function wgr_version_patch():Int
		return Raw.host._wgr_version_patch();

	public static inline function wgr_version_label():String
		return str(Raw.host._wgr_version_label());

	public static inline function wgr_version_number():Int
		return Raw.host._wgr_version_number();

	public static inline function wgr_version_string():String
		return str(Raw.host._wgr_version_string());

	public static inline function wgr_window_set_title(title:String):Void
		Raw.host._wgr_window_set_title(cstr(title));

	public static inline function wgr_window_close_requested():Int
		return Raw.host._wgr_window_close_requested();

	public static function wgr_window_get_screen_size():Vec2 {
		final out = scratch(8);
		Raw.host._wgr_window_get_screen_size(out);
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new Vec2(f32[base + 0], f32[base + 1]);
	}

	public static inline function wgr_window_set_size(width:Int, height:Int):Bool
		return Raw.host._wgr_window_set_size(width, height) != 0;

	public static inline function wgr_window_set_position(x:Int, y:Int):Bool
		return Raw.host._wgr_window_set_position(x, y) != 0;

	public static function wgr_window_get_position():Vec2 {
		final out = scratch(8);
		Raw.host._wgr_window_get_position(out);
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new Vec2(f32[base + 0], f32[base + 1]);
	}

	public static inline function wgr_window_set_fullscreen(fullscreen:Bool):Bool
		return Raw.host._wgr_window_set_fullscreen(fullscreen) != 0;

	public static inline function wgr_window_is_fullscreen():Bool
		return Raw.host._wgr_window_is_fullscreen() != 0;

	public static inline function wgr_window_set_visible(visible:Bool):Bool
		return Raw.host._wgr_window_set_visible(visible) != 0;

	public static inline function wgr_window_is_visible():Bool
		return Raw.host._wgr_window_is_visible() != 0;

	public static inline function wgr_window_is_focused():Bool
		return Raw.host._wgr_window_is_focused() != 0;

	public static inline function wgr_window_get_monitor_count():Int
		return Raw.host._wgr_window_get_monitor_count();

	public static inline function wgr_window_get_monitor():Int
		return Raw.host._wgr_window_get_monitor();

	public static inline function wgr_window_set_monitor(monitor:Int):Bool
		return Raw.host._wgr_window_set_monitor(monitor) != 0;

	public static function wgr_window_get_monitor_size(monitor:Int):Vec2 {
		final out = scratch(8);
		Raw.host._wgr_window_get_monitor_size(out, monitor);
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new Vec2(f32[base + 0], f32[base + 1]);
	}

	public static function wgr_window_get_monitor_position(monitor:Int):Vec2 {
		final out = scratch(8);
		Raw.host._wgr_window_get_monitor_position(out, monitor);
		final f32 = Raw.host.HEAPF32;
		final base = out >> 2;
		return new Vec2(f32[base + 0], f32[base + 1]);
	}

	public static inline function wgr_window_get_monitor_name(monitor:Int):String
		return str(Raw.host._wgr_window_get_monitor_name(monitor));

	/** The varargs logger, fixed at one `%s` — enough for a Haxe string. **/
	public static inline function wgr_logger_message(level:Int, format:String, text:String):Void
		Raw.host._wgr_logger_message(level, cstr(format), cstr(text));

	/** The same, with the call site the WGR_LOG_* macros would have filled in. **/
	public static inline function wgr_logger_message_source(level:Int, sourceFile:String, sourceLine:Int,
			format:String, text:String):Void
		Raw.host._wgr_logger_message_source(level, cstr(sourceFile), sourceLine, cstr(format), cstr(text));
}

/**
	Where `wgr_keyboard_state_t`'s fields sit, in ints from the pointer. Offsets are
	generated from the header, so a layout change moves them rather than
	silently misreading. An array field gives the index of its first element.
**/
class KeyboardStateLayout {
	public static inline var BYTES = 2324;
	public static inline var maxNumKeys = 0;
	public static inline var keys = 1; // [512]
	public static inline var pressedKey = 513;
	public static inline var pressedChar = 514;
	public static inline var numPressedKeys = 515;
	public static inline var pressedKeys = 516; // [32]
	public static inline var numPressedChars = 548;
	public static inline var pressedChars = 549; // [32]

	public static inline function read(pointer:Int, index:Int):Int
		return (Raw.host.HEAP32 : Array<Int>)[(pointer >> 2) + index];
}
