package wgr.impl;

// GENERATED by tools/gen_raw.py from wgrender's include/*.h — do not edit.
// Re-run the tool when wgrender's API moves; it writes this file whole.
//
// wgrender 0.0.1 at 8e5e635, 34 headers.
// wgrender-headers: 017dae86087a6947

import cpp.ConstCharStar;
import cpp.RawPointer;
import cpp.UInt32;

typedef WgrHandle = UInt32;
typedef WgrColor = UInt32;

/** C `void *`: the opaque user pointer every wgrender callback carries. **/
typedef VoidStar = RawPointer<cpp.Void>;
/** The ABI types the callback plumbing shares with js; see Raw.js.hx. **/
typedef CStr = ConstCharStar;
typedef F32 = Single;

typedef AssetCallbackFn = cpp.Callable<(path:ConstCharStar, user:VoidStar) -> Void>;
typedef AssetFetchFn = cpp.Callable<(request:WgrHandle, url:ConstCharStar, destPath:ConstCharStar, user:VoidStar) -> Void>;
typedef AssetPingFn = cpp.Callable<(host:ConstCharStar, milliseconds:Single, user:VoidStar) -> Void>;
typedef EventListenerFn = cpp.Callable<(payload:VoidStar, user:VoidStar) -> Void>;
typedef FrameFn = cpp.Callable<(dt:Single, tickFraction:Single, user:VoidStar) -> Void>;
typedef LifecycleFn = cpp.Callable<(user:VoidStar) -> Void>;
typedef TickFn = cpp.Callable<(dt:Single, user:VoidStar) -> Void>;

// Structs the API returns by value. C++ takes them as values; the JS side reads
// them out of the heap (see Raw.js.hx).
@:include("wgr.h") @:native("vec2_t") @:structAccess @:unreflective
extern class CVec2 {
	var x:Single;
	var y:Single;
}

@:include("wgr.h") @:native("vec3_t") @:structAccess @:unreflective
extern class CVec3 {
	var x:Single;
	var y:Single;
	var z:Single;
}

@:include("wgr.h") @:native("wgr_keyboard_state_t") @:structAccess @:unreflective
extern class CKeyboardState {
	var max_num_keys:Int;
	/** C `int[512]`, so it reads as a pointer here; index it in place. **/
	var keys:cpp.RawPointer<Int>;
	var pressed_key:Int;
	var pressed_char:Int;
	var num_pressed_keys:Int;
	/** C `int[32]`, so it reads as a pointer here; index it in place. **/
	var pressed_keys:cpp.RawPointer<Int>;
	var num_pressed_chars:Int;
	/** C `int[32]`, so it reads as a pointer here; index it in place. **/
	var pressed_chars:cpp.RawPointer<Int>;
}

@:include("wgr.h") @:native("wgr_mouse_state_t") @:structAccess @:unreflective
extern class CMouseState {
	var x:Int;
	var y:Int;
	var wheel:Single;
	var wheel_x:Single;
	var left:Int;
	var right:Int;
	var middle:Int;
	/** C `int[3]`, so it reads as a pointer here; index it in place. **/
	var buttons:cpp.RawPointer<Int>;
	var dx:Int;
	var dy:Int;
}

@:include("wgr.h") @:native("wgr_pick_result_t") @:structAccess @:unreflective
extern class CPickResult {
	var hit:Bool;
	var handle:WgrHandle;
	var distance:Single;
	var point_local:CVec3;
	var point_world:CVec3;
	var normal_local:CVec3;
	var normal_world:CVec3;
}

@:include("wgr.h") @:native("wgr_pick_stats_t") @:structAccess @:unreflective
extern class CPickStats {
	var broadphase_tests:Int;
	var broadphase_rejects:Int;
	var narrowphase_tests:Int;
	var narrowphase_hits:Int;
}

@:include("wgr.h") @:native("wgr_touch_gesture_t") @:structAccess @:unreflective
extern class CTouchGesture {
	var active:Bool;
	var x:Single;
	var y:Single;
	var dx:Single;
	var dy:Single;
	var scale:Single;
	var rotation:Single;
}

@:include("wgr.h") @:native("wgr_touch_t") @:structAccess @:unreflective
extern class CTouch {
	var id:Int;
	var x:Single;
	var y:Single;
	var dx:Single;
	var dy:Single;
	var state:Int;
}

// C enum parameter types: C++ will not take an `int` where the header names an
// enum, so wgr's enum abstracts cast to these (see their `toRaw`).
@:include("wgr.h") @:native("wgr_alpha_mode_t") @:structAccess @:unreflective
extern class CAlphaMode {}

@:include("wgr.h") @:native("wgr_asset_add_task_result_t") @:structAccess @:unreflective
extern class CAssetAddTaskResult {}

@:include("wgr.h") @:native("wgr_button_state_t") @:structAccess @:unreflective
extern class CButtonState {}

@:include("wgr.h") @:native("wgr_camera3d_projection_t") @:structAccess @:unreflective
extern class CCamera3DProjection {}

@:include("wgr.h") @:native("wgr_gamepad_axis_t") @:structAccess @:unreflective
extern class CGamepadAxis {}

@:include("wgr.h") @:native("wgr_gamepad_button_t") @:structAccess @:unreflective
extern class CGamepadButton {}

@:include("wgr.h") @:native("wgr_handle_kind_t") @:structAccess @:unreflective
extern class CHandleKind {}

@:include("wgr.h") @:native("wgr_keycode_t") @:structAccess @:unreflective
extern class CKeycode {}

@:include("wgr.h") @:native("wgr_light_type_t") @:structAccess @:unreflective
extern class CLightType {}

@:include("wgr.h") @:native("wgr_log_level_t") @:structAccess @:unreflective
extern class CLogLevel {}

@:include("wgr.h") @:native("wgr_material_shading_t") @:structAccess @:unreflective
extern class CMaterialShading {}

@:include("wgr.h") @:native("wgr_sprite3d_facing_t") @:structAccess @:unreflective
extern class CSprite3DFacing {}

@:include("wgr.h") @:native("wgr_text_align_t") @:structAccess @:unreflective
extern class CTextAlign {}

@:include("wgr.h") @:native("wgr_texture_filter_t") @:structAccess @:unreflective
extern class CTextureFilter {}

@:include("wgr.h") @:native("wgr_texture_wrap_t") @:structAccess @:unreflective
extern class CTextureWrap {}

@:include("wgr.h") @:native("wgr_tonemap_t") @:structAccess @:unreflective
extern class CTonemap {}

// Where wgrender is and how to link it. This rides here because every program
// that touches wgrender at all reaches this class, so -dce full cannot strip it
// out from under the build the way it can any class in the API layer.
//
// A checkout defines WGR_BUILD_XML and points it at whatever wgrender it is
// working against -- the examples and test/check.py each write one. An install
// has none and falls through to project/Build.xml, which links the wgrender-c
// submodule under project/lib.
//
// The switch is on WGR_BUILD_XML rather than on the `wgrender_hx` define that
// -lib sets, because the in-repo examples use -lib too: that define says which
// binding is in use, not which wgrender to link against.
@:buildXml('
	<include name="${WGR_BUILD_XML}" if="WGR_BUILD_XML" />
	<include name="${haxelib:wgrender-hx}/project/Build.xml" unless="WGR_BUILD_XML" />
')
@:keep @:unreflective @:include("wgr.h")
extern class Raw {
	@:native("wgr_init_values")
	static function wgr_init_values(window_width:Int, window_height:Int, window_title:ConstCharStar, window_flags:UInt32):Int;
	@:native("wgr_set_frame")
	static function wgr_set_frame(frame_fn:FrameFn, user_data:VoidStar):Void;
	@:native("wgr_set_tick")
	static function wgr_set_tick(tick_fn:TickFn, user_data:VoidStar, hz:Int):Void;
	@:native("wgr_set_init")
	static function wgr_set_init(init_fn:LifecycleFn, user_data:VoidStar):Void;
	@:native("wgr_set_cleanup")
	static function wgr_set_cleanup(cleanup_fn:LifecycleFn, user_data:VoidStar):Void;
	@:native("wgr_run")
	static function wgr_run():Int;
	@:native("wgr_request_quit")
	static function wgr_request_quit():Void;
	@:native("wgr_is_initialized")
	static function wgr_is_initialized():Bool;
	@:native("wgr_get_platform")
	static function wgr_get_platform():ConstCharStar;
	@:native("wgr_get_renderer")
	static function wgr_get_renderer():ConstCharStar;
	@:native("wgr_has_threads")
	static function wgr_has_threads():Bool;
	@:native("wgr_set_target_fps")
	static function wgr_set_target_fps(fps:Int):Void;
	@:native("wgr_get_time")
	static function wgr_get_time():Float;
	@:native("wgr_asset_set_host")
	static function wgr_asset_set_host(host:ConstCharStar):Void;
	@:native("wgr_asset_get_host")
	static function wgr_asset_get_host():ConstCharStar;
	@:native("wgr_asset_set_cache_dir")
	static function wgr_asset_set_cache_dir(dir:ConstCharStar):Bool;
	@:native("wgr_asset_set_fetcher")
	static function wgr_asset_set_fetcher(fn:AssetFetchFn, user_data:VoidStar):Bool;
	@:native("wgr_asset_fetch_done")
	static function wgr_asset_fetch_done(request:WgrHandle, ok:Bool):Bool;
	@:native("wgr_asset_evict")
	static function wgr_asset_evict(path:ConstCharStar):Bool;
	@:native("wgr_asset_clear_cache")
	static function wgr_asset_clear_cache():Void;
	@:native("wgr_asset_ensure_async")
	static function wgr_asset_ensure_async(path:ConstCharStar, fetch_url:ConstCharStar, flags:UInt32):WgrHandle;
	@:native("wgr_asset_add_task")
	static function wgr_asset_add_task(task:WgrHandle, on_success:AssetCallbackFn, on_failure:AssetCallbackFn, user_data:VoidStar):Int;
	@:native("wgr_asset_group_create")
	static function wgr_asset_group_create():WgrHandle;
	@:native("wgr_asset_group_add")
	static function wgr_asset_group_add(group:WgrHandle, task:WgrHandle):Bool;
	@:native("wgr_asset_get_progress")
	static function wgr_asset_get_progress(task:WgrHandle):Single;
	@:native("wgr_asset_add_redirect")
	static function wgr_asset_add_redirect(prefix:ConstCharStar, target:ConstCharStar):Bool;
	@:native("wgr_asset_clear_redirects")
	static function wgr_asset_clear_redirects():Void;
	@:native("wgr_asset_ping_host")
	static function wgr_asset_ping_host(host:ConstCharStar, timeout_ms:Int, on_done:AssetPingFn, user_data:VoidStar):Bool;
	@:native("wgr_asset_set_upload_budget")
	static function wgr_asset_set_upload_budget(milliseconds:Single):Void;
	@:native("wgr_audio_create")
	static function wgr_audio_create(path:ConstCharStar):WgrHandle;
	@:native("wgr_audio_release")
	static function wgr_audio_release(handle:WgrHandle):Void;
	@:native("wgr_camera3d_create")
	static function wgr_camera3d_create(projection:CCamera3DProjection):WgrHandle;
	@:native("wgr_camera3d_get_default")
	static function wgr_camera3d_get_default():WgrHandle;
	@:native("wgr_camera3d_destroy")
	static function wgr_camera3d_destroy(camera:WgrHandle):Void;
	@:native("wgr_camera3d_set_view")
	static function wgr_camera3d_set_view(camera:WgrHandle, position_x:Single, position_y:Single, position_z:Single, target_x:Single, target_y:Single, target_z:Single, up_x:Single, up_y:Single, up_z:Single):Bool;
	@:native("wgr_camera3d_set_projection")
	static function wgr_camera3d_set_projection(camera:WgrHandle, projection:CCamera3DProjection):Bool;
	@:native("wgr_camera3d_get_projection")
	static function wgr_camera3d_get_projection(camera:WgrHandle):Int;
	@:native("wgr_camera3d_set_fov")
	static function wgr_camera3d_set_fov(camera:WgrHandle, fov:Single):Bool;
	@:native("wgr_camera3d_get_fov")
	static function wgr_camera3d_get_fov(camera:WgrHandle):Single;
	@:native("wgr_camera3d_set_ortho_height")
	static function wgr_camera3d_set_ortho_height(camera:WgrHandle, height:Single):Bool;
	@:native("wgr_camera3d_get_ortho_height")
	static function wgr_camera3d_get_ortho_height(camera:WgrHandle):Single;
	@:native("wgr_camera3d_set_active")
	static function wgr_camera3d_set_active(camera:WgrHandle):Bool;
	@:native("wgr_camera3d_get_active")
	static function wgr_camera3d_get_active():WgrHandle;
	@:native("wgr_color_rgba")
	static function wgr_color_rgba(r:Int, g:Int, b:Int, a:Int):WgrColor;
	@:native("wgr_color_rgbaf")
	static function wgr_color_rgbaf(r:Single, g:Single, b:Single, a:Single):WgrColor;
	@:native("wgr_color_with_alpha")
	static function wgr_color_with_alpha(color:WgrColor, a:Int):WgrColor;
	@:native("wgr_color_get_red")
	static function wgr_color_get_red(color:WgrColor):Int;
	@:native("wgr_color_get_green")
	static function wgr_color_get_green(color:WgrColor):Int;
	@:native("wgr_color_get_blue")
	static function wgr_color_get_blue(color:WgrColor):Int;
	@:native("wgr_color_get_alpha")
	static function wgr_color_get_alpha(color:WgrColor):Int;
	@:native("wgr_color_lerp")
	static function wgr_color_lerp(from:WgrColor, to:WgrColor, t:Single):WgrColor;
	@:native("wgr_debug_enable_fps")
	static function wgr_debug_enable_fps(x:Int, y:Int, font_size:Int):Void;
	@:native("wgr_debug_disable_fps")
	static function wgr_debug_disable_fps():Void;
	@:native("wgr_emitter2d_create")
	static function wgr_emitter2d_create(texture:WgrHandle):WgrHandle;
	@:native("wgr_emitter2d_destroy")
	static function wgr_emitter2d_destroy(emitter:WgrHandle):Void;
	@:native("wgr_emitter2d_set_source")
	static function wgr_emitter2d_set_source(emitter:WgrHandle, x:Single, y:Single, width:Single, height:Single):Bool;
	@:native("wgr_emitter2d_set_frames")
	static function wgr_emitter2d_set_frames(emitter:WgrHandle, columns:Int, rows:Int, count:Int, per_second:Single):Bool;
	@:native("wgr_emitter2d_set_position")
	static function wgr_emitter2d_set_position(emitter:WgrHandle, x:Single, y:Single):Bool;
	@:native("wgr_emitter2d_jump")
	static function wgr_emitter2d_jump(emitter:WgrHandle, x:Single, y:Single):Bool;
	@:native("wgr_emitter2d_get_position")
	static function wgr_emitter2d_get_position(emitter:WgrHandle):CVec2;
	@:native("wgr_emitter2d_set_rate")
	static function wgr_emitter2d_set_rate(emitter:WgrHandle, per_second:Single):Bool;
	@:native("wgr_emitter2d_burst")
	static function wgr_emitter2d_burst(emitter:WgrHandle, count:Int):Bool;
	@:native("wgr_emitter2d_set_emitting")
	static function wgr_emitter2d_set_emitting(emitter:WgrHandle, emitting:Bool):Bool;
	@:native("wgr_emitter2d_is_emitting")
	static function wgr_emitter2d_is_emitting(emitter:WgrHandle):Bool;
	@:native("wgr_emitter2d_set_max")
	static function wgr_emitter2d_set_max(emitter:WgrHandle, count:Int):Bool;
	@:native("wgr_emitter2d_set_life")
	static function wgr_emitter2d_set_life(emitter:WgrHandle, min_seconds:Single, max_seconds:Single):Bool;
	@:native("wgr_emitter2d_prewarm")
	static function wgr_emitter2d_prewarm(emitter:WgrHandle, seconds:Single):Bool;
	@:native("wgr_emitter2d_set_spawn_box")
	static function wgr_emitter2d_set_spawn_box(emitter:WgrHandle, half_width:Single, half_height:Single):Bool;
	@:native("wgr_emitter2d_set_spawn_circle")
	static function wgr_emitter2d_set_spawn_circle(emitter:WgrHandle, radius:Single):Bool;
	@:native("wgr_emitter2d_set_velocity")
	static function wgr_emitter2d_set_velocity(emitter:WgrHandle, x:Single, y:Single, spread:Single, speed_variance:Single):Bool;
	@:native("wgr_emitter2d_set_gravity")
	static function wgr_emitter2d_set_gravity(emitter:WgrHandle, x:Single, y:Single):Bool;
	@:native("wgr_emitter2d_set_drag")
	static function wgr_emitter2d_set_drag(emitter:WgrHandle, per_second:Single):Bool;
	@:native("wgr_emitter2d_set_inherit_velocity")
	static function wgr_emitter2d_set_inherit_velocity(emitter:WgrHandle, fraction:Single):Bool;
	@:native("wgr_emitter2d_set_size")
	static function wgr_emitter2d_set_size(emitter:WgrHandle, start:Single, end:Single, variance:Single):Bool;
	@:native("wgr_emitter2d_set_color")
	static function wgr_emitter2d_set_color(emitter:WgrHandle, start:WgrColor, end:WgrColor):Bool;
	@:native("wgr_emitter2d_add_size_key")
	static function wgr_emitter2d_add_size_key(emitter:WgrHandle, t:Single, size:Single):Bool;
	@:native("wgr_emitter2d_clear_size_keys")
	static function wgr_emitter2d_clear_size_keys(emitter:WgrHandle):Bool;
	@:native("wgr_emitter2d_add_color_key")
	static function wgr_emitter2d_add_color_key(emitter:WgrHandle, t:Single, color:WgrColor):Bool;
	@:native("wgr_emitter2d_clear_color_keys")
	static function wgr_emitter2d_clear_color_keys(emitter:WgrHandle):Bool;
	@:native("wgr_emitter2d_add_palette_color")
	static function wgr_emitter2d_add_palette_color(emitter:WgrHandle, color:WgrColor):Bool;
	@:native("wgr_emitter2d_clear_palette")
	static function wgr_emitter2d_clear_palette(emitter:WgrHandle):Bool;
	@:native("wgr_emitter2d_set_spin")
	static function wgr_emitter2d_set_spin(emitter:WgrHandle, min:Single, max:Single):Bool;
	@:native("wgr_emitter2d_set_stretch")
	static function wgr_emitter2d_set_stretch(emitter:WgrHandle, seconds:Single):Bool;
	@:native("wgr_emitter2d_set_alpha_mode")
	static function wgr_emitter2d_set_alpha_mode(emitter:WgrHandle, mode:CAlphaMode, cutoff:Single):Bool;
	@:native("wgr_emitter2d_set_seed")
	static function wgr_emitter2d_set_seed(emitter:WgrHandle, seed:UInt32):Bool;
	@:native("wgr_emitter2d_get_count")
	static function wgr_emitter2d_get_count(emitter:WgrHandle):Int;
	@:native("wgr_emitter2d_clear")
	static function wgr_emitter2d_clear(emitter:WgrHandle):Void;
	@:native("wgr_emitter2d_set_visible")
	static function wgr_emitter2d_set_visible(emitter:WgrHandle, visible:Bool):Bool;
	@:native("wgr_emitter2d_draw")
	static function wgr_emitter2d_draw(emitter:WgrHandle):Void;
	@:native("wgr_emitter3d_create")
	static function wgr_emitter3d_create(texture:WgrHandle):WgrHandle;
	@:native("wgr_emitter3d_destroy")
	static function wgr_emitter3d_destroy(emitter:WgrHandle):Void;
	@:native("wgr_emitter3d_set_source")
	static function wgr_emitter3d_set_source(emitter:WgrHandle, x:Single, y:Single, width:Single, height:Single):Bool;
	@:native("wgr_emitter3d_set_frames")
	static function wgr_emitter3d_set_frames(emitter:WgrHandle, columns:Int, rows:Int, count:Int, per_second:Single):Bool;
	@:native("wgr_emitter3d_set_position")
	static function wgr_emitter3d_set_position(emitter:WgrHandle, x:Single, y:Single, z:Single):Bool;
	@:native("wgr_emitter3d_jump")
	static function wgr_emitter3d_jump(emitter:WgrHandle, x:Single, y:Single, z:Single):Bool;
	@:native("wgr_emitter3d_get_position")
	static function wgr_emitter3d_get_position(emitter:WgrHandle):CVec3;
	@:native("wgr_emitter3d_set_rate")
	static function wgr_emitter3d_set_rate(emitter:WgrHandle, per_second:Single):Bool;
	@:native("wgr_emitter3d_burst")
	static function wgr_emitter3d_burst(emitter:WgrHandle, count:Int):Bool;
	@:native("wgr_emitter3d_set_emitting")
	static function wgr_emitter3d_set_emitting(emitter:WgrHandle, emitting:Bool):Bool;
	@:native("wgr_emitter3d_is_emitting")
	static function wgr_emitter3d_is_emitting(emitter:WgrHandle):Bool;
	@:native("wgr_emitter3d_set_max")
	static function wgr_emitter3d_set_max(emitter:WgrHandle, count:Int):Bool;
	@:native("wgr_emitter3d_set_life")
	static function wgr_emitter3d_set_life(emitter:WgrHandle, min_seconds:Single, max_seconds:Single):Bool;
	@:native("wgr_emitter3d_prewarm")
	static function wgr_emitter3d_prewarm(emitter:WgrHandle, seconds:Single):Bool;
	@:native("wgr_emitter3d_set_spawn_box")
	static function wgr_emitter3d_set_spawn_box(emitter:WgrHandle, half_x:Single, half_y:Single, half_z:Single):Bool;
	@:native("wgr_emitter3d_set_spawn_sphere")
	static function wgr_emitter3d_set_spawn_sphere(emitter:WgrHandle, radius:Single):Bool;
	@:native("wgr_emitter3d_set_velocity")
	static function wgr_emitter3d_set_velocity(emitter:WgrHandle, x:Single, y:Single, z:Single, spread:Single, speed_variance:Single):Bool;
	@:native("wgr_emitter3d_set_gravity")
	static function wgr_emitter3d_set_gravity(emitter:WgrHandle, x:Single, y:Single, z:Single):Bool;
	@:native("wgr_emitter3d_set_drag")
	static function wgr_emitter3d_set_drag(emitter:WgrHandle, per_second:Single):Bool;
	@:native("wgr_emitter3d_set_inherit_velocity")
	static function wgr_emitter3d_set_inherit_velocity(emitter:WgrHandle, fraction:Single):Bool;
	@:native("wgr_emitter3d_set_size")
	static function wgr_emitter3d_set_size(emitter:WgrHandle, start:Single, end:Single, variance:Single):Bool;
	@:native("wgr_emitter3d_set_color")
	static function wgr_emitter3d_set_color(emitter:WgrHandle, start:WgrColor, end:WgrColor):Bool;
	@:native("wgr_emitter3d_add_size_key")
	static function wgr_emitter3d_add_size_key(emitter:WgrHandle, t:Single, size:Single):Bool;
	@:native("wgr_emitter3d_clear_size_keys")
	static function wgr_emitter3d_clear_size_keys(emitter:WgrHandle):Bool;
	@:native("wgr_emitter3d_add_color_key")
	static function wgr_emitter3d_add_color_key(emitter:WgrHandle, t:Single, color:WgrColor):Bool;
	@:native("wgr_emitter3d_clear_color_keys")
	static function wgr_emitter3d_clear_color_keys(emitter:WgrHandle):Bool;
	@:native("wgr_emitter3d_add_palette_color")
	static function wgr_emitter3d_add_palette_color(emitter:WgrHandle, color:WgrColor):Bool;
	@:native("wgr_emitter3d_clear_palette")
	static function wgr_emitter3d_clear_palette(emitter:WgrHandle):Bool;
	@:native("wgr_emitter3d_set_spin")
	static function wgr_emitter3d_set_spin(emitter:WgrHandle, min:Single, max:Single):Bool;
	@:native("wgr_emitter3d_set_stretch")
	static function wgr_emitter3d_set_stretch(emitter:WgrHandle, seconds:Single):Bool;
	@:native("wgr_emitter3d_set_alpha_mode")
	static function wgr_emitter3d_set_alpha_mode(emitter:WgrHandle, mode:CAlphaMode, cutoff:Single):Bool;
	@:native("wgr_emitter3d_set_seed")
	static function wgr_emitter3d_set_seed(emitter:WgrHandle, seed:UInt32):Bool;
	@:native("wgr_emitter3d_get_count")
	static function wgr_emitter3d_get_count(emitter:WgrHandle):Int;
	@:native("wgr_emitter3d_clear")
	static function wgr_emitter3d_clear(emitter:WgrHandle):Void;
	@:native("wgr_emitter3d_set_visible")
	static function wgr_emitter3d_set_visible(emitter:WgrHandle, visible:Bool):Bool;
	@:native("wgr_emitter3d_draw")
	static function wgr_emitter3d_draw(emitter:WgrHandle):Void;
	@:native("wgr_environment_create")
	static function wgr_environment_create(path:ConstCharStar):WgrHandle;
	@:native("wgr_environment_release")
	static function wgr_environment_release(environment:WgrHandle):Void;
	@:native("wgr_event_on")
	static function wgr_event_on(event_name:ConstCharStar, listener:EventListenerFn, user_data:VoidStar):Int;
	@:native("wgr_event_once")
	static function wgr_event_once(event_name:ConstCharStar, listener:EventListenerFn, user_data:VoidStar):Int;
	@:native("wgr_event_off")
	static function wgr_event_off(event_name:ConstCharStar, listener:EventListenerFn, user_data:VoidStar):Int;
	@:native("wgr_event_off_all")
	static function wgr_event_off_all(event_name:ConstCharStar):Int;
	@:native("wgr_event_emit")
	static function wgr_event_emit(event_name:ConstCharStar, payload:VoidStar):Int;
	@:native("wgr_event_listener_count")
	static function wgr_event_listener_count(event_name:ConstCharStar):Int;
	@:native("wgr_font_create")
	static function wgr_font_create(path:ConstCharStar):WgrHandle;
	@:native("wgr_font_release")
	static function wgr_font_release(handle:WgrHandle):Void;
	@:native("wgr_handle_get_kind")
	static function wgr_handle_get_kind(handle:WgrHandle):Int;
	@:native("wgr_input_capture_cursor")
	static function wgr_input_capture_cursor():Void;
	@:native("wgr_input_release_cursor")
	static function wgr_input_release_cursor():Void;
	@:native("wgr_input_get_mouse_position")
	static function wgr_input_get_mouse_position():CVec2;
	@:native("wgr_input_get_mouse_delta")
	static function wgr_input_get_mouse_delta():CVec2;
	@:native("wgr_input_get_mouse_wheel")
	static function wgr_input_get_mouse_wheel():Single;
	@:native("wgr_input_get_mouse_wheel_x")
	static function wgr_input_get_mouse_wheel_x():Single;
	@:native("wgr_input_get_mouse_button")
	static function wgr_input_get_mouse_button(button:Int):Int;
	@:native("wgr_input_get_mouse_state")
	static function wgr_input_get_mouse_state():CMouseState;
	@:native("wgr_input_get_key")
	static function wgr_input_get_key(key:CKeycode):Int;
	@:native("wgr_input_get_keyboard_state")
	static function wgr_input_get_keyboard_state():CKeyboardState;
	@:native("wgr_input_get_touch_count")
	static function wgr_input_get_touch_count():Int;
	@:native("wgr_input_get_touch")
	static function wgr_input_get_touch(index:Int):CTouch;
	@:native("wgr_input_get_touch_gesture")
	static function wgr_input_get_touch_gesture():CTouchGesture;
	@:native("wgr_input_is_gamepad_connected")
	static function wgr_input_is_gamepad_connected(pad:Int):Bool;
	@:native("wgr_input_get_gamepad_name")
	static function wgr_input_get_gamepad_name(pad:Int):ConstCharStar;
	@:native("wgr_input_get_gamepad_button")
	static function wgr_input_get_gamepad_button(pad:Int, button:CGamepadButton):Int;
	@:native("wgr_input_get_gamepad_axis")
	static function wgr_input_get_gamepad_axis(pad:Int, axis:CGamepadAxis):Single;
	@:native("wgr_input_set_gamepad_deadzone")
	static function wgr_input_set_gamepad_deadzone(radius:Single):Bool;
	@:native("wgr_input_is_pointer_captured")
	static function wgr_input_is_pointer_captured():Bool;
	@:native("wgr_input_set_pointer_captured")
	static function wgr_input_set_pointer_captured(captured:Bool):Void;
	@:native("wgr_input_is_keyboard_captured")
	static function wgr_input_is_keyboard_captured():Bool;
	@:native("wgr_input_set_keyboard_captured")
	static function wgr_input_set_keyboard_captured(captured:Bool):Void;
	@:native("wgr_light_create")
	static function wgr_light_create(type:CLightType):WgrHandle;
	@:native("wgr_light_destroy")
	static function wgr_light_destroy(light:WgrHandle):Void;
	@:native("wgr_light_set_color")
	static function wgr_light_set_color(light:WgrHandle, color:WgrColor):Bool;
	@:native("wgr_light_set_intensity")
	static function wgr_light_set_intensity(light:WgrHandle, intensity:Single):Bool;
	@:native("wgr_light_set_position")
	static function wgr_light_set_position(light:WgrHandle, x:Single, y:Single, z:Single):Bool;
	@:native("wgr_light_set_direction")
	static function wgr_light_set_direction(light:WgrHandle, x:Single, y:Single, z:Single):Bool;
	@:native("wgr_light_set_range")
	static function wgr_light_set_range(light:WgrHandle, range:Single):Bool;
	@:native("wgr_light_set_spot_cone")
	static function wgr_light_set_spot_cone(light:WgrHandle, inner_angle:Single, outer_angle:Single):Bool;
	@:native("wgr_light_set_enabled")
	static function wgr_light_set_enabled(light:WgrHandle, enabled:Bool):Bool;
	@:native("wgr_light_is_enabled")
	static function wgr_light_is_enabled(light:WgrHandle):Bool;
	@:native("wgr_light_get_type")
	static function wgr_light_get_type(light:WgrHandle):Int;
	@:native("wgr_light_get_color")
	static function wgr_light_get_color(light:WgrHandle):WgrColor;
	@:native("wgr_light_get_intensity")
	static function wgr_light_get_intensity(light:WgrHandle):Single;
	@:native("wgr_light_get_position")
	static function wgr_light_get_position(light:WgrHandle):CVec3;
	@:native("wgr_light_get_direction")
	static function wgr_light_get_direction(light:WgrHandle):CVec3;
	@:native("wgr_light_get_range")
	static function wgr_light_get_range(light:WgrHandle):Single;
	@:native("wgr_light_get_spot_inner_angle")
	static function wgr_light_get_spot_inner_angle(light:WgrHandle):Single;
	@:native("wgr_light_get_spot_outer_angle")
	static function wgr_light_get_spot_outer_angle(light:WgrHandle):Single;
	@:native("wgr_light_set_casts_shadows")
	static function wgr_light_set_casts_shadows(light:WgrHandle, casts:Bool):Bool;
	@:native("wgr_light_get_casts_shadows")
	static function wgr_light_get_casts_shadows(light:WgrHandle):Bool;
	@:native("wgr_light_set_shadow_distance")
	static function wgr_light_set_shadow_distance(light:WgrHandle, distance:Single):Bool;
	@:native("wgr_light_set_shadow_map_size")
	static function wgr_light_set_shadow_map_size(light:WgrHandle, size:Int):Bool;
	@:native("wgr_light_set_shadow_strength")
	static function wgr_light_set_shadow_strength(light:WgrHandle, strength:Single):Bool;
	@:native("wgr_light_set_shadow_color")
	static function wgr_light_set_shadow_color(light:WgrHandle, color:WgrColor):Bool;
	@:native("wgr_light_set_shadow_bias")
	static function wgr_light_set_shadow_bias(light:WgrHandle, constant:Single, slope:Single):Bool;
	@:native("wgr_light_get_shadow_distance")
	static function wgr_light_get_shadow_distance(light:WgrHandle):Single;
	@:native("wgr_light_get_shadow_map_size")
	static function wgr_light_get_shadow_map_size(light:WgrHandle):Int;
	@:native("wgr_light_get_shadow_strength")
	static function wgr_light_get_shadow_strength(light:WgrHandle):Single;
	@:native("wgr_light_get_shadow_color")
	static function wgr_light_get_shadow_color(light:WgrHandle):WgrColor;
	@:native("wgr_light_get_shadow_bias_constant")
	static function wgr_light_get_shadow_bias_constant(light:WgrHandle):Single;
	@:native("wgr_light_get_shadow_bias_slope")
	static function wgr_light_get_shadow_bias_slope(light:WgrHandle):Single;
	@:native("wgr_logger_set_level")
	static function wgr_logger_set_level(level:CLogLevel):Void;
	@:native("wgr_material_create")
	static function wgr_material_create(shading:CMaterialShading):WgrHandle;
	@:native("wgr_material_create_custom")
	static function wgr_material_create_custom(shader:WgrHandle):WgrHandle;
	@:native("wgr_material_get_shader")
	static function wgr_material_get_shader(material:WgrHandle):WgrHandle;
	@:native("wgr_material_release")
	static function wgr_material_release(material:WgrHandle):Void;
	@:native("wgr_material_set_shading")
	static function wgr_material_set_shading(material:WgrHandle, shading:CMaterialShading):Bool;
	@:native("wgr_material_get_shading")
	static function wgr_material_get_shading(material:WgrHandle):Int;
	@:native("wgr_material_set_alpha_mode")
	static function wgr_material_set_alpha_mode(material:WgrHandle, mode:CAlphaMode, cutoff:Single):Bool;
	@:native("wgr_material_get_alpha_mode")
	static function wgr_material_get_alpha_mode(material:WgrHandle):Int;
	@:native("wgr_material_set_double_sided")
	static function wgr_material_set_double_sided(material:WgrHandle, double_sided:Bool):Bool;
	@:native("wgr_material_is_double_sided")
	static function wgr_material_is_double_sided(material:WgrHandle):Bool;
	@:native("wgr_material_set_int")
	static function wgr_material_set_int(material:WgrHandle, name:ConstCharStar, value:Int):Bool;
	@:native("wgr_material_set_float")
	static function wgr_material_set_float(material:WgrHandle, name:ConstCharStar, value:Single):Bool;
	@:native("wgr_material_set_vec2")
	static function wgr_material_set_vec2(material:WgrHandle, name:ConstCharStar, x:Single, y:Single):Bool;
	@:native("wgr_material_set_vec3")
	static function wgr_material_set_vec3(material:WgrHandle, name:ConstCharStar, x:Single, y:Single, z:Single):Bool;
	@:native("wgr_material_set_vec4")
	static function wgr_material_set_vec4(material:WgrHandle, name:ConstCharStar, x:Single, y:Single, z:Single, w:Single):Bool;
	@:native("wgr_material_set_color")
	static function wgr_material_set_color(material:WgrHandle, name:ConstCharStar, color:WgrColor):Bool;
	@:native("wgr_material_set_texture")
	static function wgr_material_set_texture(material:WgrHandle, name:ConstCharStar, texture:WgrHandle):Bool;
	@:native("wgr_material_set_texture_sampling")
	static function wgr_material_set_texture_sampling(material:WgrHandle, name:ConstCharStar, wrap_u:CTextureWrap, wrap_v:CTextureWrap, filter:CTextureFilter):Bool;
	@:native("wgr_mesh_create")
	static function wgr_mesh_create(path:ConstCharStar):WgrHandle;
	@:native("wgr_mesh_release")
	static function wgr_mesh_release(mesh:WgrHandle):Void;
	@:native("wgr_mesh_create_plane")
	static function wgr_mesh_create_plane(width:Single, length:Single, subdivisions:Int):WgrHandle;
	@:native("wgr_mesh_create_cube")
	static function wgr_mesh_create_cube(width:Single, height:Single, length:Single):WgrHandle;
	@:native("wgr_mesh_create_sphere")
	static function wgr_mesh_create_sphere(radius:Single, rings:Int, segments:Int):WgrHandle;
	@:native("wgr_mesh_create_cylinder")
	static function wgr_mesh_create_cylinder(radius:Single, height:Single, segments:Int):WgrHandle;
	@:native("wgr_mesh_create_cone")
	static function wgr_mesh_create_cone(radius:Single, height:Single, segments:Int):WgrHandle;
	@:native("wgr_mesh_create_capsule")
	static function wgr_mesh_create_capsule(radius:Single, height:Single, rings:Int, segments:Int):WgrHandle;
	@:native("wgr_mesh_create_torus")
	static function wgr_mesh_create_torus(radius:Single, thickness:Single, rings:Int, segments:Int):WgrHandle;
	@:native("wgr_mesh_get_material_count")
	static function wgr_mesh_get_material_count(mesh:WgrHandle):Int;
	@:native("wgr_mesh_get_material")
	static function wgr_mesh_get_material(mesh:WgrHandle, slot:Int):WgrHandle;
	@:native("wgr_model_create")
	static function wgr_model_create(mesh:WgrHandle):WgrHandle;
	@:native("wgr_model_set_mesh")
	static function wgr_model_set_mesh(handle:WgrHandle, mesh:WgrHandle):Bool;
	@:native("wgr_model_set_transform")
	static function wgr_model_set_transform(handle:WgrHandle, position_x:Single, position_y:Single, position_z:Single, rotation_x:Single, rotation_y:Single, rotation_z:Single, scale_x:Single, scale_y:Single, scale_z:Single):Bool;
	@:native("wgr_model_set_position")
	static function wgr_model_set_position(handle:WgrHandle, x:Single, y:Single, z:Single):Bool;
	@:native("wgr_model_set_rotation")
	static function wgr_model_set_rotation(handle:WgrHandle, x:Single, y:Single, z:Single):Bool;
	@:native("wgr_model_set_scale")
	static function wgr_model_set_scale(handle:WgrHandle, x:Single, y:Single, z:Single):Bool;
	@:native("wgr_model_get_position")
	static function wgr_model_get_position(handle:WgrHandle):CVec3;
	@:native("wgr_model_get_rotation")
	static function wgr_model_get_rotation(handle:WgrHandle):CVec3;
	@:native("wgr_model_get_scale")
	static function wgr_model_get_scale(handle:WgrHandle):CVec3;
	@:native("wgr_model_set_tint")
	static function wgr_model_set_tint(handle:WgrHandle, color:WgrColor):Bool;
	@:native("wgr_model_set_material")
	static function wgr_model_set_material(handle:WgrHandle, slot:Int, material:WgrHandle):Bool;
	@:native("wgr_model_get_material")
	static function wgr_model_get_material(handle:WgrHandle, slot:Int):WgrHandle;
	@:native("wgr_model_set_visible")
	static function wgr_model_set_visible(handle:WgrHandle, visible:Bool):Bool;
	@:native("wgr_model_is_visible")
	static function wgr_model_is_visible(handle:WgrHandle):Bool;
	@:native("wgr_model_set_pickable")
	static function wgr_model_set_pickable(handle:WgrHandle, pickable:Bool):Bool;
	@:native("wgr_model_is_pickable")
	static function wgr_model_is_pickable(handle:WgrHandle):Bool;
	@:native("wgr_model_set_enabled")
	static function wgr_model_set_enabled(model:WgrHandle, enabled:Bool):Bool;
	@:native("wgr_model_is_enabled")
	static function wgr_model_is_enabled(model:WgrHandle):Bool;
	@:native("wgr_model_set_casts_shadow")
	static function wgr_model_set_casts_shadow(model:WgrHandle, casts:Bool):Bool;
	@:native("wgr_model_casts_shadow")
	static function wgr_model_casts_shadow(model:WgrHandle):Bool;
	@:native("wgr_model_set_receives_shadow")
	static function wgr_model_set_receives_shadow(model:WgrHandle, receives:Bool):Bool;
	@:native("wgr_model_receives_shadow")
	static function wgr_model_receives_shadow(model:WgrHandle):Bool;
	@:native("wgr_model_draw")
	static function wgr_model_draw(handle:WgrHandle):Void;
	@:native("wgr_model_destroy")
	static function wgr_model_destroy(handle:WgrHandle):Void;
	@:native("wgr_model_get_animation_count")
	static function wgr_model_get_animation_count(handle:WgrHandle):Int;
	@:native("wgr_model_set_animation")
	static function wgr_model_set_animation(handle:WgrHandle, animation_index:Int):Bool;
	@:native("wgr_model_set_animation_speed")
	static function wgr_model_set_animation_speed(handle:WgrHandle, speed:Single):Bool;
	@:native("wgr_model_set_animation_loop")
	static function wgr_model_set_animation_loop(handle:WgrHandle, loop:Bool):Bool;
	@:native("wgr_model_animate")
	static function wgr_model_animate(handle:WgrHandle, delta_seconds:Single):Bool;
	@:native("wgr_model_set_animation_time")
	static function wgr_model_set_animation_time(handle:WgrHandle, seconds:Single):Bool;
	@:native("wgr_model_get_animation_time")
	static function wgr_model_get_animation_time(handle:WgrHandle):Single;
	@:native("wgr_model_get_animation_duration")
	static function wgr_model_get_animation_duration(handle:WgrHandle, animation_index:Int):Single;
	@:native("wgr_model_is_ready")
	static function wgr_model_is_ready(handle:WgrHandle):Bool;
	@:native("wgr_pick_object")
	static function wgr_pick_object(object:WgrHandle, camera:WgrHandle, x:Single, y:Single):CPickResult;
	@:native("wgr_pick_get_stats")
	static function wgr_pick_get_stats():CPickStats;
	@:native("wgr_pick_reset_stats")
	static function wgr_pick_reset_stats():Void;
	@:native("wgr_render_begin_frame")
	static function wgr_render_begin_frame():Void;
	@:native("wgr_render_end_frame")
	static function wgr_render_end_frame():Void;
	@:native("wgr_render_clear_background")
	static function wgr_render_clear_background(color:WgrColor):Void;
	@:native("wgr_render_begin_mode_2d")
	static function wgr_render_begin_mode_2d():Void;
	@:native("wgr_render_end_mode_2d")
	static function wgr_render_end_mode_2d():Void;
	@:native("wgr_render_begin_mode_3d")
	static function wgr_render_begin_mode_3d():Void;
	@:native("wgr_render_end_mode_3d")
	static function wgr_render_end_mode_3d():Void;
	@:native("wgr_render_push_clip")
	static function wgr_render_push_clip(x:Single, y:Single, width:Single, height:Single):Void;
	@:native("wgr_render_pop_clip")
	static function wgr_render_pop_clip():Void;
	@:native("wgr_render_begin_texture")
	static function wgr_render_begin_texture(texture:WgrHandle):Bool;
	@:native("wgr_render_end_texture")
	static function wgr_render_end_texture():Void;
	@:native("wgr_render_add_effect")
	static function wgr_render_add_effect(material:WgrHandle):Bool;
	@:native("wgr_render_clear_effects")
	static function wgr_render_clear_effects():Void;
	@:native("wgr_render_effect_count")
	static function wgr_render_effect_count():Int;
	@:native("wgr_scene_create")
	static function wgr_scene_create():WgrHandle;
	@:native("wgr_scene_destroy")
	static function wgr_scene_destroy(scene:WgrHandle):Void;
	@:native("wgr_scene_add")
	static function wgr_scene_add(scene:WgrHandle, drawable:WgrHandle, layer:Int):Bool;
	@:native("wgr_scene_set_layer")
	static function wgr_scene_set_layer(scene:WgrHandle, drawable:WgrHandle, layer:Int):Bool;
	@:native("wgr_scene_remove")
	static function wgr_scene_remove(scene:WgrHandle, drawable:WgrHandle):Bool;
	@:native("wgr_scene_clear")
	static function wgr_scene_clear(scene:WgrHandle):Void;
	@:native("wgr_scene_set_clip")
	static function wgr_scene_set_clip(scene:WgrHandle, layer:Int, x:Single, y:Single, width:Single, height:Single):Bool;
	@:native("wgr_scene_set_active_camera")
	static function wgr_scene_set_active_camera(scene:WgrHandle, camera:WgrHandle):Void;
	@:native("wgr_scene_set_ambient")
	static function wgr_scene_set_ambient(scene:WgrHandle, color:WgrColor, intensity:Single):Bool;
	@:native("wgr_scene_set_environment")
	static function wgr_scene_set_environment(scene:WgrHandle, environment:WgrHandle, intensity:Single, rotation:Single):Bool;
	@:native("wgr_scene_set_background")
	static function wgr_scene_set_background(scene:WgrHandle, environment:WgrHandle, blur:Single):Bool;
	@:native("wgr_scene_set_tonemap")
	static function wgr_scene_set_tonemap(scene:WgrHandle, tonemap:CTonemap, exposure:Single):Bool;
	@:native("wgr_scene_draw")
	static function wgr_scene_draw(scene:WgrHandle):Void;
	@:native("wgr_scene_set_interactive")
	static function wgr_scene_set_interactive(scene:WgrHandle, interactive:Bool):Bool;
	@:native("wgr_scene_set_culling")
	static function wgr_scene_set_culling(scene:WgrHandle, culling:Bool):Bool;
	@:native("wgr_scene_is_culling")
	static function wgr_scene_is_culling(scene:WgrHandle):Bool;
	@:native("wgr_scene_is_interactive")
	static function wgr_scene_is_interactive(scene:WgrHandle):Bool;
	@:native("wgr_scene_get_hovered")
	static function wgr_scene_get_hovered(scene:WgrHandle):WgrHandle;
	@:native("wgr_scene_get_hover")
	static function wgr_scene_get_hover(scene:WgrHandle, object:WgrHandle):Int;
	@:native("wgr_scene_get_press")
	static function wgr_scene_get_press(scene:WgrHandle, object:WgrHandle):Int;
	@:native("wgr_scene_is_clicked")
	static function wgr_scene_is_clicked(scene:WgrHandle, object:WgrHandle):Bool;
	@:native("wgr_scene_pick")
	static function wgr_scene_pick(scene:WgrHandle, camera:WgrHandle, mouse_x:Single, mouse_y:Single):CPickResult;
	@:native("wgr_shader_create")
	static function wgr_shader_create(path:ConstCharStar):WgrHandle;
	@:native("wgr_shader_release")
	static function wgr_shader_release(shader:WgrHandle):Void;
	@:native("wgr_shape2d_draw_rectangle")
	static function wgr_shape2d_draw_rectangle(x:Single, y:Single, width:Single, height:Single, color:WgrColor):Void;
	@:native("wgr_shape2d_draw_rectangle_lines")
	static function wgr_shape2d_draw_rectangle_lines(x:Single, y:Single, width:Single, height:Single, color:WgrColor):Void;
	@:native("wgr_shape2d_draw_line")
	static function wgr_shape2d_draw_line(start_x:Single, start_y:Single, end_x:Single, end_y:Single, color:WgrColor):Void;
	@:native("wgr_shape2d_draw_circle")
	static function wgr_shape2d_draw_circle(center_x:Single, center_y:Single, radius:Single, color:WgrColor):Void;
	@:native("wgr_shape2d_draw_circle_lines")
	static function wgr_shape2d_draw_circle_lines(center_x:Single, center_y:Single, radius:Single, color:WgrColor):Void;
	@:native("wgr_shape2d_draw_triangle")
	static function wgr_shape2d_draw_triangle(x0:Single, y0:Single, x1:Single, y1:Single, x2:Single, y2:Single, color:WgrColor):Void;
	@:native("wgr_shape2d_draw_rounded_rectangle")
	static function wgr_shape2d_draw_rounded_rectangle(x:Single, y:Single, width:Single, height:Single, r_top_left:Single, r_top_right:Single, r_bottom_right:Single, r_bottom_left:Single, color:WgrColor):Void;
	@:native("wgr_shape2d_draw_border")
	static function wgr_shape2d_draw_border(x:Single, y:Single, width:Single, height:Single, left:Single, top:Single, right:Single, bottom:Single, r_top_left:Single, r_top_right:Single, r_bottom_right:Single, r_bottom_left:Single, color:WgrColor):Void;
	@:native("wgr_shape2d_create")
	static function wgr_shape2d_create():WgrHandle;
	@:native("wgr_shape2d_destroy")
	static function wgr_shape2d_destroy(shape:WgrHandle):Void;
	@:native("wgr_shape2d_set_rectangle")
	static function wgr_shape2d_set_rectangle(shape:WgrHandle, width:Single, height:Single, corner_radius:Single):Bool;
	@:native("wgr_shape2d_set_circle")
	static function wgr_shape2d_set_circle(shape:WgrHandle, radius:Single):Bool;
	@:native("wgr_shape2d_set_line")
	static function wgr_shape2d_set_line(shape:WgrHandle, x0:Single, y0:Single, x1:Single, y1:Single, thickness:Single):Bool;
	@:native("wgr_shape2d_set_transform")
	static function wgr_shape2d_set_transform(shape:WgrHandle, x:Single, y:Single, rotation:Single, scale_x:Single, scale_y:Single):Bool;
	@:native("wgr_shape2d_set_position")
	static function wgr_shape2d_set_position(shape:WgrHandle, x:Single, y:Single):Bool;
	@:native("wgr_shape2d_set_rotation")
	static function wgr_shape2d_set_rotation(shape:WgrHandle, angle:Single):Bool;
	@:native("wgr_shape2d_set_scale")
	static function wgr_shape2d_set_scale(shape:WgrHandle, x:Single, y:Single):Bool;
	@:native("wgr_shape2d_get_position")
	static function wgr_shape2d_get_position(shape:WgrHandle):CVec2;
	@:native("wgr_shape2d_get_rotation")
	static function wgr_shape2d_get_rotation(shape:WgrHandle):Single;
	@:native("wgr_shape2d_get_scale")
	static function wgr_shape2d_get_scale(shape:WgrHandle):CVec2;
	@:native("wgr_shape2d_set_pivot")
	static function wgr_shape2d_set_pivot(shape:WgrHandle, x:Single, y:Single):Bool;
	@:native("wgr_shape2d_set_outline")
	static function wgr_shape2d_set_outline(shape:WgrHandle, thickness:Single):Bool;
	@:native("wgr_shape2d_set_color")
	static function wgr_shape2d_set_color(shape:WgrHandle, color:WgrColor):Bool;
	@:native("wgr_shape2d_set_visible")
	static function wgr_shape2d_set_visible(shape:WgrHandle, visible:Bool):Bool;
	@:native("wgr_shape2d_is_visible")
	static function wgr_shape2d_is_visible(shape:WgrHandle):Bool;
	@:native("wgr_shape2d_set_pickable")
	static function wgr_shape2d_set_pickable(shape:WgrHandle, pickable:Bool):Bool;
	@:native("wgr_shape2d_is_pickable")
	static function wgr_shape2d_is_pickable(shape:WgrHandle):Bool;
	@:native("wgr_shape2d_set_enabled")
	static function wgr_shape2d_set_enabled(shape:WgrHandle, enabled:Bool):Bool;
	@:native("wgr_shape2d_is_enabled")
	static function wgr_shape2d_is_enabled(shape:WgrHandle):Bool;
	@:native("wgr_shape2d_draw")
	static function wgr_shape2d_draw(shape:WgrHandle):Void;
	@:native("wgr_shape3d_draw_line")
	static function wgr_shape3d_draw_line(x0:Single, y0:Single, z0:Single, x1:Single, y1:Single, z1:Single, color:WgrColor):Void;
	@:native("wgr_shape3d_draw_cube")
	static function wgr_shape3d_draw_cube(cx:Single, cy:Single, cz:Single, width:Single, height:Single, length:Single, color:WgrColor):Void;
	@:native("wgr_shape3d_draw_cube_wires")
	static function wgr_shape3d_draw_cube_wires(cx:Single, cy:Single, cz:Single, width:Single, height:Single, length:Single, color:WgrColor):Void;
	@:native("wgr_shape3d_draw_sphere")
	static function wgr_shape3d_draw_sphere(cx:Single, cy:Single, cz:Single, radius:Single, color:WgrColor):Void;
	@:native("wgr_shape3d_draw_grid")
	static function wgr_shape3d_draw_grid(slices:Int, spacing:Single, color:WgrColor):Void;
	@:native("wgr_shape3d_draw_rectangle")
	static function wgr_shape3d_draw_rectangle(cx:Single, cy:Single, cz:Single, width:Single, height:Single, rx:Single, ry:Single, rz:Single, color:WgrColor):Void;
	@:native("wgr_shape3d_draw_circle")
	static function wgr_shape3d_draw_circle(cx:Single, cy:Single, cz:Single, radius:Single, rx:Single, ry:Single, rz:Single, color:WgrColor):Void;
	@:native("wgr_shape3d_create")
	static function wgr_shape3d_create():WgrHandle;
	@:native("wgr_shape3d_destroy")
	static function wgr_shape3d_destroy(shape:WgrHandle):Void;
	@:native("wgr_shape3d_set_cube")
	static function wgr_shape3d_set_cube(shape:WgrHandle, width:Single, height:Single, length:Single):Bool;
	@:native("wgr_shape3d_set_sphere")
	static function wgr_shape3d_set_sphere(shape:WgrHandle, radius:Single):Bool;
	@:native("wgr_shape3d_set_rectangle")
	static function wgr_shape3d_set_rectangle(shape:WgrHandle, width:Single, height:Single):Bool;
	@:native("wgr_shape3d_set_circle")
	static function wgr_shape3d_set_circle(shape:WgrHandle, radius:Single):Bool;
	@:native("wgr_shape3d_set_line")
	static function wgr_shape3d_set_line(shape:WgrHandle, x0:Single, y0:Single, z0:Single, x1:Single, y1:Single, z1:Single):Bool;
	@:native("wgr_shape3d_set_line_strip")
	static function wgr_shape3d_set_line_strip(shape:WgrHandle):Bool;
	@:native("wgr_shape3d_add_point")
	static function wgr_shape3d_add_point(shape:WgrHandle, x:Single, y:Single, z:Single):Bool;
	@:native("wgr_shape3d_get_point_count")
	static function wgr_shape3d_get_point_count(shape:WgrHandle):Int;
	@:native("wgr_shape3d_set_transform")
	static function wgr_shape3d_set_transform(shape:WgrHandle, position_x:Single, position_y:Single, position_z:Single, rotation_x:Single, rotation_y:Single, rotation_z:Single, scale_x:Single, scale_y:Single, scale_z:Single):Bool;
	@:native("wgr_shape3d_set_position")
	static function wgr_shape3d_set_position(handle:WgrHandle, x:Single, y:Single, z:Single):Bool;
	@:native("wgr_shape3d_set_rotation")
	static function wgr_shape3d_set_rotation(handle:WgrHandle, x:Single, y:Single, z:Single):Bool;
	@:native("wgr_shape3d_set_scale")
	static function wgr_shape3d_set_scale(handle:WgrHandle, x:Single, y:Single, z:Single):Bool;
	@:native("wgr_shape3d_get_position")
	static function wgr_shape3d_get_position(handle:WgrHandle):CVec3;
	@:native("wgr_shape3d_get_rotation")
	static function wgr_shape3d_get_rotation(handle:WgrHandle):CVec3;
	@:native("wgr_shape3d_get_scale")
	static function wgr_shape3d_get_scale(handle:WgrHandle):CVec3;
	@:native("wgr_shape3d_set_color")
	static function wgr_shape3d_set_color(shape:WgrHandle, color:WgrColor):Bool;
	@:native("wgr_shape3d_set_visible")
	static function wgr_shape3d_set_visible(shape:WgrHandle, visible:Bool):Bool;
	@:native("wgr_shape3d_is_visible")
	static function wgr_shape3d_is_visible(shape:WgrHandle):Bool;
	@:native("wgr_shape3d_set_pickable")
	static function wgr_shape3d_set_pickable(shape:WgrHandle, pickable:Bool):Bool;
	@:native("wgr_shape3d_is_pickable")
	static function wgr_shape3d_is_pickable(shape:WgrHandle):Bool;
	@:native("wgr_shape3d_set_enabled")
	static function wgr_shape3d_set_enabled(shape:WgrHandle, enabled:Bool):Bool;
	@:native("wgr_shape3d_is_enabled")
	static function wgr_shape3d_is_enabled(shape:WgrHandle):Bool;
	@:native("wgr_shape3d_draw")
	static function wgr_shape3d_draw(shape:WgrHandle):Void;
	@:native("wgr_sound_create")
	static function wgr_sound_create(audio:WgrHandle):WgrHandle;
	@:native("wgr_sound_set_audio")
	static function wgr_sound_set_audio(handle:WgrHandle, audio:WgrHandle):Bool;
	@:native("wgr_sound_destroy")
	static function wgr_sound_destroy(handle:WgrHandle):Void;
	@:native("wgr_sound_play")
	static function wgr_sound_play(handle:WgrHandle):Bool;
	@:native("wgr_sound_pause")
	static function wgr_sound_pause(handle:WgrHandle):Bool;
	@:native("wgr_sound_resume")
	static function wgr_sound_resume(handle:WgrHandle):Bool;
	@:native("wgr_sound_stop")
	static function wgr_sound_stop(handle:WgrHandle):Bool;
	@:native("wgr_sound_set_loop")
	static function wgr_sound_set_loop(handle:WgrHandle, loop:Bool):Bool;
	@:native("wgr_sound_set_volume")
	static function wgr_sound_set_volume(handle:WgrHandle, volume:Single):Bool;
	@:native("wgr_sound_set_pitch")
	static function wgr_sound_set_pitch(handle:WgrHandle, pitch:Single):Bool;
	@:native("wgr_sound_set_pan")
	static function wgr_sound_set_pan(handle:WgrHandle, pan:Single):Bool;
	@:native("wgr_sound_is_playing")
	static function wgr_sound_is_playing(handle:WgrHandle):Bool;
	@:native("wgr_sprite2d_create")
	static function wgr_sprite2d_create(texture:WgrHandle):WgrHandle;
	@:native("wgr_sprite2d_destroy")
	static function wgr_sprite2d_destroy(sprite:WgrHandle):Void;
	@:native("wgr_sprite2d_set_texture")
	static function wgr_sprite2d_set_texture(sprite:WgrHandle, texture:WgrHandle):Bool;
	@:native("wgr_sprite2d_set_source")
	static function wgr_sprite2d_set_source(sprite:WgrHandle, x:Single, y:Single, width:Single, height:Single):Bool;
	@:native("wgr_sprite2d_set_transform")
	static function wgr_sprite2d_set_transform(sprite:WgrHandle, x:Single, y:Single, rotation:Single, scale_x:Single, scale_y:Single):Bool;
	@:native("wgr_sprite2d_set_position")
	static function wgr_sprite2d_set_position(sprite:WgrHandle, x:Single, y:Single):Bool;
	@:native("wgr_sprite2d_set_rotation")
	static function wgr_sprite2d_set_rotation(sprite:WgrHandle, angle:Single):Bool;
	@:native("wgr_sprite2d_set_scale")
	static function wgr_sprite2d_set_scale(sprite:WgrHandle, x:Single, y:Single):Bool;
	@:native("wgr_sprite2d_get_position")
	static function wgr_sprite2d_get_position(sprite:WgrHandle):CVec2;
	@:native("wgr_sprite2d_get_rotation")
	static function wgr_sprite2d_get_rotation(sprite:WgrHandle):Single;
	@:native("wgr_sprite2d_get_scale")
	static function wgr_sprite2d_get_scale(sprite:WgrHandle):CVec2;
	@:native("wgr_sprite2d_set_size")
	static function wgr_sprite2d_set_size(sprite:WgrHandle, width:Single, height:Single):Bool;
	@:native("wgr_sprite2d_set_pivot")
	static function wgr_sprite2d_set_pivot(sprite:WgrHandle, x:Single, y:Single):Bool;
	@:native("wgr_sprite2d_set_nine_slice")
	static function wgr_sprite2d_set_nine_slice(sprite:WgrHandle, left:Single, top:Single, right:Single, bottom:Single):Bool;
	@:native("wgr_sprite2d_set_tint")
	static function wgr_sprite2d_set_tint(sprite:WgrHandle, color:WgrColor):Bool;
	@:native("wgr_sprite2d_set_visible")
	static function wgr_sprite2d_set_visible(sprite:WgrHandle, visible:Bool):Bool;
	@:native("wgr_sprite2d_is_visible")
	static function wgr_sprite2d_is_visible(sprite:WgrHandle):Bool;
	@:native("wgr_sprite2d_set_pickable")
	static function wgr_sprite2d_set_pickable(sprite:WgrHandle, pickable:Bool):Bool;
	@:native("wgr_sprite2d_is_pickable")
	static function wgr_sprite2d_is_pickable(sprite:WgrHandle):Bool;
	@:native("wgr_sprite2d_set_enabled")
	static function wgr_sprite2d_set_enabled(sprite:WgrHandle, enabled:Bool):Bool;
	@:native("wgr_sprite2d_is_enabled")
	static function wgr_sprite2d_is_enabled(sprite:WgrHandle):Bool;
	@:native("wgr_sprite2d_set_alpha_mode")
	static function wgr_sprite2d_set_alpha_mode(sprite:WgrHandle, mode:CAlphaMode, cutoff:Single):Bool;
	@:native("wgr_sprite2d_get_alpha_mode")
	static function wgr_sprite2d_get_alpha_mode(sprite:WgrHandle):Int;
	@:native("wgr_sprite2d_set_material")
	static function wgr_sprite2d_set_material(sprite:WgrHandle, material:WgrHandle):Bool;
	@:native("wgr_sprite2d_get_material")
	static function wgr_sprite2d_get_material(sprite:WgrHandle):WgrHandle;
	@:native("wgr_sprite2d_set_pick_alpha_test")
	static function wgr_sprite2d_set_pick_alpha_test(sprite:WgrHandle, enable:Bool, threshold:Single):Bool;
	@:native("wgr_sprite2d_draw")
	static function wgr_sprite2d_draw(sprite:WgrHandle):Void;
	@:native("wgr_sprite3d_create")
	static function wgr_sprite3d_create(texture:WgrHandle):WgrHandle;
	@:native("wgr_sprite3d_set_texture")
	static function wgr_sprite3d_set_texture(handle:WgrHandle, texture:WgrHandle):Bool;
	@:native("wgr_sprite3d_set_transform")
	static function wgr_sprite3d_set_transform(handle:WgrHandle, position_x:Single, position_y:Single, position_z:Single, rotation_x:Single, rotation_y:Single, rotation_z:Single, scale_x:Single, scale_y:Single, scale_z:Single):Bool;
	@:native("wgr_sprite3d_set_position")
	static function wgr_sprite3d_set_position(handle:WgrHandle, x:Single, y:Single, z:Single):Bool;
	@:native("wgr_sprite3d_set_rotation")
	static function wgr_sprite3d_set_rotation(handle:WgrHandle, x:Single, y:Single, z:Single):Bool;
	@:native("wgr_sprite3d_set_scale")
	static function wgr_sprite3d_set_scale(handle:WgrHandle, x:Single, y:Single, z:Single):Bool;
	@:native("wgr_sprite3d_set_size")
	static function wgr_sprite3d_set_size(handle:WgrHandle, size:Single):Bool;
	@:native("wgr_sprite3d_set_extent")
	static function wgr_sprite3d_set_extent(handle:WgrHandle, width:Single, height:Single):Bool;
	@:native("wgr_sprite3d_set_source")
	static function wgr_sprite3d_set_source(handle:WgrHandle, x:Single, y:Single, width:Single, height:Single):Bool;
	@:native("wgr_sprite3d_set_pivot")
	static function wgr_sprite3d_set_pivot(handle:WgrHandle, x:Single, y:Single):Bool;
	@:native("wgr_sprite3d_set_facing")
	static function wgr_sprite3d_set_facing(handle:WgrHandle, facing:CSprite3DFacing):Bool;
	@:native("wgr_sprite3d_get_position")
	static function wgr_sprite3d_get_position(handle:WgrHandle):CVec3;
	@:native("wgr_sprite3d_get_rotation")
	static function wgr_sprite3d_get_rotation(handle:WgrHandle):CVec3;
	@:native("wgr_sprite3d_get_scale")
	static function wgr_sprite3d_get_scale(handle:WgrHandle):CVec3;
	@:native("wgr_sprite3d_set_tint")
	static function wgr_sprite3d_set_tint(handle:WgrHandle, color:WgrColor):Bool;
	@:native("wgr_sprite3d_set_visible")
	static function wgr_sprite3d_set_visible(handle:WgrHandle, visible:Bool):Bool;
	@:native("wgr_sprite3d_is_visible")
	static function wgr_sprite3d_is_visible(handle:WgrHandle):Bool;
	@:native("wgr_sprite3d_set_pickable")
	static function wgr_sprite3d_set_pickable(handle:WgrHandle, pickable:Bool):Bool;
	@:native("wgr_sprite3d_is_pickable")
	static function wgr_sprite3d_is_pickable(handle:WgrHandle):Bool;
	@:native("wgr_sprite3d_set_enabled")
	static function wgr_sprite3d_set_enabled(sprite:WgrHandle, enabled:Bool):Bool;
	@:native("wgr_sprite3d_is_enabled")
	static function wgr_sprite3d_is_enabled(sprite:WgrHandle):Bool;
	@:native("wgr_sprite3d_set_alpha_mode")
	static function wgr_sprite3d_set_alpha_mode(handle:WgrHandle, mode:CAlphaMode, cutoff:Single):Bool;
	@:native("wgr_sprite3d_get_alpha_mode")
	static function wgr_sprite3d_get_alpha_mode(handle:WgrHandle):Int;
	@:native("wgr_sprite3d_set_material")
	static function wgr_sprite3d_set_material(handle:WgrHandle, material:WgrHandle):Bool;
	@:native("wgr_sprite3d_get_material")
	static function wgr_sprite3d_get_material(handle:WgrHandle):WgrHandle;
	@:native("wgr_sprite3d_set_pick_alpha_test")
	static function wgr_sprite3d_set_pick_alpha_test(handle:WgrHandle, enable:Bool, threshold:Single):Bool;
	@:native("wgr_sprite3d_draw")
	static function wgr_sprite3d_draw(handle:WgrHandle):Void;
	@:native("wgr_sprite3d_destroy")
	static function wgr_sprite3d_destroy(handle:WgrHandle):Void;
	@:native("wgr_text_set_default_font")
	static function wgr_text_set_default_font(font:WgrHandle):Bool;
	@:native("wgr_text_get_default_font")
	static function wgr_text_get_default_font():WgrHandle;
	@:native("wgr_text_draw_fps")
	static function wgr_text_draw_fps(x:Int, y:Int):Void;
	@:native("wgr_text_draw_fps_ex")
	static function wgr_text_draw_fps_ex(font:WgrHandle, x:Single, y:Single, size:Single, color:WgrColor):Void;
	@:native("wgr_text_draw")
	static function wgr_text_draw(text:ConstCharStar, x:Int, y:Int, font_size:Int, color:WgrColor):Void;
	@:native("wgr_text_measure")
	static function wgr_text_measure(text:ConstCharStar, font_size:Int):Int;
	@:native("wgr_text_draw_ex")
	static function wgr_text_draw_ex(font:WgrHandle, text:ConstCharStar, x:Single, y:Single, size:Single, color:WgrColor):Void;
	@:native("wgr_text_measure_ex")
	static function wgr_text_measure_ex(font:WgrHandle, text:ConstCharStar, size:Single):CVec2;
	@:native("wgr_text_draw_n")
	static function wgr_text_draw_n(font:WgrHandle, text:ConstCharStar, length:Int, x:Single, y:Single, size:Single, color:WgrColor):Void;
	@:native("wgr_text_measure_n")
	static function wgr_text_measure_n(font:WgrHandle, text:ConstCharStar, length:Int, size:Single):CVec2;
	@:native("wgr_text2d_create")
	static function wgr_text2d_create(font:WgrHandle):WgrHandle;
	@:native("wgr_text2d_set_font")
	static function wgr_text2d_set_font(handle:WgrHandle, font:WgrHandle):Bool;
	@:native("wgr_text2d_set_text")
	static function wgr_text2d_set_text(handle:WgrHandle, text:ConstCharStar):Bool;
	@:native("wgr_text2d_set_position")
	static function wgr_text2d_set_position(handle:WgrHandle, x:Single, y:Single):Bool;
	@:native("wgr_text2d_get_position")
	static function wgr_text2d_get_position(handle:WgrHandle):CVec2;
	@:native("wgr_text2d_set_size")
	static function wgr_text2d_set_size(handle:WgrHandle, size:Single):Bool;
	@:native("wgr_text2d_set_color")
	static function wgr_text2d_set_color(handle:WgrHandle, color:WgrColor):Bool;
	@:native("wgr_text2d_set_visible")
	static function wgr_text2d_set_visible(handle:WgrHandle, visible:Bool):Bool;
	@:native("wgr_text2d_is_visible")
	static function wgr_text2d_is_visible(handle:WgrHandle):Bool;
	@:native("wgr_text2d_set_pickable")
	static function wgr_text2d_set_pickable(handle:WgrHandle, pickable:Bool):Bool;
	@:native("wgr_text2d_is_pickable")
	static function wgr_text2d_is_pickable(handle:WgrHandle):Bool;
	@:native("wgr_text2d_set_enabled")
	static function wgr_text2d_set_enabled(text:WgrHandle, enabled:Bool):Bool;
	@:native("wgr_text2d_is_enabled")
	static function wgr_text2d_is_enabled(text:WgrHandle):Bool;
	@:native("wgr_text2d_set_align")
	static function wgr_text2d_set_align(handle:WgrHandle, horizontal:CTextAlign, vertical:CTextAlign):Bool;
	@:native("wgr_text2d_set_max_width")
	static function wgr_text2d_set_max_width(handle:WgrHandle, width:Single):Bool;
	@:native("wgr_text2d_measure_width")
	static function wgr_text2d_measure_width(handle:WgrHandle):Single;
	@:native("wgr_text2d_measure_height")
	static function wgr_text2d_measure_height(handle:WgrHandle):Single;
	@:native("wgr_text2d_draw")
	static function wgr_text2d_draw(handle:WgrHandle):Void;
	@:native("wgr_text2d_destroy")
	static function wgr_text2d_destroy(handle:WgrHandle):Void;
	@:native("wgr_text3d_create")
	static function wgr_text3d_create(font:WgrHandle):WgrHandle;
	@:native("wgr_text3d_destroy")
	static function wgr_text3d_destroy(text:WgrHandle):Void;
	@:native("wgr_text3d_set_font")
	static function wgr_text3d_set_font(text:WgrHandle, font:WgrHandle):Bool;
	@:native("wgr_text3d_set_text")
	static function wgr_text3d_set_text(text:WgrHandle, string:ConstCharStar):Bool;
	@:native("wgr_text3d_set_size")
	static function wgr_text3d_set_size(text:WgrHandle, size:Single):Bool;
	@:native("wgr_text3d_set_align")
	static function wgr_text3d_set_align(text:WgrHandle, horizontal:CTextAlign, vertical:CTextAlign):Bool;
	@:native("wgr_text3d_set_max_width")
	static function wgr_text3d_set_max_width(text:WgrHandle, width:Single):Bool;
	@:native("wgr_text3d_set_transform")
	static function wgr_text3d_set_transform(text:WgrHandle, x:Single, y:Single, z:Single, rotation_x:Single, rotation_y:Single, rotation_z:Single):Bool;
	@:native("wgr_text3d_set_position")
	static function wgr_text3d_set_position(text:WgrHandle, x:Single, y:Single, z:Single):Bool;
	@:native("wgr_text3d_set_rotation")
	static function wgr_text3d_set_rotation(text:WgrHandle, x:Single, y:Single, z:Single):Bool;
	@:native("wgr_text3d_get_position")
	static function wgr_text3d_get_position(text:WgrHandle):CVec3;
	@:native("wgr_text3d_get_rotation")
	static function wgr_text3d_get_rotation(text:WgrHandle):CVec3;
	@:native("wgr_text3d_set_facing")
	static function wgr_text3d_set_facing(text:WgrHandle, facing:CSprite3DFacing):Bool;
	@:native("wgr_text3d_set_color")
	static function wgr_text3d_set_color(text:WgrHandle, color:WgrColor):Bool;
	@:native("wgr_text3d_set_visible")
	static function wgr_text3d_set_visible(text:WgrHandle, visible:Bool):Bool;
	@:native("wgr_text3d_is_visible")
	static function wgr_text3d_is_visible(text:WgrHandle):Bool;
	@:native("wgr_text3d_set_pickable")
	static function wgr_text3d_set_pickable(text:WgrHandle, pickable:Bool):Bool;
	@:native("wgr_text3d_is_pickable")
	static function wgr_text3d_is_pickable(text:WgrHandle):Bool;
	@:native("wgr_text3d_set_enabled")
	static function wgr_text3d_set_enabled(text:WgrHandle, enabled:Bool):Bool;
	@:native("wgr_text3d_is_enabled")
	static function wgr_text3d_is_enabled(text:WgrHandle):Bool;
	@:native("wgr_text3d_get_size")
	static function wgr_text3d_get_size(text:WgrHandle):CVec2;
	@:native("wgr_text3d_draw")
	static function wgr_text3d_draw(text:WgrHandle):Void;
	@:native("wgr_text_draw_3d")
	static function wgr_text_draw_3d(font:WgrHandle, text:ConstCharStar, x:Single, y:Single, z:Single, size:Single, color:WgrColor):Void;
	@:native("wgr_texture_get_default")
	static function wgr_texture_get_default():WgrHandle;
	@:native("wgr_texture_get_placeholder")
	static function wgr_texture_get_placeholder():WgrHandle;
	@:native("wgr_texture_set_placeholder")
	static function wgr_texture_set_placeholder(texture:WgrHandle):Bool;
	@:native("wgr_texture_create")
	static function wgr_texture_create(path:ConstCharStar):WgrHandle;
	@:native("wgr_texture_create_target")
	static function wgr_texture_create_target(width:Int, height:Int):WgrHandle;
	@:native("wgr_texture_set_sampling")
	static function wgr_texture_set_sampling(texture:WgrHandle, wrap_u:CTextureWrap, wrap_v:CTextureWrap, filter:CTextureFilter):Bool;
	@:native("wgr_texture_get_size")
	static function wgr_texture_get_size(handle:WgrHandle):CVec2;
	@:native("wgr_texture_draw")
	static function wgr_texture_draw(texture:WgrHandle, x:Single, y:Single, width:Single, height:Single, tint:WgrColor):Void;
	@:native("wgr_texture_draw_ex")
	static function wgr_texture_draw_ex(texture:WgrHandle, source_x:Single, source_y:Single, source_width:Single, source_height:Single, x:Single, y:Single, width:Single, height:Single, tint:WgrColor):Void;
	@:native("wgr_texture_draw_nine_slice")
	static function wgr_texture_draw_nine_slice(texture:WgrHandle, source_x:Single, source_y:Single, source_width:Single, source_height:Single, left:Single, top:Single, right:Single, bottom:Single, x:Single, y:Single, width:Single, height:Single, tint:WgrColor):Void;
	@:native("wgr_texture_release")
	static function wgr_texture_release(handle:WgrHandle):Void;
	@:native("wgr_version_major")
	static function wgr_version_major():Int;
	@:native("wgr_version_minor")
	static function wgr_version_minor():Int;
	@:native("wgr_version_patch")
	static function wgr_version_patch():Int;
	@:native("wgr_version_label")
	static function wgr_version_label():ConstCharStar;
	@:native("wgr_version_number")
	static function wgr_version_number():UInt32;
	@:native("wgr_version_string")
	static function wgr_version_string():ConstCharStar;
	@:native("wgr_window_set_title")
	static function wgr_window_set_title(title:ConstCharStar):Void;
	@:native("wgr_window_close_requested")
	static function wgr_window_close_requested():Int;
	@:native("wgr_window_get_screen_size")
	static function wgr_window_get_screen_size():CVec2;
	@:native("wgr_window_set_size")
	static function wgr_window_set_size(width:Int, height:Int):Bool;
	@:native("wgr_window_set_position")
	static function wgr_window_set_position(x:Int, y:Int):Bool;
	@:native("wgr_window_get_position")
	static function wgr_window_get_position():CVec2;
	@:native("wgr_window_has_fullscreen")
	static function wgr_window_has_fullscreen():Bool;
	@:native("wgr_window_request_fullscreen")
	static function wgr_window_request_fullscreen(fullscreen:Bool):Bool;
	@:native("wgr_window_is_fullscreen")
	static function wgr_window_is_fullscreen():Bool;
	@:native("wgr_window_set_visible")
	static function wgr_window_set_visible(visible:Bool):Bool;
	@:native("wgr_window_is_visible")
	static function wgr_window_is_visible():Bool;
	@:native("wgr_window_is_focused")
	static function wgr_window_is_focused():Bool;
	@:native("wgr_window_get_monitor_count")
	static function wgr_window_get_monitor_count():Int;
	@:native("wgr_window_get_monitor")
	static function wgr_window_get_monitor():Int;
	@:native("wgr_window_set_monitor")
	static function wgr_window_set_monitor(monitor:Int):Bool;
	@:native("wgr_window_get_monitor_size")
	static function wgr_window_get_monitor_size(monitor:Int):CVec2;
	@:native("wgr_window_get_monitor_position")
	static function wgr_window_get_monitor_position(monitor:Int):CVec2;
	@:native("wgr_window_get_monitor_name")
	static function wgr_window_get_monitor_name(monitor:Int):ConstCharStar;

	/** The varargs logger, fixed at one `%s` — enough for a Haxe string. **/
	@:native("wgr_logger_message")
	static function wgr_logger_message(level:CLogLevel, format:ConstCharStar, text:ConstCharStar):Void;

	/** The same, with the call site the WGR_LOG_* macros would have filled in. **/
	@:native("wgr_logger_message_source")
	static function wgr_logger_message_source(level:CLogLevel, sourceFile:ConstCharStar, sourceLine:Int,
		format:ConstCharStar, text:ConstCharStar):Void;
}
