package wgr;

// wgr_keys.h — generated by tools/gen_keys.py

/**
	wgrender's key codes (`WGR_KEY_*`, wgr_keys.h). The numbers currently follow the
	GLFW/sokol layout, but that is an implementation detail: code to the names.
	`KeyCheck` below asserts them against the header at C++ compile time.
**/
enum abstract Key(Int) from Int to Int {
	var Space = 32;
	var Apostrophe = 39;
	var Comma = 44;
	var Minus = 45;
	var Period = 46;
	var Slash = 47;
	var Digit0 = 48;
	var Digit1 = 49;
	var Digit2 = 50;
	var Digit3 = 51;
	var Digit4 = 52;
	var Digit5 = 53;
	var Digit6 = 54;
	var Digit7 = 55;
	var Digit8 = 56;
	var Digit9 = 57;
	var Semicolon = 59;
	var Equal = 61;
	var A = 65;
	var B = 66;
	var C = 67;
	var D = 68;
	var E = 69;
	var F = 70;
	var G = 71;
	var H = 72;
	var I = 73;
	var J = 74;
	var K = 75;
	var L = 76;
	var M = 77;
	var N = 78;
	var O = 79;
	var P = 80;
	var Q = 81;
	var R = 82;
	var S = 83;
	var T = 84;
	var U = 85;
	var V = 86;
	var W = 87;
	var X = 88;
	var Y = 89;
	var Z = 90;
	var LeftBracket = 91;
	var Backslash = 92;
	var RightBracket = 93;
	var GraveAccent = 96;
	var Escape = 256;
	var Enter = 257;
	var Tab = 258;
	var Backspace = 259;
	var Insert = 260;
	var Delete = 261;
	var Right = 262;
	var Left = 263;
	var Down = 264;
	var Up = 265;
	var PageUp = 266;
	var PageDown = 267;
	var Home = 268;
	var End = 269;
	var CapsLock = 280;
	var F1 = 290;
	var F2 = 291;
	var F3 = 292;
	var F4 = 293;
	var F5 = 294;
	var F6 = 295;
	var F7 = 296;
	var F8 = 297;
	var F9 = 298;
	var F10 = 299;
	var F11 = 300;
	var F12 = 301;
	var LeftShift = 340;
	var LeftControl = 341;
	var LeftAlt = 342;
	var LeftSuper = 343;
	var RightShift = 344;
	var RightControl = 345;
	var RightAlt = 346;
	var RightSuper = 347;

	#if cpp
	/** C++ needs the cast: the header says `wgr_keycode_t`, not `int`. **/
	@:to inline function toRaw():CKeycode
		return untyped __cpp__("(wgr_keycode_t)({0})", this);
	#end
}

class KeyCheck {
	// Exists only to give the static_asserts above a translation unit.
	static function __check():Void {}
}
