package wgr;

// wgr_keys.h — generated by tools/gen_keys.py. Do not edit; run the tool.

/**
	wgrender's key codes (`WGR_KEY_*`, wgr_keys.h). The numbers currently follow the
	GLFW/sokol layout, but that is an implementation detail: code to the names.
	`KeyCheck` below asserts them against the header at C++ compile time.
**/
enum abstract Key(Int) from Int to Int {
	var Space = 32;
	var Apostrophe = 39;
	var Comma = 44;
	var Minus = 45;
	var Period = 46;
	var Slash = 47;
	var Digit0 = 48;
	var Digit1 = 49;
	var Digit2 = 50;
	var Digit3 = 51;
	var Digit4 = 52;
	var Digit5 = 53;
	var Digit6 = 54;
	var Digit7 = 55;
	var Digit8 = 56;
	var Digit9 = 57;
	var Semicolon = 59;
	var Equal = 61;
	var A = 65;
	var B = 66;
	var C = 67;
	var D = 68;
	var E = 69;
	var F = 70;
	var G = 71;
	var H = 72;
	var I = 73;
	var J = 74;
	var K = 75;
	var L = 76;
	var M = 77;
	var N = 78;
	var O = 79;
	var P = 80;
	var Q = 81;
	var R = 82;
	var S = 83;
	var T = 84;
	var U = 85;
	var V = 86;
	var W = 87;
	var X = 88;
	var Y = 89;
	var Z = 90;
	var LeftBracket = 91;
	var Backslash = 92;
	var RightBracket = 93;
	var GraveAccent = 96;
	var Escape = 256;
	var Enter = 257;
	var Tab = 258;
	var Backspace = 259;
	var Insert = 260;
	var Delete = 261;
	var Right = 262;
	var Left = 263;
	var Down = 264;
	var Up = 265;
	var PageUp = 266;
	var PageDown = 267;
	var Home = 268;
	var End = 269;
	var CapsLock = 280;
	var F1 = 290;
	var F2 = 291;
	var F3 = 292;
	var F4 = 293;
	var F5 = 294;
	var F6 = 295;
	var F7 = 296;
	var F8 = 297;
	var F9 = 298;
	var F10 = 299;
	var F11 = 300;
	var F12 = 301;
	var LeftShift = 340;
	var LeftControl = 341;
	var LeftAlt = 342;
	var LeftSuper = 343;
	var RightShift = 344;
	var RightControl = 345;
	var RightAlt = 346;
	var RightSuper = 347;

	#if cpp
	/** C++ needs the cast: the header says `wgr_keycode_t`, not `int`. **/
	@:to inline function toRaw():CKeycode
		return untyped __cpp__("(wgr_keycode_t)({0})", this);
	#end
}

// The static_asserts are the point: if wgrender renumbers a key, the C++ build fails
// here rather than the wrong key being pressed. js has no compiler to assert with.
#if cpp
@:keep
@:noCompletion
@:cppFileCode('#include <wgr_keys.h>
static_assert(WGR_KEY_SPACE == 32, "wgr.Key.Space is out of date with wgr_keys.h");
static_assert(WGR_KEY_APOSTROPHE == 39, "wgr.Key.Apostrophe is out of date with wgr_keys.h");
static_assert(WGR_KEY_COMMA == 44, "wgr.Key.Comma is out of date with wgr_keys.h");
static_assert(WGR_KEY_MINUS == 45, "wgr.Key.Minus is out of date with wgr_keys.h");
static_assert(WGR_KEY_PERIOD == 46, "wgr.Key.Period is out of date with wgr_keys.h");
static_assert(WGR_KEY_SLASH == 47, "wgr.Key.Slash is out of date with wgr_keys.h");
static_assert(WGR_KEY_0 == 48, "wgr.Key.Digit0 is out of date with wgr_keys.h");
static_assert(WGR_KEY_1 == 49, "wgr.Key.Digit1 is out of date with wgr_keys.h");
static_assert(WGR_KEY_2 == 50, "wgr.Key.Digit2 is out of date with wgr_keys.h");
static_assert(WGR_KEY_3 == 51, "wgr.Key.Digit3 is out of date with wgr_keys.h");
static_assert(WGR_KEY_4 == 52, "wgr.Key.Digit4 is out of date with wgr_keys.h");
static_assert(WGR_KEY_5 == 53, "wgr.Key.Digit5 is out of date with wgr_keys.h");
static_assert(WGR_KEY_6 == 54, "wgr.Key.Digit6 is out of date with wgr_keys.h");
static_assert(WGR_KEY_7 == 55, "wgr.Key.Digit7 is out of date with wgr_keys.h");
static_assert(WGR_KEY_8 == 56, "wgr.Key.Digit8 is out of date with wgr_keys.h");
static_assert(WGR_KEY_9 == 57, "wgr.Key.Digit9 is out of date with wgr_keys.h");
static_assert(WGR_KEY_SEMICOLON == 59, "wgr.Key.Semicolon is out of date with wgr_keys.h");
static_assert(WGR_KEY_EQUAL == 61, "wgr.Key.Equal is out of date with wgr_keys.h");
static_assert(WGR_KEY_A == 65, "wgr.Key.A is out of date with wgr_keys.h");
static_assert(WGR_KEY_B == 66, "wgr.Key.B is out of date with wgr_keys.h");
static_assert(WGR_KEY_C == 67, "wgr.Key.C is out of date with wgr_keys.h");
static_assert(WGR_KEY_D == 68, "wgr.Key.D is out of date with wgr_keys.h");
static_assert(WGR_KEY_E == 69, "wgr.Key.E is out of date with wgr_keys.h");
static_assert(WGR_KEY_F == 70, "wgr.Key.F is out of date with wgr_keys.h");
static_assert(WGR_KEY_G == 71, "wgr.Key.G is out of date with wgr_keys.h");
static_assert(WGR_KEY_H == 72, "wgr.Key.H is out of date with wgr_keys.h");
static_assert(WGR_KEY_I == 73, "wgr.Key.I is out of date with wgr_keys.h");
static_assert(WGR_KEY_J == 74, "wgr.Key.J is out of date with wgr_keys.h");
static_assert(WGR_KEY_K == 75, "wgr.Key.K is out of date with wgr_keys.h");
static_assert(WGR_KEY_L == 76, "wgr.Key.L is out of date with wgr_keys.h");
static_assert(WGR_KEY_M == 77, "wgr.Key.M is out of date with wgr_keys.h");
static_assert(WGR_KEY_N == 78, "wgr.Key.N is out of date with wgr_keys.h");
static_assert(WGR_KEY_O == 79, "wgr.Key.O is out of date with wgr_keys.h");
static_assert(WGR_KEY_P == 80, "wgr.Key.P is out of date with wgr_keys.h");
static_assert(WGR_KEY_Q == 81, "wgr.Key.Q is out of date with wgr_keys.h");
static_assert(WGR_KEY_R == 82, "wgr.Key.R is out of date with wgr_keys.h");
static_assert(WGR_KEY_S == 83, "wgr.Key.S is out of date with wgr_keys.h");
static_assert(WGR_KEY_T == 84, "wgr.Key.T is out of date with wgr_keys.h");
static_assert(WGR_KEY_U == 85, "wgr.Key.U is out of date with wgr_keys.h");
static_assert(WGR_KEY_V == 86, "wgr.Key.V is out of date with wgr_keys.h");
static_assert(WGR_KEY_W == 87, "wgr.Key.W is out of date with wgr_keys.h");
static_assert(WGR_KEY_X == 88, "wgr.Key.X is out of date with wgr_keys.h");
static_assert(WGR_KEY_Y == 89, "wgr.Key.Y is out of date with wgr_keys.h");
static_assert(WGR_KEY_Z == 90, "wgr.Key.Z is out of date with wgr_keys.h");
static_assert(WGR_KEY_LEFT_BRACKET == 91, "wgr.Key.LeftBracket is out of date with wgr_keys.h");
static_assert(WGR_KEY_BACKSLASH == 92, "wgr.Key.Backslash is out of date with wgr_keys.h");
static_assert(WGR_KEY_RIGHT_BRACKET == 93, "wgr.Key.RightBracket is out of date with wgr_keys.h");
static_assert(WGR_KEY_GRAVE_ACCENT == 96, "wgr.Key.GraveAccent is out of date with wgr_keys.h");
static_assert(WGR_KEY_ESCAPE == 256, "wgr.Key.Escape is out of date with wgr_keys.h");
static_assert(WGR_KEY_ENTER == 257, "wgr.Key.Enter is out of date with wgr_keys.h");
static_assert(WGR_KEY_TAB == 258, "wgr.Key.Tab is out of date with wgr_keys.h");
static_assert(WGR_KEY_BACKSPACE == 259, "wgr.Key.Backspace is out of date with wgr_keys.h");
static_assert(WGR_KEY_INSERT == 260, "wgr.Key.Insert is out of date with wgr_keys.h");
static_assert(WGR_KEY_DELETE == 261, "wgr.Key.Delete is out of date with wgr_keys.h");
static_assert(WGR_KEY_RIGHT == 262, "wgr.Key.Right is out of date with wgr_keys.h");
static_assert(WGR_KEY_LEFT == 263, "wgr.Key.Left is out of date with wgr_keys.h");
static_assert(WGR_KEY_DOWN == 264, "wgr.Key.Down is out of date with wgr_keys.h");
static_assert(WGR_KEY_UP == 265, "wgr.Key.Up is out of date with wgr_keys.h");
static_assert(WGR_KEY_PAGE_UP == 266, "wgr.Key.PageUp is out of date with wgr_keys.h");
static_assert(WGR_KEY_PAGE_DOWN == 267, "wgr.Key.PageDown is out of date with wgr_keys.h");
static_assert(WGR_KEY_HOME == 268, "wgr.Key.Home is out of date with wgr_keys.h");
static_assert(WGR_KEY_END == 269, "wgr.Key.End is out of date with wgr_keys.h");
static_assert(WGR_KEY_CAPS_LOCK == 280, "wgr.Key.CapsLock is out of date with wgr_keys.h");
static_assert(WGR_KEY_F1 == 290, "wgr.Key.F1 is out of date with wgr_keys.h");
static_assert(WGR_KEY_F2 == 291, "wgr.Key.F2 is out of date with wgr_keys.h");
static_assert(WGR_KEY_F3 == 292, "wgr.Key.F3 is out of date with wgr_keys.h");
static_assert(WGR_KEY_F4 == 293, "wgr.Key.F4 is out of date with wgr_keys.h");
static_assert(WGR_KEY_F5 == 294, "wgr.Key.F5 is out of date with wgr_keys.h");
static_assert(WGR_KEY_F6 == 295, "wgr.Key.F6 is out of date with wgr_keys.h");
static_assert(WGR_KEY_F7 == 296, "wgr.Key.F7 is out of date with wgr_keys.h");
static_assert(WGR_KEY_F8 == 297, "wgr.Key.F8 is out of date with wgr_keys.h");
static_assert(WGR_KEY_F9 == 298, "wgr.Key.F9 is out of date with wgr_keys.h");
static_assert(WGR_KEY_F10 == 299, "wgr.Key.F10 is out of date with wgr_keys.h");
static_assert(WGR_KEY_F11 == 300, "wgr.Key.F11 is out of date with wgr_keys.h");
static_assert(WGR_KEY_F12 == 301, "wgr.Key.F12 is out of date with wgr_keys.h");
static_assert(WGR_KEY_LEFT_SHIFT == 340, "wgr.Key.LeftShift is out of date with wgr_keys.h");
static_assert(WGR_KEY_LEFT_CONTROL == 341, "wgr.Key.LeftControl is out of date with wgr_keys.h");
static_assert(WGR_KEY_LEFT_ALT == 342, "wgr.Key.LeftAlt is out of date with wgr_keys.h");
static_assert(WGR_KEY_LEFT_SUPER == 343, "wgr.Key.LeftSuper is out of date with wgr_keys.h");
static_assert(WGR_KEY_RIGHT_SHIFT == 344, "wgr.Key.RightShift is out of date with wgr_keys.h");
static_assert(WGR_KEY_RIGHT_CONTROL == 345, "wgr.Key.RightControl is out of date with wgr_keys.h");
static_assert(WGR_KEY_RIGHT_ALT == 346, "wgr.Key.RightAlt is out of date with wgr_keys.h");
static_assert(WGR_KEY_RIGHT_SUPER == 347, "wgr.Key.RightSuper is out of date with wgr_keys.h");')
class KeyCheck {
	// Exists only to give the static_asserts above a translation unit.
	static function __check():Void {}
}
#end
