#!/usr/bin/env python3
"""Build the wgrender simple example in Haxe (Haxe -> hxcpp -> C++ -> native/wasm).

    ./build.py desktop     out/<os>/<variant>/simple (builds wgrender's native lib first)
    ./build.py web         out/web/webgl2-nothreads/: simple.js/.wasm + wgrender's page shell
    ./build.py all         both

    ./build.py serve       serve the web build on http://localhost:8000 (wgrender's tools/serve.py:
                           COOP/COEP headers for threads, examples/assets at /assets,
                           gzip-compressed responses)
    ./build.py sizes       wasm/JS sizes of the web build, raw and gzipped
    ./build.py compare     the same, next to wgrender's C example and the Nim and Beef ports
    ./build.py clean       remove out/ (what the builds made) and build/ (their work)

The binding's own checks are the library's, not this example's: run test/check.py
at the library root.

The wgr binding is the wgrender-hx haxelib (haxelib dev wgrender-hx <path>), shared
with the guest ports; this project only carries the example and its build.

Each build works in build/<platform>/<variant>/ (build/linux/release,
build/web/webgl2-nothreads, ...: the wg* layout, whirlinggizmo/.github CONVENTIONS.md).
It first writes build.hxml and wgrender.xml there: where wgrender is on this machine,
and the compile/link flags to use it. wgrender.xml is hxcpp build-tool XML, pulled in
by the @:buildXml on wgr.Wgr; build.hxml is this directory's build.hxml or web.hxml
with that, and the C++ output (cpp/ beside it). Afterwards `haxe
build/linux/release/build.hxml` (say) works on its own.

Web options are wgrender's web build settings, read from the environment:
  BACKEND=webgl2|webgpu   WEB_DEBUG=0|1   (e.g. BACKEND=webgpu ./build.py web)
Web builds are always WEB_THREADS=0: hxcpp's emscripten target is single-threaded, so
its objects are built without atomics and can't link into shared memory.
Override the wgrender location with WGRENDER_DIR=/path/to/wgrender.
"""
import gzip
import os
import pathlib
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent
LIB = ROOT.parents[1]
if not (LIB / 'tools/wgrpath.py').exists():
    _found = subprocess.run(['haxelib', 'libpath', 'wgrender-hx'],
                            capture_output=True, text=True).stdout.strip()
    if not _found:
        sys.exit('wgrender-hx not found. Either keep this example inside the library, or:\n'
                 '  haxelib git wgrender-hx https://github.com/whirlinggizmo/wgrender-hx')
    LIB = pathlib.Path(_found)
sys.path.insert(0, str(LIB / 'tools'))
from wgrpath import find, host_os  # noqa: E402  # examples/simple-hxcpp -> the library
import wgrbuild  # noqa: E402
WGRENDER = find(argv=[])
HAXE = os.environ.get('HAXE', 'haxe')
# The wgr binding, its generator and its host glue are the wgrender-hx haxelib.

def run(cmd, **kwargs):
    print('+', ' '.join(str(c) for c in cmd), flush=True)
    subprocess.run([str(c) for c in cmd], check=True, **kwargs)


def write_config(work, hxml, cflags, ldflags, libs):
    """work/wgrender.xml (hxcpp build-tool) and work/build.hxml (haxe): the committed
    hxml, told how to use wgrender and to put its C++ in work/cpp. Returns the latter."""
    work.mkdir(parents=True, exist_ok=True)

    def elements(tag, attr, values):
        return '\n'.join(f'    <{tag} {attr}="{v}" />' for v in values)

    # In an hxcpp target, <flag> lands before the object files and <lib> after them —
    # which is where a static library has to be.
    (work / 'wgrender.xml').write_text(f'''<xml>
<!-- Generated by build.py: how to compile and link against wgrender on this machine.
     Pulled in by the @:buildXml on wgr.Wgr. Do not edit; re-run ./build.py. -->
  <files id="haxe">
{elements('compilerflag', 'value', cflags)}
  </files>
  <!-- The guest glue. This example drives wgrender itself rather than being a guest,
       but wgr.Wgr's lifecycle setters go through the glue on both targets now: it owns
       wgrender's slots and dispatches to whatever Haxe set, which is what lets one
       source build all-in-one or as a guest. -->
  <files id="wgrguest">
{elements('compilerflag', 'value', cflags)}
    <file name="{LIB}/host/wgr_guest.c" />
  </files>
  <files id="__main__">
{elements('compilerflag', 'value', cflags)}
  </files>
  <target id="haxe">
    <files id="wgrguest" />
{elements('flag', 'value', ldflags)}
{elements('lib', 'name', libs)}
  </target>
</xml>
''')

    rel = work.relative_to(ROOT).as_posix()
    lines = ['# Generated by build.py — where wgrender is on this machine. Run from the example.',
             f'-D WGR_BUILD_XML={work / "wgrender.xml"}',
             hxml,
             f'--cpp {rel}/cpp']
    (work / 'build.hxml').write_text('\n'.join(lines) + '\n')
    return work / 'build.hxml'


def desktop_variant():
    """<platform>/<variant> (the wg* layout): release, or on Windows mingw, the
    toolchain wgrbuild.desktop builds wgrender's library with (gcc)."""
    return f"{host_os()}/{'mingw' if host_os() == 'windows' else 'release'}"


def web_variant():
    """web/<variant>: wgrender's web settings, always without threads here."""
    backend = os.environ.get('BACKEND') or 'webgl2'
    debug = (os.environ.get('WEB_DEBUG') or '0') == '1'
    return 'web/' + f'{backend}-nothreads' + ('-debug' if debug else '')


def desktop_out():
    return ROOT / 'out' / desktop_variant()


def web_out():
    return ROOT / 'out' / web_variant()


def build_desktop():
    print('wgrender (desktop)')
    lib, libs = wgrbuild.desktop(WGRENDER)
    work = ROOT / 'build' / desktop_variant()
    hxml = write_config(work, 'build.hxml',
                        cflags=[f'-I{WGRENDER}/include', f'-I{LIB}/host'],
                        ldflags=[],
                        libs=[str(lib), *libs])
    out = desktop_out()
    print(f'simple (desktop) -> {out.relative_to(ROOT)}/simple')
    run([HAXE, hxml.relative_to(ROOT)], cwd=ROOT)
    out.mkdir(parents=True, exist_ok=True)
    exe = 'simple' + ('.exe' if host_os() == 'windows' else '')
    shutil.copy2(work / 'cpp' / exe, out / exe)
    # wgr.Assets looks for `assets` beside the executable, the same lookup a shipped
    # program uses. (A Windows build would copy or junction instead of linking.)
    link = out / 'assets'
    if link.is_symlink() or link.exists():
        link.unlink()
    link.symlink_to(WGRENDER / 'examples/assets')
    print(f'built {out}/simple (assets -> {link.readlink()})')


def build_web():
    print('wgrender (web)')
    lib, cflags, ldflags = wgrbuild.web(WGRENDER)
    # The guest glue, as on desktop -- plus WGR_GUEST_NO_MAIN, because this build has
    # hxcpp's main() and the glue would otherwise define a second one.
    cflags = [*cflags, f'-I{LIB}/host', '-DWGR_GUEST_NO_MAIN']
    # wgrender's EM_JS glue makes emscripten's JS $stackSave/$stackRestore live, but
    # under hxcpp's -fwasm-exceptions nothing native references the wasm stack ops, so
    # emcc leaves them out and the link fails on them. Exporting them pulls them in.
    # (-sEXPORTED_FUNCTIONS replaces the default list, so _main has to be named too.)
    ldflags = ['-sEXPORTED_FUNCTIONS=_main,_emscripten_stack_get_current,__emscripten_stack_restore', *ldflags]
    # emcc takes JS libraries anywhere on the line; everything else is a plain flag.
    work = ROOT / 'build' / web_variant()
    hxml = write_config(work, 'web.hxml',
                        cflags=cflags,
                        ldflags=[f for f in ldflags if not f.startswith('-l')],
                        libs=[str(lib), *[f for f in ldflags if f.startswith('-l')]])
    site = web_out()
    print(f'simple (web) -> {site.relative_to(ROOT)}/')
    run([HAXE, hxml.relative_to(ROOT)], cwd=ROOT)

    site.mkdir(parents=True, exist_ok=True)
    for name in ('simple.js', 'simple.wasm'):
        shutil.copy2(work / 'cpp' / name, site / name)
    # wgrender's page shell, opening this example by default (its default is "hello"),
    # finished by wgrender's deploy script: versioned file names and examples.json.
    shell = work / 'index.html'
    shell.write_text((WGRENDER / 'examples/web/index.html').read_text()
                     .replace('params.get("ex") || "hello"', 'params.get("ex") || "simple"')
                     .replace('<title>wgrender examples</title>', '<title>simple (wgrender, Haxe)</title>'))
    run([sys.executable, WGRENDER / 'tools/webdeploy.py', site, shell])
    shell.unlink()
    sizes()
    print(f'built {site.relative_to(ROOT)} — ./build.py serve, then open http://localhost:8000/')



def measure(directory):
    out = {}
    for name in ('simple.js', 'simple.wasm'):
        path = pathlib.Path(directory) / name
        if path.exists():
            out[name] = (path.stat().st_size, len(gzip.compress(path.read_bytes(), 9)))
    return out


def sizes():
    for name, (raw, packed) in measure(web_out()).items():
        print(f'{name}: {raw:,} bytes ({packed:,} gzipped)')


def compare():
    """Every port of this example that is built, side by side.

    Only comparable when each was linked against the same wgrender web library —
    BACKEND=webgl2 WEB_THREADS=0, which is what ./build.py web uses. The Nim port
    defaults to WEB_THREADS=1; build it with WEB_THREADS=0 to line the numbers up.
    """
    ports = [
        ('C (wgrender example)', WGRENDER / 'out/web/webgl2-nothreads'),
        ('Nim', LIB / '../wgrender-nim/examples/simple/out/web/webgl2-nothreads'),
        ('Beef', LIB / '../wgrender-beef/examples/simple/out/web/webgl2-nothreads'),
        ('Haxe (this)', web_out()),
    ]
    rows = [(label, measure(path)) for label, path in ports]
    baseline = next((m['simple.wasm'][0] for label, m in rows if label.startswith('C')), None)
    print(f'{"port":<22} {"wasm":>12} {"gzipped":>11} {"vs C":>8}   {"js":>9} {"gzipped":>9}')
    for label, m in rows:
        if 'simple.wasm' not in m:
            print(f'{label:<22} (not built)')
            continue
        wasm, wasm_gz = m['simple.wasm']
        js, js_gz = m.get('simple.js', (0, 0))
        over = f'{wasm / baseline:.2f}x' if baseline else '-'
        print(f'{label:<22} {wasm:>12,} {wasm_gz:>11,} {over:>8}   {js:>9,} {js_gz:>9,}')


def serve(port='8000'):
    run([sys.executable, WGRENDER / 'tools/serve.py', port, web_out(), '--gzip'])


def clean():
    for d in ('out', 'build'):
        shutil.rmtree(ROOT / d, ignore_errors=True)
        print(f'removed {d}/')


def main():
    args = sys.argv[1:]
    command = args[0] if args else ''
    if command == 'desktop':
        build_desktop()
    elif command == 'web':
        build_web()
    elif command == 'all':
        build_desktop()
        build_web()
    elif command == 'serve':
        serve(*args[1:2])
    elif command == 'sizes':
        sizes()
    elif command == 'compare':
        compare()
    elif command == 'clean':
        clean()
    else:
        sys.exit(__doc__)


if __name__ == '__main__':
    main()
