#!/usr/bin/env python3
"""Build the wgrender simple example in Haxe (Haxe -> hxcpp -> C++ -> native/wasm).

    ./build.py desktop     out/<os>/simple (builds wgrender's native lib first)
    ./build.py web         out/web/: simple.js/.wasm + wgrender's page shell
    ./build.py all         both

    ./build.py serve       serve out/web on http://localhost:8000 (wgrender's tools/serve.py:
                           COOP/COEP headers for threads, examples/assets at /assets,
                           gzip-compressed responses)
    ./build.py sizes       wasm/JS sizes of out/web, raw and gzipped
    ./build.py compare     the same, next to wgrender's C example and the Nim and Beef ports
    ./build.py clean       remove out/ and build/

The binding's own checks are the library's, not this example's: run test/check.py
at the library root.

The wgr binding is the wgrender-hx haxelib (haxelib dev wgrender-hx <path>), shared
with the guest ports; this project only carries the example and its build.

Each build first writes build/<target>.hxml and build/<target>.xml: where wgrender is
on this machine, and the compile/link flags to use it. build/<target>.xml is hxcpp
build-tool XML, pulled in by the @:buildXml on wgr.Wgr. Afterwards `haxe build.hxml`
and `haxe web.hxml` work on their own.

Web options are wgrender's make variables, read from the environment:
  BACKEND=webgl2|webgpu   WEB_DEBUG=0|1   (e.g. BACKEND=webgpu ./build.py web)
Web builds are always WEB_THREADS=0: hxcpp's emscripten target is single-threaded, so
its objects are built without atomics and can't link into shared memory.
Override the wgrender location with WGRENDER_DIR=/path/to/wgrender.
"""
import gzip
import os
import pathlib
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent
LIB = ROOT.parents[1]
if not (LIB / 'tools/wgrpath.py').exists():
    _found = subprocess.run(['haxelib', 'libpath', 'wgrender-hx'],
                            capture_output=True, text=True).stdout.strip()
    if not _found:
        sys.exit('wgrender-hx not found. Either keep this example inside the library, or:\n'
                 '  haxelib git wgrender-hx https://github.com/whirlinggizmo/wgrender-hx')
    LIB = pathlib.Path(_found)
sys.path.insert(0, str(LIB / 'tools'))
from wgrpath import find, host_os  # noqa: E402  # examples/simple-hxcpp -> the library
WGRENDER = find(argv=[])
HAXE = os.environ.get('HAXE', 'haxe')
# The wgr binding, its generator and its host glue are the wgrender-hx haxelib.

# Desktop link libraries, as in wgrender's examples/Makefile.
DESKTOP_LIBS = ['-lGL', '-lX11', '-lXi', '-lXcursor', '-lXrandr', '-lasound', '-ldl', '-lm', '-lpthread']


def run(cmd, **kwargs):
    print('+', ' '.join(str(c) for c in cmd), flush=True)
    subprocess.run([str(c) for c in cmd], check=True, **kwargs)


def make(*args):
    """A wgrender make call, with the web variables from the environment."""
    web_vars = [f'{v}={os.environ[v]}' for v in ('BACKEND', 'WEB_DEBUG') if v in os.environ]
    return ['make', '--no-print-directory', '-s', '-C', WGRENDER, *args, *web_vars]


def web_flags():
    """wgrender's web compile/link flags, so this build matches how the library was built."""
    output = subprocess.run([str(c) for c in make('print-web-flags', 'WEB_THREADS=0')],
                            check=True, capture_output=True, text=True).stdout
    flags = {}
    for line in output.splitlines():
        key, _, value = line.partition(':')
        flags[key.strip()] = value.strip()
    if 'lib' not in flags:
        sys.exit(f'could not read wgrender web flags:\n{output}')
    return (WGRENDER / flags['lib'],
            flags.get('cflags', '').replace('-Iinclude', f'-I{WGRENDER}/include').split(),
            flags.get('ldflags', '').split())


def write_config(target, cflags, ldflags, libs, defines=()):
    """build/<target>.xml (hxcpp build-tool) and build/<target>.hxml (haxe)."""
    build = ROOT / 'build'
    build.mkdir(exist_ok=True)

    def elements(tag, attr, values):
        return '\n'.join(f'    <{tag} {attr}="{v}" />' for v in values)

    # In an hxcpp target, <flag> lands before the object files and <lib> after them —
    # which is where a static library has to be.
    (build / f'{target}.xml').write_text(f'''<xml>
<!-- Generated by build.py: how to compile and link against wgrender on this machine.
     Pulled in by the @:buildXml on wgr.Wgr. Do not edit; re-run ./build.py. -->
  <files id="haxe">
{elements('compilerflag', 'value', cflags)}
  </files>
  <!-- The guest glue. This example drives wgrender itself rather than being a guest,
       but wgr.Wgr's lifecycle setters go through the glue on both targets now: it owns
       wgrender's slots and dispatches to whatever Haxe set, which is what lets one
       source build all-in-one or as a guest. -->
  <files id="wgrguest">
{elements('compilerflag', 'value', cflags)}
    <file name="{LIB}/host/wgr_guest.c" />
  </files>
  <files id="__main__">
{elements('compilerflag', 'value', cflags)}
  </files>
  <target id="haxe">
    <files id="wgrguest" />
{elements('flag', 'value', ldflags)}
{elements('lib', 'name', libs)}
  </target>
</xml>
''')

    lines = [f'# Generated by build.py — where wgrender is on this machine.',
             f'-D WGR_BUILD_XML={build / f"{target}.xml"}']
    lines += [f'-D {d}' for d in defines]
    (build / f'{target}.hxml').write_text('\n'.join(lines) + '\n')


def build_desktop():
    print('wgrender (desktop)')
    run(make('all'))
    write_config('desktop',
                 cflags=[f'-I{WGRENDER}/include', f'-I{LIB}/host'],
                 ldflags=[],
                 libs=[str(WGRENDER / f'build/{host_os()}/libwgrender.a'), *DESKTOP_LIBS])
    print(f'simple (desktop) -> out/{host_os()}/simple')
    run([HAXE, 'build.hxml'])
    out = ROOT / f'out/{host_os()}'
    out.mkdir(parents=True, exist_ok=True)
    shutil.copy2(ROOT / 'build/cpp/desktop/simple', out / 'simple')
    # wgr.Assets looks for `assets` beside the executable, the same lookup a shipped
    # program uses. (A Windows build would copy or junction instead of linking.)
    link = out / 'assets'
    if link.is_symlink() or link.exists():
        link.unlink()
    link.symlink_to(WGRENDER / 'examples/assets')
    print(f'built {out}/simple (assets -> {link.readlink()})')


def build_web():
    print('wgrender (web)')
    run(make('web', 'WEB_THREADS=0'))
    lib, cflags, ldflags = web_flags()
    # The guest glue, as on desktop -- plus WGR_GUEST_NO_MAIN, because this build has
    # hxcpp's main() and the glue would otherwise define a second one.
    cflags = [*cflags, f'-I{LIB}/host', '-DWGR_GUEST_NO_MAIN']
    # wgrender's EM_JS glue makes emscripten's JS $stackSave/$stackRestore live, but
    # under hxcpp's -fwasm-exceptions nothing native references the wasm stack ops, so
    # emcc leaves them out and the link fails on them. Exporting them pulls them in.
    # (-sEXPORTED_FUNCTIONS replaces the default list, so _main has to be named too.)
    ldflags = ['-sEXPORTED_FUNCTIONS=_main,_emscripten_stack_get_current,__emscripten_stack_restore', *ldflags]
    # emcc takes JS libraries anywhere on the line; everything else is a plain flag.
    write_config('web',
                 cflags=cflags,
                 ldflags=[f for f in ldflags if not f.startswith('-l')],
                 libs=[str(lib), *[f for f in ldflags if f.startswith('-l')]])
    print('simple (web) -> out/web/')
    run([HAXE, 'web.hxml'])

    site = ROOT / 'out/web'
    site.mkdir(parents=True, exist_ok=True)
    for name in ('simple.js', 'simple.wasm'):
        shutil.copy2(ROOT / 'build/cpp/web' / name, site / name)
    # wgrender's page shell, opening this example by default (its default is "hello"),
    # finished by wgrender's deploy script: versioned file names and examples.json.
    shell = ROOT / 'build/index.html'
    shell.write_text((WGRENDER / 'examples/web/index.html').read_text()
                     .replace('params.get("ex") || "hello"', 'params.get("ex") || "simple"')
                     .replace('<title>wgrender examples</title>', '<title>simple (wgrender, Haxe)</title>'))
    run(['python3', WGRENDER / 'tools/webdeploy.py', site, shell])
    shell.unlink()
    sizes()
    print('built out/web — ./build.py serve, then open http://localhost:8000/')



def measure(directory):
    out = {}
    for name in ('simple.js', 'simple.wasm'):
        path = pathlib.Path(directory) / name
        if path.exists():
            out[name] = (path.stat().st_size, len(gzip.compress(path.read_bytes(), 9)))
    return out


def sizes():
    for name, (raw, packed) in measure(ROOT / 'out/web').items():
        print(f'{name}: {raw:,} bytes ({packed:,} gzipped)')


def compare():
    """Every port of this example that is built, side by side.

    Only comparable when each was linked against the same wgrender web library —
    BACKEND=webgl2 WEB_THREADS=0, which is what ./build.py web uses. The Nim port
    defaults to WEB_THREADS=1; build it with WEB_THREADS=0 to line the numbers up.
    """
    ports = [
        ('C (wgrender example)', WGRENDER / 'examples/build/webgl2-nothreads'),
        ('Nim', ROOT / '../../../../../nim/simple/out/web'),
        ('Beef', ROOT / '../../../../../beef/simple/build/web'),
        ('Haxe (this)', ROOT / 'out/web'),
    ]
    rows = [(label, measure(path)) for label, path in ports]
    baseline = next((m['simple.wasm'][0] for label, m in rows if label.startswith('C')), None)
    print(f'{"port":<22} {"wasm":>12} {"gzipped":>11} {"vs C":>8}   {"js":>9} {"gzipped":>9}')
    for label, m in rows:
        if 'simple.wasm' not in m:
            print(f'{label:<22} (not built)')
            continue
        wasm, wasm_gz = m['simple.wasm']
        js, js_gz = m.get('simple.js', (0, 0))
        over = f'{wasm / baseline:.2f}x' if baseline else '-'
        print(f'{label:<22} {wasm:>12,} {wasm_gz:>11,} {over:>8}   {js:>9,} {js_gz:>9,}')


def serve(port='8000'):
    run(['python3', WGRENDER / 'tools/serve.py', port, ROOT / 'out/web', '--gzip'])


def clean():
    for d in ('out', 'build'):
        shutil.rmtree(ROOT / d, ignore_errors=True)
        print(f'removed {d}/')


def main():
    args = sys.argv[1:]
    command = args[0] if args else ''
    if command == 'desktop':
        build_desktop()
    elif command == 'web':
        build_web()
    elif command == 'all':
        build_desktop()
        build_web()
    elif command == 'serve':
        serve(*args[1:2])
    elif command == 'sizes':
        sizes()
    elif command == 'compare':
        compare()
    elif command == 'clean':
        clean()
    else:
        sys.exit(__doc__)


if __name__ == '__main__':
    main()
