#!/usr/bin/env python3
"""Build and check every example here.

    examples/build.py all        build each one (web and native)
    examples/build.py web        the web build only
    examples/build.py drive      run each web build in a headless browser
    examples/build.py site       collect every web build into out/www with a picker
    examples/build.py serve      build the site and serve it on :8000
    examples/build.py compare    sizes against wgrender's own C build of each
    examples/build.py bench      frame cost, Haxe against C, for each
    examples/build.py clean

Each example owns its build.py; this runs them, so there is one command to say
"everything still works" after a change to the binding. The library's own checks are
test/check.py at the root -- they are not an example's business and run on their own.

Python rather than a Makefile: nothing else in wgrender-hx uses make, and wgrender's
own tools (serve.py, webdeploy.py) are Python and get shelled out to from here, so
this adds no dependency that building already needed.

    WGRENDER_DIR   where wgrender-c is
    ONLY=name,name limit it to those examples
"""
import os
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
LIB = HERE.parent
if not (LIB / 'tools/wgrpath.py').exists():
    # this tree has been copied out of the library; ask haxelib where it went
    _found = subprocess.run(['haxelib', 'libpath', 'wgrender-hx'],
                            capture_output=True, text=True).stdout.strip()
    if not _found:
        sys.exit('wgrender-hx not found. Either keep examples/ inside the library, or:\n'
                 '  haxelib git wgrender-hx https://github.com/whirlinggizmo/wgrender-hx')
    LIB = pathlib.Path(_found)
sys.path.insert(0, str(LIB / 'tools'))
from wgrpath import find  # noqa: E402
WGRENDER = find(argv=[])
C_BUILD = WGRENDER / 'examples/build/webgl2-nothreads'

# simple-hxcpp is the other architecture -- Haxe through hxcpp into one wasm, rather
# than a JS guest on a wgrender host -- so it has its own commands and is not driven
# or benched with the guests.
GUESTS = ['hello3d', 'particles', 'simple']
OTHERS = ['simple-hxcpp']


def wanted(names):
    only = os.environ.get('ONLY')
    return [n for n in names if not only or n in only.split(',')]


def run(cmd, cwd, **kw):
    print(f'\n=== {cwd.name}: {" ".join(str(c) for c in cmd)}', flush=True)
    subprocess.run([str(c) for c in cmd], check=True, cwd=cwd, **kw)


def each(command, names=None):
    for name in wanted(names or GUESTS + OTHERS):
        run(['./build.py', command], HERE / name)


def drive():
    for name in wanted(GUESTS):
        run(['node', 'tools/drive.mjs'], HERE / name)
    if 'simple-hxcpp' in wanted(OTHERS):
        run(['node', 'check_web.mjs'], HERE / 'simple-hxcpp')


def bench():
    if not C_BUILD.exists():
        sys.exit(f'no C builds at {C_BUILD}\n'
                 f'  make -C {WGRENDER} wasm-all WEB_THREADS=0')
    for name in wanted(GUESTS):
        for args in ([f'--site={C_BUILD}', f'--url=/?ex={name}', '--probe=examples.json',
                      f'--label={name}-c'],
                     [f'--site={HERE / name / "out/web"}', f'--label={name}-haxe']):
            subprocess.run(['node', str(LIB / 'tools/bench.mjs'), *args], check=True)


SITE_INDEX = """<!doctype html>
<meta charset="utf-8">
<title>wgrender-hx examples</title>
<!-- Generated by examples/build.py site. -->
<style>
  :root {{ color-scheme: dark; }}
  body {{ margin: 0; padding: 2.5rem 1.5rem; background: #14141a; color: #e8e8ef;
         font: 15px/1.6 ui-monospace, SFMono-Regular, Menlo, monospace; }}
  main {{ max-width: 46rem; margin: 0 auto; }}
  h1 {{ font-size: 1.3rem; font-weight: 600; margin: 0 0 .3rem; }}
  p.lede {{ color: #9a9aad; margin: 0 0 2rem; }}
  ul {{ list-style: none; padding: 0; margin: 0 0 2.5rem; }}
  li {{ margin: 0 0 .5rem; }}
  a {{ color: #66bfff; text-decoration: none; display: block; padding: .7rem .9rem;
       border: 1px solid #2a2a36; border-radius: 6px; }}
  a:hover {{ background: #1c1c26; border-color: #3a3a4a; }}
  a span {{ float: right; color: #6a6a7d; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 13px; }}
  th, td {{ text-align: right; padding: .35rem .6rem; border-bottom: 1px solid #23232e; }}
  th:first-child, td:first-child {{ text-align: left; }}
  th {{ color: #9a9aad; font-weight: 500; }}
  caption {{ text-align: left; color: #9a9aad; padding-bottom: .6rem; }}
</style>
<main>
<h1>wgrender-hx examples</h1>
<p class="lede">wgrender compiled to wasm as the host, the game compiled to JS as the
guest. The same sources build native through hxcpp.</p>
<ul>
{links}
</ul>
{table}
</main>
"""


def site():
    """Every built example under one directory, with a page that lists them.

    Each example already generates a working page into its own out/web, so this
    copies those in side by side rather than building anything new. They cannot share
    a directory: every example has its own wgrender-host.wasm, exporting exactly the
    calls that guest makes, and they all have that name.
    """
    import shutil
    out = HERE / 'out/www'
    shutil.rmtree(out, ignore_errors=True)
    out.mkdir(parents=True)
    links, built = [], []
    for name in wanted(GUESTS):
        src = HERE / name / 'out/web'
        if not (src / 'index.html').exists():
            print(f'{name}: not built, skipping (./build.py all)', file=sys.stderr)
            continue
        shutil.copytree(src, out / name)
        built.append(name)
        size = sum(f.stat().st_size for f in (out / name).rglob('*') if f.is_file())
        links.append(f'  <li><a href="./{name}/">{name}<span>{size:,} bytes</span></a></li>')
    if not built:
        sys.exit('nothing built: examples/build.py all')
    (out / 'index.html').write_text(
        SITE_INDEX.format(links='\n'.join(links), table=size_table(built)))
    print(f'site -> {out} ({len(built)} examples)')
    return out


def size_table(names):
    """The comparison against wgrender's own C build, inlined into the page."""
    import gzip
    if not C_BUILD.exists():
        return ''
    rows = []
    for name in names:
        site_dir = HERE / 'out/www' / name
        hx = [site_dir / 'wgrender-host.wasm', site_dir / 'wgrender-host.js', site_dir / f'{name}.js']
        c = [C_BUILD / f'{name}.wasm', C_BUILD / f'{name}.js']
        if not all(p.exists() for p in hx + c):
            continue
        def total(paths):
            data = b''.join(p.read_bytes() for p in paths)
            return sum(p.stat().st_size for p in paths), len(gzip.compress(data, 9))
        craw, cgz = total(c)
        hraw, hgz = total(hx)
        rows.append(f'<tr><td>{name}</td><td>{craw:,}</td><td>{cgz:,}</td>'
                    f'<td>{hraw:,}</td><td>{hgz:,}</td><td>{hgz / cgz:.2f}x</td></tr>')
    if not rows:
        return ''
    return ('<table><caption>Against wgrender\'s own C build of the same example, same '
            'backend and threading.</caption>'
            '<tr><th>example</th><th>C</th><th>C gzip</th><th>Haxe</th><th>Haxe gzip</th>'
            '<th>vs C</th></tr>' + ''.join(rows) + '</table>')


def serve():
    out = site()
    subprocess.run(['python3', str(WGRENDER / 'tools/serve.py'), '8000', str(out)], check=False)


def main():
    command = sys.argv[1] if len(sys.argv) > 1 else ''
    if command == 'all':
        each('all')
    elif command in ('web', 'guest', 'host', 'desktop', 'sizes', 'clean'):
        # the guests take host/guest/desktop; simple-hxcpp takes web/desktop
        if command in ('guest', 'host'):
            each(command, GUESTS)
        elif command == 'web':
            each('all', GUESTS)
            each('web', OTHERS)
        else:
            each(command)
    elif command == 'drive':
        drive()
    elif command == 'site':
        site()
    elif command == 'serve':
        serve()
    elif command == 'compare':
        # compare.py prints what is missing and why; a traceback on top of that adds
        # a stack trace to a message that was already the answer.
        return subprocess.run([str(LIB / 'tools/compare.py')]).returncode
    elif command == 'bench':
        bench()
    else:
        sys.exit(__doc__)


if __name__ == '__main__':
    sys.exit(main() or 0)
