#!/usr/bin/env python3
"""Build and check the examples here.

    examples/build.py <command> [example ...]

Naming examples limits the command to those; naming none means all of them.

    all        build it: the guest, the wasm host, and the native binary
    guest      the Haxe-to-JS half only
    host       the wasm host only (reads the built guest to know what to export)
    desktop    the native binary only
    web        everything a browser needs
    drive      run each web build in a headless browser and fail on a console error
    site       collect every web build into out/www with a page that lists them
    serve      build that site and serve it (--tls cert key for https on 8443)
    sizes      what each web build weighs
    compare    those sizes against wgrender's own C build of the same example
    bench      frame cost, Haxe against C
    list       the examples, and what each one is
    clean      remove out/ and build/

So `examples/build.py desktop` builds every example's native binary, and
`examples/build.py all simple` builds one example every way.

Each example owns its build.py; this runs them, so there is one command to say
whether a change to the binding broke any of them. The library's own checks are
test/check.py at the root -- they are not an example's business and run on their own.

Python rather than a Makefile: nothing else in wgrender-hx uses make, and wgrender's
own tools that this shells out to are Python already, so it adds no dependency the
build did not have.

    WGRENDER_DIR   build against a wgrender of your own
    TLS_CERT/TLS_KEY   serve https without passing --tls
"""
import json
import os
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
LIB = HERE.parent
if not (LIB / 'tools/wgrpath.py').exists():
    # this tree has been copied out of the library; ask haxelib where it went
    _found = subprocess.run(['haxelib', 'libpath', 'wgrender-hx'],
                            capture_output=True, text=True).stdout.strip()
    if not _found:
        sys.exit('wgrender-hx not found. Either keep examples/ inside the library, or:\n'
                 '  haxelib git wgrender-hx https://github.com/whirlinggizmo/wgrender-hx')
    LIB = pathlib.Path(_found)
sys.path.insert(0, str(LIB / 'tools'))
from wgrpath import find  # noqa: E402
WGRENDER = find(argv=[])
C_BUILD = WGRENDER / 'examples/build/webgl2-nothreads'

# simple-hxcpp is the other architecture -- Haxe through hxcpp into one wasm, rather
# than a JS guest on a wgrender host -- so it has its own commands and is not driven
# or benched with the guests.
GUESTS = ['hello', 'hello3d', 'particles', 'simple', 'tick']
OTHERS = ['simple-hxcpp']

WHAT = {
    'hello': 'a window, 2D shapes, text and the mouse',
    'hello3d': 'an orbiting camera over immediate-mode 3D; loads nothing, so it is '
               'the size floor',
    'particles': 'five emitters, 2D and 3D, with a click to burst confetti',
    'tick': 'a 10 Hz simulation against the render rate, raw and interpolated',
    'simple': 'a glTF model, a sprite, text, audio and picking',
    'simple-hxcpp': 'the same scene the other way: Haxe through hxcpp into one wasm, '
                    'for the size comparison',
}


def wanted(names, chosen=()):
    picked = [n for n in names if not chosen or n in chosen]
    if chosen and not picked and set(chosen) - set(GUESTS + OTHERS):
        sys.exit(f'no such example: {", ".join(sorted(set(chosen) - set(GUESTS + OTHERS)))}\n'
                 f'  have: {", ".join(GUESTS + OTHERS)}')
    return picked


def run(cmd, cwd, **kw):
    print(f'\n=== {cwd.name}: {" ".join(str(c) for c in cmd)}', flush=True)
    subprocess.run([str(c) for c in cmd], check=True, cwd=cwd, **kw)


def each(command, names=None, chosen=()):
    for name in wanted(names or GUESTS + OTHERS, chosen):
        run(['./build.py', command], HERE / name)


def drive(chosen=()):
    for name in wanted(GUESTS, chosen):
        run(['node', 'tools/drive.mjs'], HERE / name)
    if 'simple-hxcpp' in wanted(OTHERS, chosen):
        run(['node', 'check_web.mjs'], HERE / 'simple-hxcpp')


def bench(chosen=()):
    if not C_BUILD.exists():
        sys.exit(f'no C builds at {C_BUILD}\n'
                 f'  make -C {WGRENDER} wasm-all WEB_THREADS=0')
    for name in wanted(GUESTS, chosen):
        for args in ([f'--site={C_BUILD}', f'--url=/?ex={name}', '--probe=examples.json',
                      f'--label={name}-c'],
                     [f'--site={HERE / name / "out/web"}', f'--label={name}-haxe']):
            subprocess.run(['node', str(LIB / 'tools/bench.mjs'), *args], check=True)


SITE_INDEX = """<!doctype html>
<meta charset="utf-8">
<title>wgrender-hx examples</title>
<!-- Generated by examples/build.py site. -->
<style>
  :root {{ color-scheme: dark; }}
  body {{ margin: 0; padding: 2.5rem 1.5rem; background: #14141a; color: #e8e8ef;
         font: 15px/1.6 ui-monospace, SFMono-Regular, Menlo, monospace; }}
  main {{ max-width: 46rem; margin: 0 auto; }}
  h1 {{ font-size: 1.3rem; font-weight: 600; margin: 0 0 .3rem; }}
  p.lede {{ color: #9a9aad; margin: 0 0 2rem; }}
  form {{ display: flex; gap: .6rem; align-items: center; margin: 0 0 .6rem; }}
  select {{ flex: 1; padding: .6rem .7rem; background: #1c1c26; color: #e8e8ef;
           border: 1px solid #2a2a36; border-radius: 6px; font: inherit; }}
  select:hover {{ border-color: #3a3a4a; }}
  button {{ padding: .6rem 1.1rem; background: #66bfff; color: #14141a; border: 0;
           border-radius: 6px; font: inherit; font-weight: 600; cursor: pointer; }}
  button:hover {{ background: #8ccfff; }}
  p.what {{ color: #9a9aad; margin: 0 0 2.5rem; min-height: 1.6em; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 13px; }}
  th, td {{ text-align: right; padding: .35rem .6rem; border-bottom: 1px solid #23232e; }}
  th:first-child, td:first-child {{ text-align: left; }}
  th {{ color: #9a9aad; font-weight: 500; }}
  caption {{ text-align: left; color: #9a9aad; padding-bottom: .6rem; }}
  noscript p {{ color: #ffb4b4; }}
</style>
<main>
<h1>wgrender-hx examples</h1>
<p class="lede">wgrender compiled to wasm as the host, the game compiled to JS as the
guest. The same sources build native through hxcpp.</p>

<form onsubmit="go(event)">
  <select id="ex" onchange="describe()" aria-label="example">
{options}
  </select>
  <button type="submit">Run</button>
</form>
<p class="what" id="what"></p>

<noscript><p>This picker needs JavaScript; the examples are at ./&lt;name&gt;/</p></noscript>

{table}
</main>
<script>
  const WHAT = {what};
  const sel = document.getElementById("ex");
  // Remember the last pick, so a reload does not send you back to the top of the
  // list. Storage can throw in a private window, and the default is fine then.
  try {{
    const last = localStorage.getItem("wgrender-hx:example");
    if (last && [...sel.options].some((o) => o.value === last)) sel.value = last;
  }} catch (e) {{}}
  function describe() {{ document.getElementById("what").textContent = WHAT[sel.value] || ""; }}
  function go(event) {{
    event.preventDefault();
    try {{ localStorage.setItem("wgrender-hx:example", sel.value); }} catch (e) {{}}
    location.href = "./" + sel.value + "/";
  }}
  describe();
</script>
"""


def site(chosen=()):
    """Every built example under one directory, with a page that lists them.

    Each example already generates a working page into its own out/web, so this
    copies those in side by side rather than building anything new. They cannot share
    a directory: every example has its own wgrender-host.wasm, exporting exactly the
    calls that guest makes, and they all have that name.
    """
    import shutil
    out = HERE / 'out/www'
    shutil.rmtree(out, ignore_errors=True)
    out.mkdir(parents=True)
    options, built = [], []
    for name in wanted(GUESTS, chosen):
        src = HERE / name / 'out/web'
        if not (src / 'index.html').exists():
            print(f'{name}: not built, skipping (./build.py all)', file=sys.stderr)
            continue
        shutil.copytree(src, out / name)
        built.append(name)
        size = sum(f.stat().st_size for f in (out / name).rglob('*') if f.is_file())
        options.append(f'    <option value="{name}">{name} &mdash; {size:,} bytes</option>')
    if not built:
        sys.exit('nothing built: examples/build.py all')
    (out / 'index.html').write_text(SITE_INDEX.format(
        options='\n'.join(options),
        what=json.dumps({n: WHAT.get(n, '') for n in built}),
        table=size_table(built)))
    print(f'site -> {out} ({len(built)} examples)')
    return out


def size_table(names):
    """The comparison against wgrender's own C build, inlined into the page."""
    import gzip
    if not C_BUILD.exists():
        return ''
    rows = []
    for name in names:
        site_dir = HERE / 'out/www' / name
        hx = [site_dir / 'wgrender-host.wasm', site_dir / 'wgrender-host.js', site_dir / f'{name}.js']
        c = [C_BUILD / f'{name}.wasm', C_BUILD / f'{name}.js']
        if not all(p.exists() for p in hx + c):
            continue
        def total(paths):
            data = b''.join(p.read_bytes() for p in paths)
            return sum(p.stat().st_size for p in paths), len(gzip.compress(data, 9))
        craw, cgz = total(c)
        hraw, hgz = total(hx)
        rows.append(f'<tr><td>{name}</td><td>{craw:,}</td><td>{cgz:,}</td>'
                    f'<td>{hraw:,}</td><td>{hgz:,}</td><td>{hgz / cgz:.2f}x</td></tr>')
    if not rows:
        return ''
    return ('<table><caption>Against wgrender\'s own C build of the same example, same '
            'backend and threading.</caption>'
            '<tr><th>example</th><th>C</th><th>C gzip</th><th>Haxe</th><th>Haxe gzip</th>'
            '<th>vs C</th></tr>' + ''.join(rows) + '</table>')


def serve(args, chosen=()):
    """Build the site and serve it with wgrender's own dev server.

    Plain HTTP on 8000 by default. --tls (or TLS_CERT/TLS_KEY in the environment,
    as wgrender's own serve-tls target takes them) serves HTTPS on 8443 instead.

    That matters for another device: localhost counts as a secure context whatever
    the scheme, but a phone on the LAN does not, and a threaded build needs a secure
    page for SharedArrayBuffer. The certificate has to name this machine's LAN
    address, which is why nothing here invents one.
    """
    cert = os.environ.get('TLS_CERT')
    key = os.environ.get('TLS_KEY')
    if '--tls' in args:
        i = args.index('--tls')
        if len(args) < i + 3:
            sys.exit('--tls takes a certificate and a key: ./build.py serve --tls cert.pem key.pem')
        cert, key = args[i + 1], args[i + 2]
        args = args[:i] + args[i + 3:]
    port = next((a for a in args if a.isdigit()), '8443' if cert else '8000')
    if (cert is None) != (key is None):
        sys.exit('TLS needs both a certificate and a key')

    out = site(chosen)
    cmd = ['python3', str(WGRENDER / 'tools/serve.py'), port, str(out)]
    if cert:
        cmd += ['--tls', cert, key]
    scheme = 'https' if cert else 'http'
    print(f'\n{scheme}://localhost:{port}/')
    if not cert:
        print('  another device on the LAN needs https: ./build.py serve --tls cert.pem key.pem')
    subprocess.run(cmd, check=False)


def listing():
    for name in GUESTS + OTHERS:
        kind = 'guest' if name in GUESTS else 'all-in-one'
        print(f'  {name:<13} {kind:<11} {WHAT.get(name, "")}')


def main():
    args = sys.argv[1:]
    command = args[0] if args else ''
    rest = args[1:]
    # anything that is not a flag and names no file is an example to limit this to
    chosen = tuple(a for a in rest if not a.startswith('-') and not a.endswith('.pem')
                   and not a.isdigit())

    if command == 'list':
        listing()
    elif command == 'all':
        each('all', chosen=chosen)
    elif command in ('guest', 'host'):
        each(command, GUESTS, chosen)
    elif command == 'web':
        each('all', GUESTS, chosen)
        each('web', OTHERS, chosen)
    elif command in ('desktop', 'sizes', 'clean'):
        each(command, chosen=chosen)
    elif command == 'drive':
        drive(chosen)
    elif command == 'site':
        site(chosen)
    elif command == 'serve':
        serve(rest, chosen)
    elif command == 'compare':
        # compare.py prints what is missing and why; a traceback on top of that adds
        # a stack trace to a message that was already the answer.
        return subprocess.run([str(LIB / 'tools/compare.py')]
                              + [str(HERE / n) for n in chosen]).returncode
    elif command == 'bench':
        bench(chosen)
    else:
        sys.exit(__doc__)


if __name__ == '__main__':
    sys.exit(main() or 0)
