#!/usr/bin/env python3
"""Emit the mechanical half of src/wgr/Raw.js.hx from the hxcpp port's extern list.

    tools/gen_raw_js.py            rewrite the generated region of Raw.js.hx in place

The two targets declare the same C surface; only the way they reach it differs. This
reads ../simple/src/wgr/Raw.hx and renders each extern as a host-module call, so the
JS side can't silently drift from the hxcpp side. Calls returning a struct, and the
lifecycle/asset calls the guest ABI replaces, are hand-written — they are listed as
skipped rather than guessed at.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CPP_RAW = ROOT / 'src/wgr/impl/Raw.cpp.hx'
JS_RAW = ROOT / 'src/wgr/impl/Raw.js.hx'

# Replaced by the guest ABI (host/wgr_guest.h), so the JS layer never needs them.
GUEST_ABI_REPLACES = {'wgr_init_values', 'wgr_set_init', 'wgr_set_frame', 'wgr_run',
                      'wgr_asset_ensure_async', 'wgr_asset_add_task'}
# The guest ABI itself: its C function pointers have no JS equivalent, and the JS side
# installs its ops through addFunction instead (see GuestAbi.js.hx).
GUEST_ABI_OWN = {'wgr_guest_register', 'wgr_guest_set_fault_policy', 'wgr_guest_start',
                 'wgr_guest_asset_load', 'wgr_guest_frame_id', 'wgr_guest_faulted'}
STRUCT_RETURNS = {'CVec2', 'CVec3', 'CPickResult', 'CMouseState', 'CKeyboardState'}
HANDLE_TYPES = {'WgrHandle', 'WgrColor', 'Int', 'UInt32'}  # all plain numbers on js


def haxe_type(c_type):
    if c_type == 'ConstCharStar':
        return 'String'
    if c_type in ('Single',):
        return 'Float'
    if c_type in HANDLE_TYPES or c_type.startswith('C'):
        return 'Int'
    return c_type  # Bool, Float, Void


BEGIN = '\t// --- BEGIN generated by tools/gen_raw_js.py from Raw.cpp.hx ---------------'
END = '\t// --- END generated ---------------------------------------------------------'


def main():
    source = JS_RAW.read_text()
    if BEGIN not in source or END not in source:
        sys.exit(f'{JS_RAW}: missing the BEGIN/END markers the generated region needs')
    head, _, rest = source.partition(BEGIN)
    _, _, tail = rest.partition(END)
    # Only the hand-written parts count as already done: computing this over the whole
    # file would make a second run emit nothing and quietly drop the region.
    have = set(re.findall(r'function (wgr_[a-z0-9_]+)\(', head + tail))
    source = CPP_RAW.read_text()
    decls = re.findall(r'@:native\("(wgr_[a-z0-9_]+)"\)\s*\n\tstatic function \1\(([^;]*?)\):([\w<>.]+);',
                       source, re.S)
    emitted, skipped = [], []
    for name, params, ret in decls:
        ret = ret.strip()
        if name in have or name in GUEST_ABI_REPLACES or name in GUEST_ABI_OWN:
            continue
        if ret in STRUCT_RETURNS:
            skipped.append(f'{name} (returns {ret}: needs a scratch read)')
            continue
        fields = []
        for part in re.split(r',\s*', ' '.join(params.split())):
            if not part.strip():
                continue
            arg, _, c_type = part.partition(':')
            fields.append((arg.strip(), c_type.strip()))
        sig = ', '.join(f'{a}:{haxe_type(t)}' for a, t in fields)
        args = ', '.join(f'cstr({a})' if t == 'ConstCharStar' else a for a, t in fields)
        call = f'host._{name}({args})'
        if ret == 'Void':
            body = f'\t\t{call};'
        elif ret == 'Bool':
            body = f'\t\treturn {call} != 0;'
        else:
            body = f'\t\treturn {call};'
        emitted.append(f'\tpublic static inline function {name}({sig}):{haxe_type(ret)}\n{body}\n')

    JS_RAW.write_text(head + BEGIN + '\n\n' + '\n'.join(emitted) + END + tail)
    print(f'{JS_RAW.name}: {len(emitted)} wrappers generated, {len(have)} hand-written')
    if skipped:
        print('// hand-written, not generated:', file=sys.stderr)
        for s in skipped:
            print('//   ' + s, file=sys.stderr)



if __name__ == '__main__':
    main()
