#!/usr/bin/env python3
"""Regenerate the Key enum in src/wgr/Wgr.hx from wgrender's include/wgr_keys.h.

    tools/gen_keys.py [WGRENDER_DIR]

Rewrites everything between the // @@KEYS@@ markers: the `Key` enum abstract and a
`KeyCheck` class whose static_asserts fail the C++ build if the header's numbers
ever move.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
WGRENDER = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / '../../github/whirlinggizmo/wgrender-c'
SOURCE = ROOT / 'src/wgr/Wgr.hx'
BEGIN, END = '// @@KEYS@@', '// @@KEYS-END@@'


def haxe_name(macro):
    name = macro[len('WGR_KEY_'):]
    if name[0].isdigit():
        name = 'DIGIT_' + name
    return ''.join(part.capitalize() for part in name.split('_'))


def main():
    header = (WGRENDER / 'include/wgr_keys.h').resolve()
    keys = [(haxe_name(m), int(v), m) for m, v in
            re.findall(r'^\s*(WGR_KEY_[A-Z0-9_]+)\s*=\s*(\d+)', header.read_text(), re.M)]
    if not keys:
        sys.exit(f'no WGR_KEY_* found in {header}')

    enum = '\n'.join(f'\tvar {name} = {value};' for name, value, _ in keys)
    asserts = '\n'.join(
        f'static_assert(WGR_KEY_{macro[len("WGR_KEY_"):]} == {value}, '
        f'"wgr.Wgr Key.{name} is out of date with wgr_keys.h");'
        for name, value, macro in keys)

    block = f'''{BEGIN}
// Generated by tools/gen_keys.py from wgrender's include/wgr_keys.h — do not edit.

/**
\twgrender's key codes (`WGR_KEY_*`, wgr_keys.h). The numbers currently follow the
\tGLFW/sokol layout, but that is an implementation detail: code to the names.
\t`KeyCheck` below asserts them against the header at C++ compile time.
**/
enum abstract Key(Int) from Int to Int {{
{enum}

	/** C++ needs the cast: the header says `wgr_keycode_t`, not `int`. **/
	@:to inline function toRaw():CKeycode
		return untyped __cpp__("(wgr_keycode_t)({{0}})", this);
}}

@:keep
@:noCompletion
@:cppFileCode('#include <wgr_keys.h>
{asserts}')
class KeyCheck {{
\t// Exists only to give the static_asserts above a translation unit.
\tstatic function __check():Void {{}}
}}
{END}'''

    text = SOURCE.read_text()
    pattern = re.compile(re.escape(BEGIN) + r'.*?' + re.escape(END), re.S)
    text, n = pattern.subn(lambda _: block, text) if pattern.search(text) else (text.replace(BEGIN, block), 1)
    SOURCE.write_text(text)
    print(f'{SOURCE.relative_to(ROOT)}: {len(keys)} keys from {header}')


if __name__ == '__main__':
    main()
