#!/usr/bin/env python3
"""Write project/wgrender.xml: wgrender's C sources, for hxcpp to compile.

    tools/gen_sources.py [WGRENDER_DIR]         write it
    tools/gen_sources.py --check [WGRENDER_DIR]  fail if it has drifted

An installed wgrender-hx compiles wgrender from source rather than linking a prebuilt
library, which is what librl-hx does for librl: hxcpp uses MSVC on Windows by default,
MinGW objects and MSVC's linker cannot be mixed, and compiling from source means both
halves come from whatever toolchain hxcpp chose, on every platform, with nothing to
build first.

That is only possible because wgrender asks for nothing at build time: its three
shader headers are committed, its dependencies are vendored, and Python is needed to
*regenerate* shaders, not to compile. The build is a C compiler and these files.

The list is generated for the usual reason: hand-listing 47 files is a second build
to keep in step with the first, and --check fails when wgrender gains or loses one.
It comes from wgrender's build.json, its build as data: the sources, and the vendored
single-header libraries' directories.
"""
import json
import os
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from wgrpath import find  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
WGRENDER = find()
OUT = ROOT / 'project/wgrender.xml'

# The vendored single-header libraries (build.json's system_include). wgrender reaches
# them with -isystem to keep their warnings out of its -Wall -Wextra; hxcpp passes
# neither, so a plain include path is equivalent here and works in both flag syntaxes.
def vendored(manifest):
    return [d.split('/', 1)[1] for d in manifest['system_include'] if d.startswith('deps/')]


def build(sources, deps):
    includes = ['include', 'src'] + [f'deps/{d}' for d in deps]
    isystem = '\n'.join(
        f'        <compilerflag value="-I${{WGRENDER}}/{i}" />' for i in includes)
    files = '\n'.join(f'        <file name="${{WGRENDER}}/src/{s}" />' for s in sources)
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by tools/gen_sources.py from wgrender's src/. Do not edit: run the tool.

  wgrender's {len(sources)} C sources, compiled by hxcpp with whatever toolchain it chose,
  so an installed wgrender-hx needs no prebuilt library and no `make`. The in-repo
  path does not come through here; it defines WGR_BUILD_XML and links the library its
  own checkout built.
-->
<xml>
    <pragma once="true" />

    <files id="wgrender">
{isystem}

        <!-- One flag syntax for every compiler: cl.exe takes -D and -I as readily
             as /D and /I, so the two-branch version this used to have was only a way
             to get it wrong. hxcpp sets toolchain=msvc rather than a bare `msvc`
             define, so `if="msvc"` was never true and the MSVC half never
             fired, which is how /D_USE_MATH_DEFINES went missing while looking present.

             sokol's backend: GLCORE everywhere wgrender builds natively, which is
             what its own desktop builds pick for Linux, Windows and macOS.

             M_PI was here too, as -D_USE_MATH_DEFINES, until wgrender d61ae61 gave
             wgr_math_internal.h its own fallback. Keeping a flag that is no longer
             required would say it is. -->
        <compilerflag value="-DSOKOL_GLCORE" />

        <!-- wgrender is C11 (_Static_assert, among other things). The one flag that
             genuinely differs: MSVC wants /std:c11, which VS 2019 16.8 added, and
             everyone else wants -std=gnu11.

             hxcpp's conditions test whether a define exists, not what it equals, and
             it sets toolchain=msvc rather than `msvc`, so MSVC is spelled
             "windows and not mingw", which is true of exactly that combination. -->
        <compilerflag value="/std:c11" if="windows" unless="mingw" />
        <compilerflag value="-std=gnu11" unless="windows" />
        <compilerflag value="-std=gnu11" if="mingw" />

{files}
    </files>
</xml>
'''


def main():
    path = WGRENDER / 'build.json'
    if not path.exists():
        sys.exit(f'no {path}: this wgrender predates it; update the submodule')
    manifest = json.loads(path.read_text())
    sources = sorted(s.split('/', 1)[1] for s in manifest['sources'])
    deps = vendored(manifest)
    text = build(sources, deps)
    if '--check' in sys.argv:
        current = OUT.read_text() if OUT.exists() else ''
        if current != text:
            print(f'project/wgrender.xml is stale: wgrender has {len(sources)} sources\n'
                  '  run tools/gen_sources.py')
            return 1
        print(f'sources: current ({len(sources)} files, {len(deps)} vendored)')
        return 0
    for comment in re.findall(r'<!--(.*?)-->', text, re.S):
        if '--' in comment:
            sys.exit('a generated XML comment contains "--", which XML forbids:\n'
                     f'  {comment.strip()[:100]}')
    OUT.write_text(text)
    print(f'project/wgrender.xml  {len(sources)} sources, {len(deps)} vendored deps')
    return 0


if __name__ == '__main__':
    sys.exit(main())
