#!/usr/bin/env python3
"""Write project/wgrender.xml: wgrender's C sources, for hxcpp to compile.

    tools/gen_sources.py [WGRENDER_DIR]         write it
    tools/gen_sources.py --check [WGRENDER_DIR]  fail if it has drifted

An installed wgrender-hx compiles wgrender from source rather than linking a library
its Makefile built, which is what librl-hx does for librl and what makes Windows work
at all: hxcpp uses MSVC there by default, wgrender's Makefile only cross-compiles
Windows with MinGW, and the two cannot be mixed. Compiling from source means both
halves come from whatever toolchain hxcpp chose, on every platform, and `setup` needs
no `make` -- which is the other thing that stopped Windows dead.

That is only possible because wgrender asks for nothing at build time: its three
shader headers are committed, its dependencies are vendored, and Python is needed to
*regenerate* shaders, not to compile. The build is a C compiler and these files.

The list is generated for the usual reason: hand-listing 47 files is a second build
to keep in step with the first, and --check fails when wgrender gains or loses one.
"""
import os
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
WGRENDER = pathlib.Path(
    next((a for a in sys.argv[1:] if not a.startswith('--')), None)
    or os.environ.get('WGRENDER_DIR', ROOT / 'project/lib/wgrender-c')).resolve()
OUT = ROOT / 'project/wgrender.xml'

# The vendored single-header libraries. wgrender's Makefile reaches them with
# -isystem to keep their warnings out of its -Wall -Wextra; hxcpp passes neither, so
# a plain include path is equivalent here and works in both flag syntaxes. Read from
# the Makefile rather than listed, so a new one comes along on its own.
def vendored(makefile):
    text = makefile.read_text()
    seen = dict.fromkeys(re.findall(r'-isystem\s+deps/(\w+)', text))  # ordered, deduped
    return list(seen)


def build(sources, deps):
    includes = ['include', 'src'] + [f'deps/{d}' for d in deps]
    isystem = '\n'.join(
        f'        <compilerflag value="-I${{WGRENDER}}/{i}" unless="msvc" />\n'
        f'        <compilerflag value="/I${{WGRENDER}}/{i}" if="msvc" />' for i in includes)
    files = '\n'.join(f'        <file name="${{WGRENDER}}/src/{s}" />' for s in sources)
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by tools/gen_sources.py from wgrender's src/. Do not edit: run the tool.

  wgrender's {len(sources)} C sources, compiled by hxcpp with whatever toolchain it chose,
  so an installed wgrender-hx needs no prebuilt library and no `make`. The in-repo
  path does not come through here; it defines WGR_BUILD_XML and links the library its
  own checkout built.
-->
<xml>
    <pragma once="true" />

    <files id="wgrender">
{isystem}

        <!-- sokol's backend. GLCORE everywhere wgrender builds natively; its Makefile
             picks the same one for Linux and Windows. -->
        <compilerflag value="-DSOKOL_GLCORE" unless="msvc" />
        <compilerflag value="/DSOKOL_GLCORE" if="msvc" />
        <compilerflag value="-std=gnu11" if="gcc" />

        <!-- M_PI is POSIX, not C. MSVC defines it in math.h only when this is set
             first, which a command-line define is exactly the right way to do. -->
        <compilerflag value="/D_USE_MATH_DEFINES" if="msvc" />

{files}
    </files>
</xml>
'''


def main():
    src = WGRENDER / 'src'
    if not src.is_dir():
        sys.exit(f'no wgrender sources under {src}')
    sources = sorted(p.name for p in src.glob('*.c'))
    deps = vendored(WGRENDER / 'Makefile')
    text = build(sources, deps)
    if '--check' in sys.argv:
        current = OUT.read_text() if OUT.exists() else ''
        if current != text:
            print(f'project/wgrender.xml is stale: wgrender has {len(sources)} sources\n'
                  '  run tools/gen_sources.py')
            return 1
        print(f'sources: current ({len(sources)} files, {len(deps)} vendored)')
        return 0
    OUT.write_text(text)
    print(f'project/wgrender.xml  {len(sources)} sources, {len(deps)} vendored deps')
    return 0


if __name__ == '__main__':
    sys.exit(main())
