#!/usr/bin/env python3
"""Write src/wgr/Key.hx from wgrender's include/wgr_keys.h.

    tools/gen_keys.py [WGRENDER_DIR]         write it
    tools/gen_keys.py --check [WGRENDER_DIR]  fail if it has drifted

The whole file, not a region of one: it is the `Key` enum abstract and a `KeyCheck`
class whose static_asserts fail the C++ build if the header's numbers ever move.

It used to splice between `// @@KEYS@@` markers in src/wgr/Wgr.hx, which is where
Key lived before the binding went to one type per module. After the split it found
no markers, wrote the file back unchanged, and reported the key count it had parsed
-- so it looked like it was working for as long as the numbers happened not to move.
Whole files and a check mode is what the other generators do, for this reason.
"""
import os
import pathlib, re, sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from wgrpath import find  # noqa: E402
ROOT = pathlib.Path(__file__).resolve().parent.parent
# Same default as the other generators: the sibling checkout. This used to say
# ../../github/whirlinggizmo/wgrender-c, which resolved to .../github/github/... once
# the repo moved under github/whirlinggizmo itself.
WGRENDER = find()
SOURCE = ROOT / 'src/wgr/Key.hx'


def haxe_name(macro):
    name = macro[len('WGR_KEY_'):]
    if name[0].isdigit():
        name = 'DIGIT_' + name
    return ''.join(part.capitalize() for part in name.split('_'))


def main():
    header = (WGRENDER / 'include/wgr_keys.h').resolve()
    keys = [(haxe_name(m), int(v), m) for m, v in
            re.findall(r'^\s*(WGR_KEY_[A-Z0-9_]+)\s*=\s*(\d+)', header.read_text(), re.M)]
    if not keys:
        sys.exit(f'no WGR_KEY_* found in {header}')

    enum = '\n'.join(f'\tvar {name} = {value};' for name, value, _ in keys)
    asserts = '\n'.join(
        f'static_assert(WGR_KEY_{macro[len("WGR_KEY_"):]} == {value}, '
        f'"wgr.Key.{name} is out of date with wgr_keys.h");'
        for name, value, macro in keys)

    block = f'''package wgr;

// wgr_keys.h — generated by tools/gen_keys.py. Do not edit; run the tool.

/**
\twgrender's key codes (`WGR_KEY_*`, wgr_keys.h). The numbers currently follow the
\tGLFW/sokol layout, but that is an implementation detail: code to the names.
\t`KeyCheck` below asserts them against the header at C++ compile time.
**/
enum abstract Key(Int) from Int to Int {{
{enum}

	#if cpp
	/** C++ needs the cast: the header says `wgr_keycode_t`, not `int`. **/
	@:to inline function toRaw():CKeycode
		return untyped __cpp__("(wgr_keycode_t)({{0}})", this);
	#end
}}

// The static_asserts are the point: if wgrender renumbers a key, the C++ build fails
// here rather than the wrong key being pressed. js has no compiler to assert with.
#if cpp
@:keep
@:noCompletion
@:cppFileCode('#include <wgr_keys.h>
{asserts}')
class KeyCheck {{
	// Exists only to give the static_asserts above a translation unit.
	static function __check():Void {{}}
}}
#end
'''

    if '--check' in sys.argv:
        current = SOURCE.read_text() if SOURCE.exists() else ''
        if current != block:
            print(f'{SOURCE.relative_to(ROOT)} is stale ({len(keys)} keys in the header)\n'
                  '  run tools/gen_keys.py')
            return 1
        print(f'keys: current ({len(keys)} from wgr_keys.h)')
        return 0
    SOURCE.write_text(block)
    print(f'{SOURCE.relative_to(ROOT)}: {len(keys)} keys from {header}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
