#!/usr/bin/env python3
"""The host/guest build, shared by every example that uses it.

wgrender runs as a wasm host and the Haxe game is a JS guest on top of it; the same
Haxe source also builds native through hxcpp, where the glue is linked in instead.
Both halves of that are identical from one example to the next, so they live here and
an example's own build.py is a few lines:

    from guestbuild import Project
    Project(root=..., name='particles', entry='Particles').main()

Everything derived from those -- the hxml files, the page, its boot module -- is
generated into the example rather than copied between examples, because a copy is a
thing that drifts. An example is its src/ and its build.py.

    ./build.py host | guest | desktop | all | serve | sizes | clean

The host exports two sets of functions: the guest ABI (host/wgr_guest.h) and the
slice of wgrender's C API the guest calls. That slice is read out of the compiled
guest, so it is exactly what is reachable and nothing keeps a subsystem alive that
the game never touches.

Env: WGRENDER_DIR, BACKEND=webgl2|webgpu, WEB_DEBUG=0|1, HAXE.
"""
import gzip
import os
import pathlib
import shutil
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from wgrpath import find  # noqa: E402

LIB = pathlib.Path(__file__).resolve().parent.parent

# The guest ABI (host/wgr_guest.h) plus what Emscripten needs for marshalling.
GUEST_ABI = ['wgr_guest_register', 'wgr_guest_set_fault_policy', 'wgr_guest_start',
             'wgr_guest_asset_load', 'wgr_guest_frame_id', 'wgr_guest_faulted']
RUNTIME_METHODS = ['addFunction', 'removeFunction', 'stringToUTF8', 'lengthBytesUTF8', 'UTF8ToString',
                   'stackAlloc', 'stackSave', 'stackRestore', 'HEAP8', 'HEAPU8', 'HEAP32', 'HEAPU32', 'HEAPF32']

INDEX_HTML = '''<!doctype html>
<meta charset="utf-8">
<title>{title} (wgrender host, Haxe guest)</title>
<!-- Generated by guestbuild.py; edit the template there.
     Without these the module graph is a four-deep waterfall -- html, boot.js,
     wgrender-host.js, then the wasm -- and on a 150 ms link the wasm request doesn't
     start for half a second. Measured: 533 ms to the wasm request without them
     against 241 ms for wgrender's own shell, which fetches its wasm in parallel. -->
<link rel="modulepreload" href="./boot.js">
<link rel="modulepreload" href="./wgrender-host.js">
<link rel="modulepreload" href="./{name}.js">
<link rel="preload" href="./wgrender-host.wasm" as="fetch" type="application/wasm" crossorigin>
<style>
  html, body {{ margin: 0; height: 100%; background: {background}; overflow: hidden; }}
  /* CSS sizes the canvas; sokol manages the drawing buffer from it, as wgrender's
     own example shell does. Without a size here it stays at the default 300x150. */
  #canvas {{ position: fixed; inset: 0; width: 100vw; height: 100vh; display: block; outline: none; }}
</style>
<canvas id="canvas" tabindex="-1" oncontextmenu="event.preventDefault()"></canvas>
<script type="module" src="./boot.js"></script>
'''

BOOT_JS = '''// Generated by guestbuild.py. Load the host, hand it to the Haxe guest, and let the
// guest start it. The guest registers its ops before wgr_guest_start, so the host
// calls init on its own schedule rather than whenever the page finished loading.
import createWgrHost from "./wgrender-host.js";
import "./{name}.js"; // Haxe output; @:expose puts WgrGuest on the global

const canvas = document.getElementById("canvas");
const host = await createWgrHost({{ canvas, print: (t) => console.log(t), printErr: (t) => console.log(t) }});
globalThis.WgrGuest.start(host);
console.log("STARTED");
'''

GUEST_HXML = '''# Generated by guestbuild.py. The Haxe guest, compiled to JS, run on the wasm host.
-cp src
-lib wgrender-hx
--main {entry}
--js out/web/{name}.js

-D js-es=6
-dce full
-D analyzer-optimize
'''

DESKTOP_HXML = '''# Generated by guestbuild.py. The same guest source, native through hxcpp:
# wgrender and the guest glue are linked into one binary, with no wasm anywhere.
build/desktop.hxml

-cp src
-lib wgrender-hx
--main {entry}
--cpp build/cpp/desktop

-D HAXE_OUTPUT_FILE={name}-guest
-dce full
-D analyzer-optimize
'''


class Project:
    def __init__(self, root, name, entry, title=None, background='#f5f5f5'):
        self.root = pathlib.Path(root).resolve()
        self.name = name
        self.entry = entry  # the Haxe class with main(); `main` here is the CLI
        self.title = title or name
        self.background = background
        self.site = self.root / 'out/web'
        self.wgrender = find(argv=[])
        self.haxe = os.environ.get('HAXE', 'haxe')

    # ---------------------------------------------------------------- shell ---

    def run(self, cmd, **kw):
        print('+', ' '.join(str(c) for c in cmd), flush=True)
        subprocess.run([str(c) for c in cmd], check=True, **kw)

    def make(self, *args):
        web_vars = [f'{v}={os.environ[v]}' for v in ('BACKEND', 'WEB_DEBUG') if v in os.environ]
        return ['make', '--no-print-directory', '-s', '-C', self.wgrender, *args, *web_vars]

    def generate(self):
        """Write the files that are the same everywhere but for a name."""
        (self.root / 'web').mkdir(exist_ok=True)
        (self.root / 'web/index.html').write_text(
            INDEX_HTML.format(name=self.name, title=self.title, background=self.background))
        (self.root / 'web/boot.js').write_text(BOOT_JS.format(name=self.name))
        (self.root / 'guest.hxml').write_text(GUEST_HXML.format(name=self.name, entry=self.entry))
        (self.root / 'desktop.hxml').write_text(DESKTOP_HXML.format(name=self.name, entry=self.entry))

    def check_binding(self):
        """The binding is generated from wgrender's headers; a stale one declares an
        API that no longer exists, and a stale omissions list hides a decision."""
        self.run([LIB / 'tools/gen_raw.py', '--check', self.wgrender])
        self.run([LIB / 'tools/coverage.py', '--check', self.wgrender])
        self.run([LIB / 'tools/setters.py', '--check', self.wgrender])

    # ---------------------------------------------------------------- build ---

    def wgr_api(self):
        """What to export from the host: exactly the calls the built guest makes.

        The binding declares wgrender's whole API, so exporting all of it would keep
        every subsystem alive in the wasm -- Emscripten cannot strip what is exported.
        Reading the compiled guest instead lets the unused ones go (75 KB, measured),
        and needs no list to maintain. The guest is built first for this reason.
        """
        import re
        guest = self.site / f'{self.name}.js'
        if not guest.exists():
            sys.exit(f'build the guest first: ./build.py guest (or ./build.py all)')
        names = sorted(set(re.findall(r'\b_(wgr_[a-z0-9_]+)\b', guest.read_text())))
        if not names:
            sys.exit(f'{guest}: no _wgr_* calls found -- did the guest compile?')
        return names

    def web_flags(self):
        out = subprocess.run([str(c) for c in self.make('print-web-flags', 'WEB_THREADS=0')],
                             check=True, capture_output=True, text=True).stdout
        flags = {k.strip(): v.strip() for k, _, v in (l.partition(':') for l in out.splitlines())}
        if 'lib' not in flags:
            sys.exit(f'could not read wgrender web flags:\n{out}')
        return self.wgrender / flags['lib'], flags.get('ldflags', '').split()

    def build_guest(self):
        self.generate()
        self.check_binding()
        self.site.mkdir(parents=True, exist_ok=True)
        print(f'guest -> out/web/{self.name}.js')
        self.run([self.haxe, 'guest.hxml'], cwd=self.root)
        for page in ('index.html', 'boot.js'):
            shutil.copy2(self.root / 'web' / page, self.site / page)
        self.sizes()

    def build_host(self):
        self.check_binding()
        print('wgrender (web)')
        self.run(self.make('web', 'WEB_THREADS=0'))
        lib, ldflags = self.web_flags()
        api = self.wgr_api()
        exported = ['_main'] + [f'_{n}' for n in GUEST_ABI + api] + ['_malloc', '_free']
        self.site.mkdir(parents=True, exist_ok=True)
        print(f'host -> out/web/wgrender-host.js ({len(api)} wgrender calls the guest makes)')
        self.run(['emcc', '-O2', f'-I{self.wgrender}/include', f'-I{LIB}/host',
                  str(LIB / 'host/wgr_guest.c'), str(lib), *ldflags,
                  # the guest installs its ops as JS functions turned into C pointers
                  '-sALLOW_TABLE_GROWTH=1',
                  '-sMODULARIZE=1', '-sEXPORT_ES6=1', '-sEXPORT_NAME=createWgrHost',
                  f'-sEXPORTED_RUNTIME_METHODS={",".join(RUNTIME_METHODS)}',
                  f'-sEXPORTED_FUNCTIONS={",".join(exported)}',
                  '-o', self.site / 'wgrender-host.js'], cwd=self.root)

    def build_desktop(self):
        """The same guest, native: hxcpp links wgrender and the glue into one binary."""
        self.generate()
        self.check_binding()
        print('wgrender (desktop)')
        self.run(self.make('all'))
        build = self.root / 'build'
        build.mkdir(exist_ok=True)
        libs = [str(self.wgrender / 'build/desktop/libwgrender.a'),
                '-lGL', '-lX11', '-lXi', '-lXcursor', '-lXrandr', '-lasound', '-ldl', '-lm', '-lpthread']
        # hxcpp compiles the glue itself, so there is no separate C build step.
        (build / 'desktop.xml').write_text(f"""<xml>
<!-- Generated by guestbuild.py. Pulled in by the @:buildXml on wgr.impl.Raw. -->
  <files id="wgrguest">
    <compilerflag value="-I{self.wgrender}/include" />
    <compilerflag value="-I{LIB}/host" />
    <file name="{LIB}/host/wgr_guest.c" />
  </files>
  <files id="haxe">
    <compilerflag value="-I{self.wgrender}/include" />
    <compilerflag value="-I{LIB}/host" />
  </files>
  <target id="haxe">
    <files id="wgrguest" />
{chr(10).join(f'    <lib name="{l}" />' for l in libs)}
  </target>
</xml>
""")
        (build / 'desktop.hxml').write_text(
            '# Generated by guestbuild.py -- where wgrender is on this machine.\n'
            f'-D WGR_BUILD_XML={build / "desktop.xml"}\n')
        print(f'desktop -> out/desktop/{self.name}-guest')
        self.run([self.haxe, 'desktop.hxml'], cwd=self.root)
        out = self.root / 'out/desktop'
        out.mkdir(parents=True, exist_ok=True)
        shutil.copy2(build / f'cpp/desktop/{self.name}-guest', out / f'{self.name}-guest')
        # wgr.Assets looks for `assets` beside the executable, so a development build
        # gets one pointing at wgrender's tree -- the same lookup a shipped program
        # uses, rather than a path baked in at compile time.
        link = out / 'assets'
        if link.is_symlink() or link.exists():
            link.unlink()
        link.symlink_to(self.wgrender / 'examples/assets')
        print(f'built {out}/{self.name}-guest (assets -> {link.readlink()})')

    # ----------------------------------------------------------------- misc ---

    def sizes(self):
        rows = [('host wasm', self.site / 'wgrender-host.wasm'),
                ('host js', self.site / 'wgrender-host.js'),
                ('guest js', self.site / f'{self.name}.js')]
        total = 0
        for label, path in rows:
            if not path.exists():
                print(f'{label:<12} (not built)')
                continue
            raw = path.stat().st_size
            total += raw
            print(f'{label:<12} {raw:>10,} bytes ({len(gzip.compress(path.read_bytes(), 9)):>9,} gzipped)')
        if total:
            print(f'{"total":<12} {total:>10,} bytes')

    def serve(self):
        self.run(['python3', self.wgrender / 'tools/serve.py', '8000', self.site])

    def clean(self):
        for d in ('out', 'build'):
            shutil.rmtree(self.root / d, ignore_errors=True)
        print('removed out/ and build/')

    def main(self):
        command = sys.argv[1] if len(sys.argv) > 1 else ''
        if command == 'host':
            self.build_host()
        elif command == 'guest':
            self.build_guest()
        elif command == 'desktop':
            self.build_desktop()
        elif command == 'all':
            self.build_guest()   # first: the host exports exactly what this calls
            self.build_host()
            self.build_desktop()
        elif command == 'generate':
            self.generate()
            print('regenerated the page, boot module and hxml files')
        elif command == 'sizes':
            self.sizes()
        elif command == 'serve':
            self.serve()
        elif command == 'clean':
            self.clean()
        else:
            sys.exit(__doc__)
